// cidadesSE.js
const cidadesSE = {
    '#empty_option': '- Selecione a Cidade -',
    '#options': {
      amparo_de_sao_francisco: 'Amparo de São Francisco',
      aquidaba: 'Aquidabã',
      aracaju: 'Aracaju',
      araua: 'Arauá',
      areia_branca: 'Areia Branca',
      barra_dos_coqueiros: 'Barra dos Coqueiros',
      boquim: 'Boquim',
      brejo_grande: 'Brejo Grande',
      campo_do_brito: 'Campo do Brito',
      canhoba: 'Canhoba',
      caninde_de_sao_francisco: 'Canindé de São Francisco',
      capela: 'Capela',
      carira: 'Carira',
      carmopolis: 'Carmópolis',
      cedro_de_sao_joao: 'Cedro de São João',
      cristinapolis: 'Cristinápolis',
      cumbe: 'Cumbe',
      divina_pastora: 'Divina Pastora',
      estancia: 'Estância',
      feira_nova: 'Feira Nova',
      frei_paulo: 'Frei Paulo',
      gararu: 'Gararu',
      general_maynard: 'General Maynard',
      graccho_cardoso: 'Graccho Cardoso',
      ilha_das_flores: 'Ilha das Flores',
      indiaroba: 'Indiaroba',
      itabaiana: 'Itabaiana',
      itabaianinha: 'Itabaianinha',
      itabi: 'Itabi',
      itaporanga_dajuda: 'Itaporanga dAjuda',
      japaratuba: 'Japaratuba',
      japoata: 'Japoatã',
      lagarto: 'Lagarto',
      laranjeiras: 'Laranjeiras',
      macambira: 'Macambira',
      malhada_dos_bois: 'Malhada dos Bois',
      malhador: 'Malhador',
      maruim: 'Maruim',
      moita_bonita: 'Moita Bonita',
      monte_alegre_de_sergipe: 'Monte Alegre de Sergipe',
      muribeca: 'Muribeca',
      neopolis: 'Neópolis',
      nossa_senhora_aparecida: 'Nossa Senhora Aparecida',
      nossa_senhora_da_gloria: 'Nossa Senhora da Glória',
      nossa_senhora_das_dores: 'Nossa Senhora das Dores',
      nossa_senhora_de_lourdes: 'Nossa Senhora de Lourdes',
      nossa_senhora_do_socorro: 'Nossa Senhora do Socorro',
      pacatuba: 'Pacatuba',
      pedra_mole: 'Pedra Mole',
      pedrinhas: 'Pedrinhas',
      pinhao: 'Pinhão',
      pirambu: 'Pirambu',
      poco_redondo: 'Poço Redondo',
      poco_verde: 'Poço Verde',
      porto_da_folha: 'Porto da Folha',
      propria: 'Propriá',
      riachao_do_dantas: 'Riachão do Dantas',
      riachuelo: 'Riachuelo',
      ribeiropolis: 'Ribeirópolis',
      rosario_do_catete: 'Rosário do Catete',
      salgado: 'Salgado',
      santa_luzia_do_itanhy: 'Santa Luzia do Itanhy',
      santa_rosa_de_lima: 'Santa Rosa de Lima',
      santana_do_sao_francisco: 'Santana do São Francisco',
      santo_amaro_das_brotas: 'Santo Amaro das Brotas',
      sao_cristovao: 'São Cristóvão',
      sao_domingos: 'São Domingos',
      sao_francisco: 'São Francisco',
      sao_miguel_do_aleixo: 'São Miguel do Aleixo',
      simao_dias: 'Simão Dias',
      siriri: 'Siriri',
      telha: 'Telha',
      tobias_barreto: 'Tobias Barreto',
      tomar_do_geru: 'Tomar do Geru',
      umbauba: 'Umbaúba',
    },
    '#Estado': 'SE',
  };
  
  export default cidadesSE;