const cidadesRN = {
    '#empty_option': '- Selecione a Cidade -',
    '#options': {
      acari: 'Acari',
      afonso_bezerra: 'Afonso Bezerra',
      agua_nova: 'Água Nova',
      alexandria: 'Alexandria',
      almino_afonso: 'Almino Afonso',
      alto_do_rodrigues: 'Alto do Rodrigues',
      angicos: 'Angicos',
      antonio_martins: 'Antônio Martins',
      apodi: 'Apodi',
      areia_branca: 'Areia Branca',
      arez: 'Arez',
      assu: 'Assu',
      baia_formosa: 'Baía Formosa',
      barauna: 'Baraúna',
      barcelona: 'Barcelona',
      bento_fernandes: 'Bento Fernandes',
      boa_saude: 'Boa Saúde',
      bodo: 'Bodó',
      bom_jesus: 'Bom Jesus',
      brejinho: 'Brejinho',
      caicara_do_norte: 'Caiçara do Norte',
      caicara_do_rio_do_vento: 'Caiçara do Rio do Vento',
      caico: 'Caicó',
      campo_grande: 'Campo Grande',
      campo_redondo: 'Campo Redondo',
      canguaretama: 'Canguaretama',
      caraubas: 'Caraúbas',
      carnauba_dos_dantas: 'Carnaúba dos Dantas',
      carnaubais: 'Carnaubais',
      ceara_mirim: 'Ceará-Mirim',
      cerro_cora: 'Cerro Corá',
      coronel_ezequiel: 'Coronel Ezequiel',
      coronel_joao_pessoa: 'Coronel João Pessoa',
      cruzeta: 'Cruzeta',
      currais_novos: 'Currais Novos',
      doutor_severiano: 'Doutor Severiano',
      encanto: 'Encanto',
      equador: 'Equador',
      espirito_santo: 'Espírito Santo',
      extremoz: 'Extremoz',
      felipe_guerra: 'Felipe Guerra',
      fernando_pedroza: 'Fernando Pedroza',
      florania: 'Florânia',
      francisco_dantas: 'Francisco Dantas',
      frutuoso_gomes: 'Frutuoso Gomes',
      galinhos: 'Galinhos',
      goianinha: 'Goianinha',
      governador_dix_sept_rosado: 'Governador Dix-Sept Rosado',
      grossos: 'Grossos',
      guamare: 'Guamaré',
      ielmo_marinho: 'Ielmo Marinho',
      ipanguacu: 'Ipanguaçu',
      ipueira: 'Ipueira',
      itaja: 'Itajá',
      itau: 'Itaú',
      jacana: 'Jaçanã',
      jandaira: 'Jandaíra',
      janduis: 'Janduís',
      japi: 'Japi',
      jardim_de_angicos: 'Jardim de Angicos',
      jardim_de_piranhas: 'Jardim de Piranhas',
      jardim_do_serido: 'Jardim do Seridó',
      joao_camara: 'João Câmara',
      joao_dias: 'João Dias',
      jose_da_penha: 'José da Penha',
      jucurutu: 'Jucurutu',
      jundia: 'Jundiá',
      lagoa_danta: 'Lagoa dAnta',
      lagoa_de_pedras: 'Lagoa de Pedras',
      lagoa_de_velhos: 'Lagoa de Velhos',
      lagoa_nova: 'Lagoa Nova',
      lagoa_salgada: 'Lagoa Salgada',
      lajes: 'Lajes',
      lajes_pintadas: 'Lajes Pintadas',
      lucrecia: 'Lucrécia',
      luis_gomes: 'Luís Gomes',
      macaiba: 'Macaíba',
      macau: 'Macau',
      major_sales: 'Major Sales',
      marcelino_vieira: 'Marcelino Vieira',
      martins: 'Martins',
      maxaranguape: 'Maxaranguape',
      messias_targino: 'Messias Targino',
      montanhas: 'Montanhas',
      monte_alegre: 'Monte Alegre',
      monte_das_gameleiras: 'Monte das Gameleiras',
      mossoro: 'Mossoró',
      natal: 'Natal',
      nisia_floresta: 'Nísia Floresta',
      nova_cruz: 'Nova Cruz',
      olho_dagua_do_borges: 'Olho-dÁgua do Borges',
      ouro_branco: 'Ouro Branco',
      parana: 'Paraná',
      parau: 'Paraú',
      parazinho: 'Parazinho',
      parelhas: 'Parelhas',
      parnamirim: 'Parnamirim',
      passa_e_fica: 'Passa-e-Fica',
      passagem: 'Passagem',
      patu: 'Patu',
      pau_dos_ferros: 'Pau dos Ferros',
      pedra_grande: 'Pedra Grande',
      pedra_preta: 'Pedra Preta',
      pedro_avelino: 'Pedro Avelino',
      pedro_velho: 'Pedro Velho',
      pendencias: 'Pendências',
      piloes: 'Pilões',
      poco_branco: 'Poço Branco',
      portalegre: 'Portalegre',
      porto_do_mangue: 'Porto do Mangue',
      pureza: 'Pureza',
      rafael_fernandes: 'Rafael Fernandes',
      rafael_godeiro: 'Rafael Godeiro',
      riacho_da_cruz: 'Riacho da Cruz',
      riacho_de_santana: 'Riacho de Santana',
      riachuelo: 'Riachuelo',
      rio_do_fogo: 'Rio do Fogo',
      rodolfo_fernandes: 'Rodolfo Fernandes',
      ruy_barbosa: 'Ruy Barbosa',
      santa_cruz: 'Santa Cruz',
      santa_maria: 'Santa Maria',
      santana_do_matos: 'Santana do Matos',
      santana_do_serido: 'Santana do Seridó',
      santo_antonio: 'Santo Antônio',
      sao_bento_do_norte: 'São Bento do Norte',
      sao_bento_do_trairi: 'São Bento do Trairi',
      sao_fernando: 'São Fernando',
      sao_francisco_do_oeste: 'São Francisco do Oeste',
      sao_goncalo_do_amarante: 'São Gonçalo do Amarante',
      sao_joao_do_sabugi: 'São João do Sabugi',
      sao_jose_de_mipibu: 'São José de Mipibu',
      sao_jose_do_campestre: 'São José do Campestre',
      sao_jose_do_serido: 'São José do Seridó',
      sao_miguel: 'São Miguel',
      sao_miguel_do_gostoso: 'São Miguel do Gostoso',
      sao_paulo_do_potengi: 'São Paulo do Potengi',
      sao_pedro: 'São Pedro',
      sao_rafael: 'São Rafael',
      sao_tome: 'São Tomé',
      sao_vicente: 'São Vicente',
      senador_eloi_de_souza: 'Senador Elói de Souza',
      senador_georgino_avelino: 'Senador Georgino Avelino',
      serra_caiada: 'Serra Caiada',
      serra_de_sao_bento: 'Serra de São Bento',
      serra_do_mel: 'Serra do Mel',
      serra_negra_do_norte: 'Serra Negra do Norte',
      serrinha: 'Serrinha',
      serrinha_dos_pintos: 'Serrinha dos Pintos',
      severiano_melo: 'Severiano Melo',
      sitio_novo: 'Sítio Novo',
      taboleiro_grande: 'Taboleiro Grande',
      taipu: 'Taipu',
      tangara: 'Tangará',
      tenente_ananias: 'Tenente Ananias',
      tenente_laurentino_cruz: 'Tenente Laurentino Cruz',
      tibau: 'Tibau',
      tibau_do_sul: 'Tibau do Sul',
      timbauba_dos_batistas: 'Timbaúba dos Batistas',
      touros: 'Touros',
      triunfo_potiguar: 'Triunfo Potiguar',
      umarizal: 'Umarizal',
      upanema: 'Upanema',
      varzea: 'Várzea',
      venha_ver: 'Venha-Ver',
      vera_cruz: 'Vera Cruz',
      vicosa: 'Viçosa',
      vila_flor: 'Vila Flor',
    },
    '#Estado': 'RN',
  };
  
  export default cidadesRN;