// cidadesRJ.js
const cidadesRJ = {
    '#empty_option': '- Selecione a Cidade -',
    '#options': {
      angra_dos_reis: 'Angra dos Reis',
      aperibe: 'Aperibé',
      araruama: 'Araruama',
      areal: 'Areal',
      armacao_dos_buzios: 'Armação dos Búzios',
      arraial_do_cabo: 'Arraial do Cabo',
      barra_do_pirai: 'Barra do Piraí',
      barra_mansa: 'Barra Mansa',
      belford_roxo: 'Belford Roxo',
      bom_jardim: 'Bom Jardim',
      bom_jesus_do_itabapoana: 'Bom Jesus do Itabapoana',
      cabo_frio: 'Cabo Frio',
      cachoeiras_de_macacu: 'Cachoeiras de Macacu',
      cambuci: 'Cambuci',
      campos_dos_goytacazes: 'Campos dos Goytacazes',
      cantagalo: 'Cantagalo',
      carapebus: 'Carapebus',
      cardoso_moreira: 'Cardoso Moreira',
      carmo: 'Carmo',
      casimiro_de_abreu: 'Casimiro de Abreu',
      comendador_levy_gasparian: 'Comendador Levy Gasparian',
      conceicao_de_macabu: 'Conceição de Macabu',
      cordeiro: 'Cordeiro',
      duas_barras: 'Duas Barras',
      duque_de_caxias: 'Duque de Caxias',
      engenheiro_paulo_de_frontin: 'Engenheiro Paulo de Frontin',
      guapimirim: 'Guapimirim',
      iguaba_grande: 'Iguaba Grande',
      itaborai: 'Itaboraí',
      itaguai: 'Itaguaí',
      italva: 'Italva',
      itaocara: 'Itaocara',
      itaperuna: 'Itaperuna',
      itatiaia: 'Itatiaia',
      japeri: 'Japeri',
      laje_do_muriae: 'Laje do Muriaé',
      macae: 'Macaé',
      macuco: 'Macuco',
      mage: 'Magé',
      mangaratiba: 'Mangaratiba',
      marica: 'Maricá',
      mendes: 'Mendes',
      mesquita: 'Mesquita',
      miguel_pereira: 'Miguel Pereira',
      miracema: 'Miracema',
      natividade: 'Natividade',
      nilopolis: 'Nilópolis',
      niteroi: 'Niterói',
      nova_friburgo: 'Nova Friburgo',
      nova_iguacu: 'Nova Iguaçu',
      paracambi: 'Paracambi',
      paraiba_do_sul: 'Paraíba do Sul',
      paraty: 'Paraty',
      paty_do_alferes: 'Paty do Alferes',
      petropolis: 'Petrópolis',
      pinheiral: 'Pinheiral',
      pirai: 'Piraí',
      porciuncula: 'Porciúncula',
      porto_real: 'Porto Real',
      quatis: 'Quatis',
      queimados: 'Queimados',
      quissama: 'Quissamã',
      resende: 'Resende',
      rio_bonito: 'Rio Bonito',
      rio_claro: 'Rio Claro',
      rio_das_flores: 'Rio das Flores',
      rio_das_ostras: 'Rio das Ostras',
      rio_de_janeiro: 'Rio de Janeiro',
      santa_maria_madalena: 'Santa Maria Madalena',
      santo_antonio_de_padua: 'Santo Antônio de Pádua',
      sao_fidelis: 'São Fidélis',
      sao_francisco_de_itabapoana: 'São Francisco de Itabapoana',
      sao_goncalo: 'São Gonçalo',
      sao_joao_da_barra: 'São João da Barra',
      sao_joao_de_meriti: 'São João de Meriti',
      sao_jose_de_uba: 'São José de Ubá',
      sao_jose_do_vale_do_rio_preto: 'São José do Vale do Rio Preto',
      sao_pedro_da_aldeia: 'São Pedro da Aldeia',
      sao_sebastiao_do_alto: 'São Sebastião do Alto',
      sapucaia: 'Sapucaia',
      saquarema: 'Saquarema',
      seropedica: 'Seropédica',
      silva_jardim: 'Silva Jardim',
      sumidouro: 'Sumidouro',
      tangua: 'Tanguá',
      teresopolis: 'Teresópolis',
      trajano_de_moraes: 'Trajano de Moraes',
      tres_rios: 'Três Rios',
      valenca: 'Valença',
      varre_sai: 'Varre-Sai',
      vassouras: 'Vassouras',
      volta_redonda: 'Volta Redonda',
    },
    '#Estado': 'RJ',
  };
  
  export default cidadesRJ;