const cidadesPA = {
    '#empty_option': '- Selecione a Cidade -',
    '#options': {
      abaetetuba: 'Abaetetuba',
      abel_figueiredo: 'Abel Figueiredo',
      acara: 'Acará',
      afua: 'Afuá',
      agua_azul_do_norte: 'Água Azul do Norte',
      alenquer: 'Alenquer',
      almeirim: 'Almeirim',
      altamira: 'Altamira',
      anajas: 'Anajás',
      ananindeua: 'Ananindeua',
      anapu: 'Anapu',
      augusto_correa: 'Augusto Corrêa',
      aurora_do_para: 'Aurora do Pará',
      aveiro: 'Aveiro',
      bagre: 'Bagre',
      baiao: 'Baião',
      bannach: 'Bannach',
      barcarena: 'Barcarena',
      belem: 'Belém',
      belterra: 'Belterra',
      benevides: 'Benevides',
      bom_jesus_do_tocantins: 'Bom Jesus do Tocantins',
      bonito: 'Bonito',
      braganca: 'Bragança',
      brasil_novo: 'Brasil Novo',
      brejo_grande_do_araguaia: 'Brejo Grande do Araguaia',
      breu_branco: 'Breu Branco',
      breves: 'Breves',
      bujaru: 'Bujaru',
      cachoeira_do_arari: 'Cachoeira do Arari',
      cachoeira_do_piria: 'Cachoeira do Piriá',
      cameta: 'Cametá',
      canaa_dos_carajas: 'Canaã dos Carajás',
      capanema: 'Capanema',
      capitao_poco: 'Capitão Poço',
      castanhal: 'Castanhal',
      chaves: 'Chaves',
      colares: 'Colares',
      conceicao_do_araguaia: 'Conceição do Araguaia',
      concordia_do_para: 'Concórdia do Pará',
      cumaru_do_norte: 'Cumaru do Norte',
      curionopolis: 'Curionópolis',
      curralinho: 'Curralinho',
      curua: 'Curuá',
      curuca: 'Curuçá',
      dom_eliseu: 'Dom Eliseu',
      eldorado_do_carajas: 'Eldorado do Carajás',
      faro: 'Faro',
      floresta_do_araguaia: 'Floresta do Araguaia',
      garrafao_do_norte: 'Garrafão do Norte',
      goianesia_do_para: 'Goianésia do Pará',
      gurupa: 'Gurupá',
      igarape_acu: 'Igarapé-Açu',
      igarape_miri: 'Igarapé-Miri',
      inhangapi: 'Inhangapi',
      ipixuna_do_para: 'Ipixuna do Pará',
      irituia: 'Irituia',
      itaituba: 'Itaituba',
      itupiranga: 'Itupiranga',
      jacareacanga: 'Jacareacanga',
      jacunda: 'Jacundá',
      juruti: 'Juruti',
      limoeiro_do_ajuru: 'Limoeiro do Ajuru',
      mae_do_rio: 'Mãe do Rio',
      magalhaes_barata: 'Magalhães Barata',
      maraba: 'Marabá',
      maracana: 'Maracanã',
      marapanim: 'Marapanim',
      marituba: 'Marituba',
      medicilandia: 'Medicilândia',
      melgaco: 'Melgaço',
      mocajuba: 'Mocajuba',
      moju: 'Moju',
      mojui_dos_campos: 'Mojuí dos Campos',
      monte_alegre: 'Monte Alegre',
      muana: 'Muaná',
      nova_esperanca_do_piria: 'Nova Esperança do Piriá',
      nova_ipixuna: 'Nova Ipixuna',
      nova_timboteua: 'Nova Timboteua',
      novo_progresso: 'Novo Progresso',
      novo_repartimento: 'Novo Repartimento',
      obidos: 'Óbidos',
      oeiras_do_para: 'Oeiras do Pará',
      oriximina: 'Oriximiná',
      ourem: 'Ourém',
      ourilandia_do_norte: 'Ourilândia do Norte',
      pacaja: 'Pacajá',
      palestina_do_para: 'Palestina do Pará',
      paragominas: 'Paragominas',
      parauapebas: 'Parauapebas',
      pau_darco: 'Pau-dArco',
      peixe_boi: 'Peixe-Boi',
      picarra: 'Piçarra',
      placas: 'Placas',
      ponta_de_pedras: 'Ponta de Pedras',
      portel: 'Portel',
      porto_de_moz: 'Porto de Moz',
      prainha: 'Prainha',
      primavera: 'Primavera',
      quatipuru: 'Quatipuru',
      redencao: 'Redenção',
      rio_maria: 'Rio Maria',
      rondon_do_para: 'Rondon do Pará',
      ruropolis: 'Rurópolis',
      salinopolis: 'Salinópolis',
      salvaterra: 'Salvaterra',
      santa_barbara_do_para: 'Santa Bárbara do Pará',
      santa_cruz_do_arari: 'Santa Cruz do Arari',
      santa_izabel_do_para: 'Santa Izabel do Pará',
      santa_luzia_do_para: 'Santa Luzia do Pará',
      santa_maria_das_barreiras: 'Santa Maria das Barreiras',
      santa_maria_do_para: 'Santa Maria do Pará',
      santana_do_araguaia: 'Santana do Araguaia',
      santarem: 'Santarém',
      santarem_novo: 'Santarém Novo',
      santo_antonio_do_taua: 'Santo Antônio do Tauá',
      sao_caetano_de_odivelas: 'São Caetano de Odivelas',
      sao_domingos_do_araguaia: 'São Domingos do Araguaia',
      sao_domingos_do_capim: 'São Domingos do Capim',
      sao_felix_do_xingu: 'São Félix do Xingu',
      sao_francisco_do_para: 'São Francisco do Pará',
      sao_geraldo_do_araguaia: 'São Geraldo do Araguaia',
      sao_joao_da_ponta: 'São João da Ponta',
      sao_joao_de_pirabas: 'São João de Pirabas',
      sao_joao_do_araguaia: 'São João do Araguaia',
      sao_miguel_do_guama: 'São Miguel do Guamá',
      sao_sebastiao_da_boa_vista: 'São Sebastião da Boa Vista',
      sapucaia: 'Sapucaia',
      senador_jose_porfirio: 'Senador José Porfírio',
      soure: 'Soure',
      tailandia: 'Tailândia',
      terra_alta: 'Terra Alta',
      terra_santa: 'Terra Santa',
      tome_acu: 'Tomé-Açu',
      tracuateua: 'Tracuateua',
      trairao: 'Trairão',
      tucuma: 'Tucumã',
      tucurui: 'Tucuruí',
      ulianopolis: 'Ulianópolis',
      uruara: 'Uruará',
      vigia: 'Vigia',
      viseu: 'Viseu',
      vitoria_do_xingu: 'Vitória do Xingu',
      xinguara: 'Xinguara',
    },
    '#Estado': 'PA',
  };
  
  export default cidadesPA;