const cidadesPB = {
    '#empty_option': '- Selecione a Cidade -',
    '#options': {
      agua_branca: 'Água Branca',
      aguiar: 'Aguiar',
      alagoa_grande: 'Alagoa Grande',
      alagoa_nova: 'Alagoa Nova',
      alagoinha: 'Alagoinha',
      alcantil: 'Alcantil',
      algodao_de_jandaira: 'Algodão de Jandaíra',
      alhandra: 'Alhandra',
      amparo: 'Amparo',
      aparecida: 'Aparecida',
      aracagi: 'Araçagi',
      arara: 'Arara',
      araruna: 'Araruna',
      areia: 'Areia',
      areia_de_baraunas: 'Areia de Baraúnas',
      areial: 'Areial',
      aroeiras: 'Aroeiras',
      assuncao: 'Assunção',
      baia_da_traicao: 'Baía da Traição',
      bananeiras: 'Bananeiras',
      barauna: 'Baraúna',
      barra_de_santa_rosa: 'Barra de Santa Rosa',
      barra_de_santana: 'Barra de Santana',
      barra_de_sao_miguel: 'Barra de São Miguel',
      bayeux: 'Bayeux',
      belem: 'Belém',
      belem_do_brejo_do_cruz: 'Belém do Brejo do Cruz',
      bernardino_batista: 'Bernardino Batista',
      boa_ventura: 'Boa Ventura',
      boa_vista: 'Boa Vista',
      bom_jesus: 'Bom Jesus',
      bom_sucesso: 'Bom Sucesso',
      bonito_de_santa_fe: 'Bonito de Santa Fé',
      boqueirao: 'Boqueirão',
      borborema: 'Borborema',
      brejo_do_cruz: 'Brejo do Cruz',
      brejo_dos_santos: 'Brejo dos Santos',
      caapora: 'Caaporã',
      cabaceiras: 'Cabaceiras',
      cabedelo: 'Cabedelo',
      cachoeira_dos_indios: 'Cachoeira dos Índios',
      cacimba_de_areia: 'Cacimba de Areia',
      cacimba_de_dentro: 'Cacimba de Dentro',
      cacimbas: 'Cacimbas',
      caicara: 'Caiçara',
      cajazeiras: 'Cajazeiras',
      cajazeirinhas: 'Cajazeirinhas',
      caldas_brandao: 'Caldas Brandão',
      camalau: 'Camalaú',
      campina_grande: 'Campina Grande',
      capim: 'Capim',
      caraubas: 'Caraúbas',
      carrapateira: 'Carrapateira',
      casserengue: 'Casserengue',
      catingueira: 'Catingueira',
      catole_do_rocha: 'Catolé do Rocha',
      caturite: 'Caturité',
      conceicao: 'Conceição',
      condado: 'Condado',
      conde: 'Conde',
      congo: 'Congo',
      coremas: 'Coremas',
      coxixola: 'Coxixola',
      cruz_do_espirito_santo: 'Cruz do Espírito Santo',
      cubati: 'Cubati',
      cuite: 'Cuité',
      cuite_de_mamanguape: 'Cuité de Mamanguape',
      cuitegi: 'Cuitegi',
      curral_de_cima: 'Curral de Cima',
      curral_velho: 'Curral Velho',
      damiao: 'Damião',
      desterro: 'Desterro',
      diamante: 'Diamante',
      dona_ines: 'Dona Inês',
      duas_estradas: 'Duas Estradas',
      emas: 'Emas',
      esperanca: 'Esperança',
      fagundes: 'Fagundes',
      frei_martinho: 'Frei Martinho',
      gado_bravo: 'Gado Bravo',
      guarabira: 'Guarabira',
      gurinhem: 'Gurinhém',
      gurjao: 'Gurjão',
      ibiara: 'Ibiara',
      igaracy: 'Igaracy',
      imaculada: 'Imaculada',
      inga: 'Ingá',
      itabaiana: 'Itabaiana',
      itaporanga: 'Itaporanga',
      itapororoca: 'Itapororoca',
      itatuba: 'Itatuba',
      jacarau: 'Jacaraú',
      jerico: 'Jericó',
      joao_pessoa: 'João Pessoa',
      joca_claudino_ex_santarem: 'Joca Claudino (ex-Santarém)',
      juarez_tavora: 'Juarez Távora',
      juazeirinho: 'Juazeirinho',
      junco_do_serido: 'Junco do Seridó',
      juripiranga: 'Juripiranga',
      juru: 'Juru',
      lagoa: 'Lagoa',
      lagoa_de_dentro: 'Lagoa de Dentro',
      lagoa_seca: 'Lagoa Seca',
      lastro: 'Lastro',
      livramento: 'Livramento',
      logradouro: 'Logradouro',
      lucena: 'Lucena',
      mae_dagua: 'Mãe dÁgua',
      malta: 'Malta',
      mamanguape: 'Mamanguape',
      manaira: 'Manaíra',
      marcacao: 'Marcação',
      mari: 'Mari',
      marizopolis: 'Marizópolis',
      massaranduba: 'Massaranduba',
      mataraca: 'Mataraca',
      matinhas: 'Matinhas',
      mato_grosso: 'Mato Grosso',
      matureia: 'Matureia',
      mogeiro: 'Mogeiro',
      montadas: 'Montadas',
      monte_horebe: 'Monte Horebe',
      monteiro: 'Monteiro',
      mulungu: 'Mulungu',
      natuba: 'Natuba',
      nazarezinho: 'Nazarezinho',
      nova_floresta: 'Nova Floresta',
      nova_olinda: 'Nova Olinda',
      nova_palmeira: 'Nova Palmeira',
      olho_dagua: 'Olho dÁgua',
      olivedos: 'Olivedos',
      ouro_velho: 'Ouro Velho',
      parari: 'Parari',
      passagem: 'Passagem',
      patos: 'Patos',
      paulista: 'Paulista',
      pedra_branca: 'Pedra Branca',
      pedra_lavrada: 'Pedra Lavrada',
      pedras_de_fogo: 'Pedras de Fogo',
      pedro_regis: 'Pedro Régis',
      pianco: 'Piancó',
      picui: 'Picuí',
      pilar: 'Pilar',
      piloes: 'Pilões',
      piloezinhos: 'Pilõezinhos',
      pirpirituba: 'Pirpirituba',
      pitimbu: 'Pitimbu',
      pocinhos: 'Pocinhos',
      poco_dantas: 'Poço Dantas',
      poco_de_jose_de_moura: 'Poço de José de Moura',
      pombal: 'Pombal',
      prata: 'Prata',
      princesa_isabel: 'Princesa Isabel',
      puxinana: 'Puxinanã',
      queimadas: 'Queimadas',
      quixaba: 'Quixaba',
      remigio: 'Remígio',
      riachao: 'Riachão',
      riachao_do_bacamarte: 'Riachão do Bacamarte',
      riachao_do_poco: 'Riachão do Poço',
      riacho_de_santo_antonio: 'Riacho de Santo Antônio',
      riacho_dos_cavalos: 'Riacho dos Cavalos',
      rio_tinto: 'Rio Tinto',
      salgadinho: 'Salgadinho',
      salgado_de_sao_felix: 'Salgado de São Félix',
      santa_cecilia: 'Santa Cecília',
      santa_cruz: 'Santa Cruz',
      santa_helena: 'Santa Helena',
      santa_ines: 'Santa Inês',
      santa_luzia: 'Santa Luzia',
      santa_rita: 'Santa Rita',
      santa_terezinha: 'Santa Terezinha',
      santana_de_mangueira: 'Santana de Mangueira',
      santana_dos_garrotes: 'Santana dos Garrotes',
      santo_andre: 'Santo André',
      sao_bentinho: 'São Bentinho',
      sao_bento: 'São Bento',
      sao_domingos: 'São Domingos',
      sao_domingos_do_cariri: 'São Domingos do Cariri',
      sao_francisco: 'São Francisco',
      sao_joao_do_cariri: 'São João do Cariri',
      sao_joao_do_rio_do_peixe: 'São João do Rio do Peixe',
      sao_joao_do_tigre: 'São João do Tigre',
      sao_jose_da_lagoa_tapada: 'São José da Lagoa Tapada',
      sao_jose_de_caiana: 'São José de Caiana',
      sao_jose_de_espinharas: 'São José de Espinharas',
      sao_jose_de_piranhas: 'São José de Piranhas',
      sao_jose_de_princesa: 'São José de Princesa',
      sao_jose_do_bonfim: 'São José do Bonfim',
      sao_jose_do_brejo_do_cruz: 'São José do Brejo do Cruz',
      sao_jose_do_sabugi: 'São José do Sabugi',
      sao_jose_dos_cordeiros: 'São José dos Cordeiros',
      sao_jose_dos_ramos: 'São José dos Ramos',
      sao_mamede: 'São Mamede',
      sao_miguel_de_taipu: 'São Miguel de Taipu',
      sao_sebastiao_de_lagoa_de_roca: 'São Sebastião de Lagoa de Roça',
      sao_sebastiao_do_umbuzeiro: 'São Sebastião do Umbuzeiro',
      sao_vicente_do_serido: 'São Vicente do Seridó',
      sape: 'Sapé',
      serra_branca: 'Serra Branca',
      serra_da_raiz: 'Serra da Raiz',
      serra_grande: 'Serra Grande',
      serra_redonda: 'Serra Redonda',
      serraria: 'Serraria',
      sertaozinho: 'Sertãozinho',
      sobrado: 'Sobrado',
      solanea: 'Solânea',
      soledade: 'Soledade',
      sossego: 'Sossêgo',
      sousa: 'Sousa',
      sume: 'Sumé',
      tacima_ex_campo_de_santana: 'Tacima (ex-Campo de Santana)',
      taperoa: 'Taperoá',
      tavares: 'Tavares',
      teixeira: 'Teixeira',
      tenorio: 'Tenório',
      triunfo: 'Triunfo',
      uirauna: 'Uiraúna',
      umbuzeiro: 'Umbuzeiro',
      varzea: 'Várzea',
      vieiropolis: 'Vieirópolis',
      vista_serrana: 'Vista Serrana',
      zabele: 'Zabelê',
    },
    '#Estado': 'PB',
  };
  
  export default cidadesPB;
  