// cidadesRS.jsx
const cidadesRS = {
    '#empty_option': '- Selecione a Cidade -',
    '#options': {
      acegua: 'Aceguá',
      agua_santa: 'Água Santa',
      agudo: 'Agudo',
      ajuricaba: 'Ajuricaba',
      alecrim: 'Alecrim',
      alegrete: 'Alegrete',
      alegria: 'Alegria',
      almirante_tamandare_do_sul: 'Almirante Tamandaré do Sul',
      alpestre: 'Alpestre',
      alto_alegre: 'Alto Alegre',
      alto_feliz: 'Alto Feliz',
      alvorada: 'Alvorada',
      amaral_ferrador: 'Amaral Ferrador',
      ametista_do_sul: 'Ametista do Sul',
      andre_da_rocha: 'André da Rocha',
      anta_gorda: 'Anta Gorda',
      antonio_prado: 'Antônio Prado',
      arambare: 'Arambaré',
      ararica: 'Araricá',
      aratiba: 'Aratiba',
      arroio_do_meio: 'Arroio do Meio',
      arroio_do_padre: 'Arroio do Padre',
      arroio_do_sal: 'Arroio do Sal',
      arroio_do_tigre: 'Arroio do Tigre',
      arroio_dos_ratos: 'Arroio dos Ratos',
      arroio_grande: 'Arroio Grande',
      arvorezinha: 'Arvorezinha',
      augusto_pestana: 'Augusto Pestana',
      aurea: 'Áurea',
      bage: 'Bagé',
      balneario_pinhal: 'Balneário Pinhal',
      barao: 'Barão',
      barao_de_cotegipe: 'Barão de Cotegipe',
      barao_do_triunfo: 'Barão do Triunfo',
      barra_do_guarita: 'Barra do Guarita',
      barra_do_quarai: 'Barra do Quaraí',
      barra_do_ribeiro: 'Barra do Ribeiro',
      barra_do_rio_azul: 'Barra do Rio Azul',
      barra_funda: 'Barra Funda',
      barracao: 'Barracão',
      barros_cassal: 'Barros Cassal',
      benjamin_constant_do_sul: 'Benjamin Constant do Sul',
      bento_goncalves: 'Bento Gonçalves',
      boa_vista_das_missoes: 'Boa Vista das Missões',
      boa_vista_do_burica: 'Boa Vista do Buricá',
      boa_vista_do_cadeado: 'Boa Vista do Cadeado',
      boa_vista_do_incra: 'Boa Vista do Incra',
      boa_vista_do_sul: 'Boa Vista do Sul',
      bom_jesus: 'Bom Jesus',
      bom_principio: 'Bom Princípio',
      bom_progresso: 'Bom Progresso',
      bom_retiro_do_sul: 'Bom Retiro do Sul',
      boqueirao_do_leao: 'Boqueirão do Leão',
      bossoroca: 'Bossoroca',
      bozano: 'Bozano',
      braga: 'Braga',
      brochier: 'Brochier',
      butia: 'Butiá',
      cacapava_do_sul: 'Caçapava do Sul',
      cacequi: 'Cacequi',
      cachoeira_do_sul: 'Cachoeira do Sul',
      cachoeirinha: 'Cachoeirinha',
      cacique_doble: 'Cacique Doble',
      caibate: 'Caibaté',
      caicara: 'Caiçara',
      camaqua: 'Camaquã',
      camargo: 'Camargo',
      cambara_do_sul: 'Cambará do Sul',
      campestre_da_serra: 'Campestre da Serra',
      campina_das_missoes: 'Campina das Missões',
      campinas_do_sul: 'Campinas do Sul',
      campo_bom: 'Campo Bom',
      campo_novo: 'Campo Novo',
      campos_borges: 'Campos Borges',
      candelaria: 'Candelária',
      candido_godoi: 'Cândido Godói',
      candiota: 'Candiota',
      canela: 'Canela',
      cangucu: 'Canguçu',
      canoas: 'Canoas',
      canudos_do_vale: 'Canudos do Vale',
      capao_bonito_do_sul: 'Capão Bonito do Sul',
      capao_da_canoa: 'Capão da Canoa',
      capao_do_cipo: 'Capão do Cipó',
      capao_do_leao: 'Capão do Leão',
      capela_de_santana: 'Capela de Santana',
      capitao: 'Capitão',
      capivari_do_sul: 'Capivari do Sul',
      caraa: 'Caraá',
      carazinho: 'Carazinho',
      carlos_barbosa: 'Carlos Barbosa',
      carlos_gomes: 'Carlos Gomes',
      casca: 'Casca',
      caseiros: 'Caseiros',
      catuipe: 'Catuípe',
      caxias_do_sul: 'Caxias do Sul',
      centenario: 'Centenário',
      cerrito: 'Cerrito',
      cerro_branco: 'Cerro Branco',
      cerro_grande_do_sul: 'Cerro Grande do Sul',
      cerro_grande: 'Cerro Grande',
      cerro_largo: 'Cerro Largo',
      chapada: 'Chapada',
      charqueadas: 'Charqueadas',
      charrua: 'Charrua',
      chiapetta: 'Chiapetta',
      chui: 'Chuí',
      chuvisca: 'Chuvisca',
      cidreira: 'Cidreira',
      ciriaco: 'Ciríaco',
      colinas: 'Colinas',
      colorado: 'Colorado',
      condor: 'Condor',
      constantina: 'Constantina',
      coqueiro_baixo: 'Coqueiro Baixo',
      coqueiros_do_sul: 'Coqueiros do Sul',
      coronel_barros: 'Coronel Barros',
      coronel_bicaco: 'Coronel Bicaco',
      coronel_pilar: 'Coronel Pilar',
      cotipora: 'Cotiporã',
      coxilha: 'Coxilha',
      crissiumal: 'Crissiumal',
      cristal: 'Cristal',
      cristal_do_sul: 'Cristal do Sul',
      cruz_alta: 'Cruz Alta',
      cruzaltense: 'Cruzaltense',
      cruzeiro_do_sul: 'Cruzeiro do Sul',
      david_canabarro: 'David Canabarro',
      derrubadas: 'Derrubadas',
      dezesseis_de_novembro: 'Dezesseis de Novembro',
      dilermando_de_aguiar: 'Dilermando de Aguiar',
      dois_irmaos_das_missoes: 'Dois Irmãos das Missões',
      dois_irmaos: 'Dois Irmãos',
      dois_lajeados: 'Dois Lajeados',
      dom_feliciano: 'Dom Feliciano',
      dom_pedrito: 'Dom Pedrito',
      dom_pedro_de_alcantara: 'Dom Pedro de Alcântara',
      dona_francisca: 'Dona Francisca',
      doutor_mauricio_cardoso: 'Doutor Maurício Cardoso',
      doutor_ricardo: 'Doutor Ricardo',
      eldorado_do_sul: 'Eldorado do Sul',
      encantado: 'Encantado',
      encruzilhada_do_sul: 'Encruzilhada do Sul',
      engenho_velho: 'Engenho Velho',
      entre_rios_do_sul: 'Entre Rios do Sul',
      entre_ijuis: 'Entre-Ijuís',
      erebango: 'Erebango',
      erechim: 'Erechim',
      ernestina: 'Ernestina',
      erval_grande: 'Erval Grande',
      erval_seco: 'Erval Seco',
      esmeralda: 'Esmeralda',
      esperanca_do_sul: 'Esperança do Sul',
      espumoso: 'Espumoso',
      estacao: 'Estação',
      estancia_velha: 'Estância Velha',
      esteio: 'Esteio',
      estrela: 'Estrela',
      estrela_velha: 'Estrela Velha',
      eugenio_de_castro: 'Eugênio de Castro',
      fagundes_varela: 'Fagundes Varela',
      farroupilha: 'Farroupilha',
      faxinal_do_soturno: 'Faxinal do Soturno',
      faxinalzinho: 'Faxinalzinho',
      fazenda_vilanova: 'Fazenda Vilanova',
      feliz: 'Feliz',
      flores_da_cunha: 'Flores da Cunha',
      floriano_peixoto: 'Floriano Peixoto',
      fontoura_xavier: 'Fontoura Xavier',
      formigueiro: 'Formigueiro',
      forquetinha: 'Forquetinha',
      fortaleza_dos_valos: 'Fortaleza dos Valos',
      frederico_westphalen: 'Frederico Westphalen',
      garibaldi: 'Garibaldi',
      garruchos: 'Garruchos',
      gaurama: 'Gaurama',
      general_camara: 'General Câmara',
      gentil: 'Gentil',
      getulio_vargas: 'Getúlio Vargas',
      girua: 'Giruá',
      glorinha: 'Glorinha',
      gramado_dos_loureiros: 'Gramado dos Loureiros',
      gramado_xavier: 'Gramado Xavier',
      gramado: 'Gramado',
      gravatai: 'Gravataí',
      guabiju: 'Guabiju',
      guaiba: 'Guaíba',
      guapore: 'Guaporé',
      guarani_das_missoes: 'Guarani das Missões',
      harmonia: 'Harmonia',
      herval: 'Herval',
      herveiras: 'Herveiras',
      horizontina: 'Horizontina',
      hulha_negra: 'Hulha Negra',
      humaita: 'Humaitá',
      ibarama: 'Ibarama',
      ibiaca: 'Ibiaçá',
      ibiraiaras: 'Ibiraiaras',
      ibirapuita: 'Ibirapuitã',
      ibiruba: 'Ibirubá',
      igrejinha: 'Igrejinha',
      ijui: 'Ijuí',
      ilopolis: 'Ilópolis',
      imbe: 'Imbé',
      imigrante: 'Imigrante',
      independencia: 'Independência',
      inhacora: 'Inhacorá',
      ipe: 'Ipê',
      ipiranga_do_sul: 'Ipiranga do Sul',
      irai: 'Iraí',
      itaara: 'Itaara',
      itacurubi: 'Itacurubi',
      itapuca: 'Itapuca',
      itaqui: 'Itaqui',
      itati: 'Itati',
      itatiba_do_sul: 'Itatiba do Sul',
      ivora: 'Ivorá',
      ivoti: 'Ivoti',
      jaboticaba: 'Jaboticaba',
      jacuizinho: 'Jacuizinho',
      jacutinga: 'Jacutinga',
      jaguarao: 'Jaguarão',
      jaguari: 'Jaguari',
      jaquirana: 'Jaquirana',
      jari: 'Jari',
      joia: 'Jóia',
      julio_de_castilhos: 'Júlio de Castilhos',
      lagoa_bonita_do_sul: 'Lagoa Bonita do Sul',
      lagoa_dos_tres_cantos: 'Lagoa dos Três Cantos',
      lagoa_vermelha: 'Lagoa Vermelha',
      lagoao: 'Lagoão',
      lajeado: 'Lajeado',
      lajeado_do_bugre: 'Lajeado do Bugre',
      lavras_do_sul: 'Lavras do Sul',
      liberato_salzano: 'Liberato Salzano',
      lindolfo_collor: 'Lindolfo Collor',
      linha_nova: 'Linha Nova',
      macambara: 'Maçambará',
      machadinho: 'Machadinho',
      mampituba: 'Mampituba',
      manoel_viana: 'Manoel Viana',
      maquine: 'Maquiné',
      marata: 'Maratá',
      marau: 'Marau',
      marcelino_ramos: 'Marcelino Ramos',
      mariana_pimentel: 'Mariana Pimentel',
      mariano_moro: 'Mariano Moro',
      marques_de_souza: 'Marques de Souza',
      mata: 'Mata',
      mato_castelhano: 'Mato Castelhano',
      mato_leitao: 'Mato Leitão',
      mato_queimado: 'Mato Queimado',
      maximiliano_de_almeida: 'Maximiliano de Almeida',
      minas_do_leao: 'Minas do Leão',
      miraguai: 'Miraguaí',
      montauri: 'Montauri',
      monte_alegre_dos_campos: 'Monte Alegre dos Campos',
      monte_belo_do_sul: 'Monte Belo do Sul',
      montenegro: 'Montenegro',
      mormaco: 'Mormaço',
      morrinhos_do_sul: 'Morrinhos do Sul',
      morro_redondo: 'Morro Redondo',
      morro_reuter: 'Morro Reuter',
      mostardas: 'Mostardas',
      mucum: 'Muçum',
      muitos_capoes: 'Muitos Capões',
      muliterno: 'Muliterno',
      nao_me_toque: 'Não-Me-Toque',
      nicolau_vergueiro: 'Nicolau Vergueiro',
      nonoai: 'Nonoai',
      nova_alvorada: 'Nova Alvorada',
      nova_araca: 'Nova Araçá',
      nova_bassano: 'Nova Bassano',
      nova_boa_vista: 'Nova Boa Vista',
      nova_brescia: 'Nova Bréscia',
      nova_candelaria: 'Nova Candelária',
      nova_esperanca_do_sul: 'Nova Esperança do Sul',
      nova_hartz: 'Nova Hartz',
      nova_padua: 'Nova Pádua',
      nova_palma: 'Nova Palma',
      nova_petropolis: 'Nova Petrópolis',
      nova_prata: 'Nova Prata',
      nova_ramada: 'Nova Ramada',
      nova_roma_do_sul: 'Nova Roma do Sul',
      nova_santa_rita: 'Nova Santa Rita',
      novo_barreiro: 'Novo Barreiro',
      novo_cabrais: 'Novo Cabrais',
      novo_hamburgo: 'Novo Hamburgo',
      novo_machado: 'Novo Machado',
      novo_tiradentes: 'Novo Tiradentes',
      novo_xingu: 'Novo Xingu',
      osorio: 'Osório',
      paim_filho: 'Paim Filho',
      palmares_do_sul: 'Palmares do Sul',
      palmeira_das_missoes: 'Palmeira das Missões',
      palmitinho: 'Palmitinho',
      panambi: 'Panambi',
      pantano_grande: 'Pantano Grande',
      parai: 'Paraí',
      paraiso_do_sul: 'Paraíso do Sul',
      pareci_novo: 'Pareci Novo',
      parobe: 'Parobé',
      passa_sete: 'Passa-Sete',
      passo_do_sobrado: 'Passo do Sobrado',
      passo_fundo: 'Passo Fundo',
      paulo_bento: 'Paulo Bento',
      paverama: 'Paverama',
      pedras_altas: 'Pedras Altas',
      pedro_osorio: 'Pedro Osório',
      pejucara: 'Pejuçara',
      pelotas: 'Pelotas',
      picada_cafe: 'Picada Café',
      pinhal: 'Pinhal',
      pinhal_da_serra: 'Pinhal da Serra',
      pinhal_grande: 'Pinhal Grande',
      pinheirinho_do_vale: 'Pinheirinho do Vale',
      pinheiro_machado: 'Pinheiro Machado',
      pinto_bandeira: 'Pinto Bandeira',
      pirapo: 'Pirapó',
      piratini: 'Piratini',
      planalto: 'Planalto',
      poco_das_antas: 'Poço das Antas',
      pontao: 'Pontão',
      ponte_preta: 'Ponte Preta',
      portao: 'Portão',
      porto_alegre: 'Porto Alegre',
      porto_lucena: 'Porto Lucena',
      porto_maua: 'Porto Mauá',
      porto_vera_cruz: 'Porto Vera Cruz',
      porto_xavier: 'Porto Xavier',
      pouso_novo: 'Pouso Novo',
      presidente_lucena: 'Presidente Lucena',
      progresso: 'Progresso',
      protasio_alves: 'Protásio Alves',
      putinga: 'Putinga',
      quarai: 'Quaraí',
      quatro_irmaos: 'Quatro Irmãos',
      quevedos: 'Quevedos',
      quinze_de_novembro: 'Quinze de Novembro',
      redentora: 'Redentora',
      relvado: 'Relvado',
      restinga_seca: 'Restinga Sêca',
      rio_dos_indios: 'Rio dos Índios',
      rio_grande: 'Rio Grande',
      rio_pardo: 'Rio Pardo',
      riozinho: 'Riozinho',
      roca_sales: 'Roca Sales',
      rodeio_bonito: 'Rodeio Bonito',
      rolador: 'Rolador',
      rolante: 'Rolante',
      ronda_alta: 'Ronda Alta',
      rondinha: 'Rondinha',
      roque_gonzales: 'Roque Gonzales',
      rosario_do_sul: 'Rosário do Sul',
      sagrada_familia: 'Sagrada Família',
      saldanha_marinho: 'Saldanha Marinho',
      salto_do_jacui: 'Salto do Jacuí',
      salvador_das_missoes: 'Salvador das Missões',
      salvador_do_sul: 'Salvador do Sul',
      sananduva: 'Sananduva',
      santa_barbara_do_sul: 'Santa Bárbara do Sul',
      santa_cecilia_do_sul: 'Santa Cecília do Sul',
      santa_clara_do_sul: 'Santa Clara do Sul',
      santa_cruz_do_sul: 'Santa Cruz do Sul',
      santa_margarida_do_sul: 'Santa Margarida do Sul',
      santa_maria: 'Santa Maria',
      santa_maria_do_herval: 'Santa Maria do Herval',
      santa_rosa: 'Santa Rosa',
      santa_tereza: 'Santa Tereza',
      santa_vitoria_do_palmar: 'Santa Vitória do Palmar',
      santana_da_boa_vista: 'Santana da Boa Vista',
      santana_do_livramento: 'SantAna do Livramento',
      santiago: 'Santiago',
      santo_angelo: 'Santo Ângelo',
      santo_antonio_da_patrulha: 'Santo Antônio da Patrulha',
      santo_antonio_das_missoes: 'Santo Antônio das Missões',
      santo_antonio_do_palma: 'Santo Antônio do Palma',
      santo_antonio_do_planalto: 'Santo Antônio do Planalto',
      santo_augusto: 'Santo Augusto',
      santo_cristo: 'Santo Cristo',
      santo_expedito_do_sul: 'Santo Expedito do Sul',
      sao_borja: 'São Borja',
      sao_domingos_do_sul: 'São Domingos do Sul',
      sao_francisco_de_assis: 'São Francisco de Assis',
      sao_francisco_de_paula: 'São Francisco de Paula',
      sao_gabriel: 'São Gabriel',
      sao_jeronimo: 'São Jerônimo',
      sao_joao_da_urtiga: 'São João da Urtiga',
      sao_joao_do_polesine: 'São João do Polêsine',
      sao_jorge: 'São Jorge',
      sao_jose_das_missoes: 'São José das Missões',
      sao_jose_do_herval: 'São José do Herval',
      sao_jose_do_hortencio: 'São José do Hortêncio',
      sao_jose_do_inhacora: 'São José do Inhacorá',
      sao_jose_do_norte: 'São José do Norte',
      sao_jose_do_ouro: 'São José do Ouro',
      sao_jose_do_sul: 'São José do Sul',
      sao_jose_dos_ausentes: 'São José dos Ausentes',
      sao_leopoldo: 'São Leopoldo',
      sao_lourenco_do_sul: 'São Lourenço do Sul',
      sao_luiz_gonzaga: 'São Luiz Gonzaga',
      sao_marcos: 'São Marcos',
      sao_martinho: 'São Martinho',
      sao_martinho_da_serra: 'São Martinho da Serra',
      sao_miguel_das_missoes: 'São Miguel das Missões',
      sao_nicolau: 'São Nicolau',
      sao_paulo_das_missoes: 'São Paulo das Missões',
      sao_pedro_da_serra: 'São Pedro da Serra',
      sao_pedro_das_missoes: 'São Pedro das Missões',
      sao_pedro_do_butia: 'São Pedro do Butiá',
      sao_pedro_do_sul: 'São Pedro do Sul',
      sao_sebastiao_do_cai: 'São Sebastião do Caí',
      sao_sepe: 'São Sepé',
      sao_valentim: 'São Valentim',
      sao_valentim_do_sul: 'São Valentim do Sul',
      sao_valerio_do_sul: 'São Valério do Sul',
      sao_vendelino: 'São Vendelino',
      sao_vicente_do_sul: 'São Vicente do Sul',
      sapiranga: 'Sapiranga',
      sapucaia_do_sul: 'Sapucaia do Sul',
      sarandi: 'Sarandi',
      seberi: 'Seberi',
      sede_nova: 'Sede Nova',
      segredo: 'Segredo',
      selbach: 'Selbach',
      senador_salgado_filho: 'Senador Salgado Filho',
      sentinela_do_sul: 'Sentinela do Sul',
      serafina_correa: 'Serafina Corrêa',
      serio: 'Sério',
      sertao: 'Sertão',
      sertao_santana: 'Sertão Santana',
      sete_de_setembro: 'Sete de Setembro',
      severiano_de_almeida: 'Severiano de Almeida',
      silveira_martins: 'Silveira Martins',
      sinimbu: 'Sinimbu',
      sobradinho: 'Sobradinho',
      soledade: 'Soledade',
      tabai: 'Tabaí',
      tapejara: 'Tapejara',
      tapera: 'Tapera',
      tapes: 'Tapes',
      taquara: 'Taquara',
      taquari: 'Taquari',
      taquarucu_do_sul: 'Taquaruçu do Sul',
      tavares: 'Tavares',
      tenente_portela: 'Tenente Portela',
      terra_de_areia: 'Terra de Areia',
      teutonia: 'Teutônia',
      tio_hugo: 'Tio Hugo',
      tiradentes_do_sul: 'Tiradentes do Sul',
      toropi: 'Toropi',
      torres: 'Torres',
      tramandai: 'Tramandaí',
      travesseiro: 'Travesseiro',
      tres_arroios: 'Três Arroios',
      tres_cachoeiras: 'Três Cachoeiras',
      tres_coroas: 'Três Coroas',
      tres_de_maio: 'Três de Maio',
      tres_forquilhas: 'Três Forquilhas',
      tres_palmeiras: 'Três Palmeiras',
      tres_passos: 'Três Passos',
      trindade_do_sul: 'Trindade do Sul',
      triunfo: 'Triunfo',
      tucunduva: 'Tucunduva',
      tunas: 'Tunas',
      tupanci_do_sul: 'Tupanci do Sul',
      tupancireta: 'Tupanciretã',
      tupandi: 'Tupandi',
      tuparendi: 'Tuparendi',
      turucu: 'Turuçu',
      ubiretama: 'Ubiretama',
      uniao_da_serra: 'União da Serra',
      unistalda: 'Unistalda',
      uruguaiana: 'Uruguaiana',
      vacaria: 'Vacaria',
      vale_do_sol: 'Vale do Sol',
      vale_real: 'Vale Real',
      vale_verde: 'Vale Verde',
      vanini: 'Vanini',
      venancio_aires: 'Venâncio Aires',
      vera_cruz: 'Vera Cruz',
      veranopolis: 'Veranópolis',
      vespasiano_correa: 'Vespasiano Corrêa',
      viadutos: 'Viadutos',
      viamao: 'Viamão',
      vicente_dutra: 'Vicente Dutra',
      victor_graeff: 'Victor Graeff',
      vila_flores: 'Vila Flores',
      vila_langaro: 'Vila Lângaro',
      vila_maria: 'Vila Maria',
      vila_nova_do_sul: 'Vila Nova do Sul',
      vista_alegre_do_prata: 'Vista Alegre do Prata',
      vista_alegre: 'Vista Alegre',
      vista_gaucha: 'Vista Gaúcha',
      vitoria_das_missoes: 'Vitória das Missões',
      westfalia: 'Westfália',
      xangri_la: 'Xangri-lá',
    },
    '#Estado': 'RS',
  };
  
  export default cidadesRS;