// cidadesPR.jsx
const cidadesPR = {
    '#empty_option': '- Selecione a Cidade -',
    '#options': {
      abatia: 'Abatiá',
      adrianopolis: 'Adrianópolis',
      agudos_do_sul: 'Agudos do Sul',
      almirante_tamandare: 'Almirante Tamandaré',
      altamira_do_parana: 'Altamira do Paraná',
      alto_paraiso: 'Alto Paraíso',
      alto_parana: 'Alto Paraná',
      alto_piquiri: 'Alto Piquiri',
      altonia: 'Altônia',
      alvorada_do_sul: 'Alvorada do Sul',
      amapora: 'Amaporã',
      ampere: 'Ampére',
      anahy: 'Anahy',
      andira: 'Andirá',
      angulo: 'Ângulo',
      antonina: 'Antonina',
      antonio_olinto: 'Antônio Olinto',
      apucarana: 'Apucarana',
      arapongas: 'Arapongas',
      arapoti: 'Arapoti',
      arapua: 'Arapuã',
      araruna: 'Araruna',
      araucaria: 'Araucária',
      ariranha_do_ivai: 'Ariranha do Ivaí',
      assai: 'Assaí',
      assis_chateaubriand: 'Assis Chateaubriand',
      astorga: 'Astorga',
      atalaia: 'Atalaia',
      balsa_nova: 'Balsa Nova',
      bandeirantes: 'Bandeirantes',
      barbosa_ferraz: 'Barbosa Ferraz',
      barra_do_jacare: 'Barra do Jacaré',
      barracao: 'Barracão',
      bela_vista_da_caroba: 'Bela Vista da Caroba',
      bela_vista_do_paraiso: 'Bela Vista do Paraíso',
      bituruna: 'Bituruna',
      boa_esperanca: 'Boa Esperança',
      boa_esperanca_do_iguacu: 'Boa Esperança do Iguaçu',
      boa_ventura_de_sao_roque: 'Boa Ventura de São Roque',
      boa_vista_da_aparecida: 'Boa Vista da Aparecida',
      bocaiuva_do_sul: 'Bocaiúva do Sul',
      bom_jesus_do_sul: 'Bom Jesus do Sul',
      bom_sucesso: 'Bom Sucesso',
      bom_sucesso_do_sul: 'Bom Sucesso do Sul',
      borrazopolis: 'Borrazópolis',
      braganey: 'Braganey',
      brasilandia_do_sul: 'Brasilândia do Sul',
      cafeara: 'Cafeara',
      cafelandia: 'Cafelândia',
      cafezal_do_sul: 'Cafezal do Sul',
      california: 'Califórnia',
      cambara: 'Cambará',
      cambe: 'Cambé',
      cambira: 'Cambira',
      campina_da_lagoa: 'Campina da Lagoa',
      campina_do_simao: 'Campina do Simão',
      campina_grande_do_sul: 'Campina Grande do Sul',
      campo_bonito: 'Campo Bonito',
      campo_do_tenente: 'Campo do Tenente',
      campo_largo: 'Campo Largo',
      campo_magro: 'Campo Magro',
      campo_mourao: 'Campo Mourão',
      candido_de_abreu: 'Cândido de Abreu',
      candoi: 'Candói',
      cantagalo: 'Cantagalo',
      capanema: 'Capanema',
      capitao_leonidas_marques: 'Capitão Leônidas Marques',
      carambei: 'Carambeí',
      carlopolis: 'Carlópolis',
      cascavel: 'Cascavel',
      castro: 'Castro',
      catanduvas: 'Catanduvas',
      centenario_do_sul: 'Centenário do Sul',
      cerro_azul: 'Cerro Azul',
      ceu_azul: 'Céu Azul',
      chopinzinho: 'Chopinzinho',
      cianorte: 'Cianorte',
      cidade_gaucha: 'Cidade Gaúcha',
      clevelandia: 'Clevelândia',
      colombo: 'Colombo',
      colorado: 'Colorado',
      congonhinhas: 'Congonhinhas',
      conselheiro_mairinck: 'Conselheiro Mairinck',
      contenda: 'Contenda',
      corbelia: 'Corbélia',
      cornelio_procopio: 'Cornélio Procópio',
      coronel_domingos_soares: 'Coronel Domingos Soares',
      coronel_vivida: 'Coronel Vivida',
      corumbatai_do_sul: 'Corumbataí do Sul',
      cruz_machado: 'Cruz Machado',
      cruzeiro_do_iguacu: 'Cruzeiro do Iguaçu',
      cruzeiro_do_oeste: 'Cruzeiro do Oeste',
      cruzeiro_do_sul: 'Cruzeiro do Sul',
      cruzmaltina: 'Cruzmaltina',
      curitiba: 'Curitiba',
      curiuva: 'Curiúva',
      diamante_do_norte: 'Diamante do Norte',
      diamante_do_sul: 'Diamante do Sul',
      diamante_doeste: 'Diamante dOeste',
      dois_vizinhos: 'Dois Vizinhos',
      douradina: 'Douradina',
      doutor_camargo: 'Doutor Camargo',
      doutor_ulysses: 'Doutor Ulysses',
      eneas_marques: 'Enéas Marques',
      engenheiro_beltrao: 'Engenheiro Beltrão',
      entre_rios_do_oeste: 'Entre Rios do Oeste',
      esperanca_nova: 'Esperança Nova',
      espigao_alto_do_iguacu: 'Espigão Alto do Iguaçu',
      farol: 'Farol',
      faxinal: 'Faxinal',
      fazenda_rio_grande: 'Fazenda Rio Grande',
      fenix: 'Fênix',
      fernandes_pinheiro: 'Fernandes Pinheiro',
      figueira: 'Figueira',
      flor_da_serra_do_sul: 'Flor da Serra do Sul',
      florai: 'Floraí',
      floresta: 'Floresta',
      florestopolis: 'Florestópolis',
      florida: 'Flórida',
      formosa_do_oeste: 'Formosa do Oeste',
      foz_do_iguacu: 'Foz do Iguaçu',
      foz_do_jordao: 'Foz do Jordão',
      francisco_alves: 'Francisco Alves',
      francisco_beltrao: 'Francisco Beltrão',
      general_carneiro: 'General Carneiro',
      godoy_moreira: 'Godoy Moreira',
      goioere: 'Goioerê',
      goioxim: 'Goioxim',
      grandes_rios: 'Grandes Rios',
      guaira: 'Guaíra',
      guairaca: 'Guairaçá',
      guamiranga: 'Guamiranga',
      guapirama: 'Guapirama',
      guaporema: 'Guaporema',
      guaraci: 'Guaraci',
      guaraniacu: 'Guaraniaçu',
      guarapuava: 'Guarapuava',
      guaraquecaba: 'Guaraqueçaba',
      guaratuba: 'Guaratuba',
      honorio_serpa: 'Honório Serpa',
      ibaiti: 'Ibaiti',
      ibema: 'Ibema',
      ibipora: 'Ibiporã',
      icaraima: 'Icaraíma',
      iguaracu: 'Iguaraçu',
      iguatu: 'Iguatu',
      imbau: 'Imbaú',
      imbituva: 'Imbituva',
      inacio_martins: 'Inácio Martins',
      inaja: 'Inajá',
      indianopolis: 'Indianópolis',
      ipiranga: 'Ipiranga',
      ipora: 'Iporã',
      iracema_do_oeste: 'Iracema do Oeste',
      irati: 'Irati',
      iretama: 'Iretama',
      itaguaje: 'Itaguajé',
      itaipulandia: 'Itaipulândia',
      itambaraca: 'Itambaracá',
      itambe: 'Itambé',
      itapejara_doeste: 'Itapejara dOeste',
      itaperucu: 'Itaperuçu',
      itauna_do_sul: 'Itaúna do Sul',
      ivai: 'Ivaí',
      ivaipora: 'Ivaiporã',
      ivate: 'Ivaté',
      ivatuba: 'Ivatuba',
      jaboti: 'Jaboti',
      jacarezinho: 'Jacarezinho',
      jaguapita: 'Jaguapitã',
      jaguariaiva: 'Jaguariaíva',
      jandaia_do_sul: 'Jandaia do Sul',
      janiopolis: 'Janiópolis',
      japira: 'Japira',
      japura: 'Japurá',
      jardim_alegre: 'Jardim Alegre',
      jardim_olinda: 'Jardim Olinda',
      jataizinho: 'Jataizinho',
      jesuitas: 'Jesuítas',
      joaquim_tavora: 'Joaquim Távora',
      jundiai_do_sul: 'Jundiaí do Sul',
      juranda: 'Juranda',
      jussara: 'Jussara',
      kalore: 'Kaloré',
      lapa: 'Lapa',
      laranjal: 'Laranjal',
      laranjeiras_do_sul: 'Laranjeiras do Sul',
      leopolis: 'Leópolis',
      lidianopolis: 'Lidianópolis',
      lindoeste: 'Lindoeste',
      loanda: 'Loanda',
      lobato: 'Lobato',
      londrina: 'Londrina',
      luiziana: 'Luiziana',
      lunardelli: 'Lunardelli',
      lupionopolis: 'Lupionópolis',
      mallet: 'Mallet',
      mambore: 'Mamborê',
      mandaguacu: 'Mandaguaçu',
      mandaguari: 'Mandaguari',
      mandirituba: 'Mandirituba',
      manfrinopolis: 'Manfrinópolis',
      mangueirinha: 'Mangueirinha',
      manoel_ribas: 'Manoel Ribas',
      marechal_candido_rondon: 'Marechal Cândido Rondon',
      maria_helena: 'Maria Helena',
      marialva: 'Marialva',
      marilandia_do_sul: 'Marilândia do Sul',
      marilena: 'Marilena',
      mariluz: 'Mariluz',
      maringa: 'Maringá',
      mariopolis: 'Mariópolis',
      maripa: 'Maripá',
      marmeleiro: 'Marmeleiro',
      marquinho: 'Marquinho',
      marumbi: 'Marumbi',
      matelandia: 'Matelândia',
      matinhos: 'Matinhos',
      mato_rico: 'Mato Rico',
      maua_da_serra: 'Mauá da Serra',
      medianeira: 'Medianeira',
      mercedes: 'Mercedes',
      mirador: 'Mirador',
      miraselva: 'Miraselva',
      missal: 'Missal',
      moreira_sales: 'Moreira Sales',
      morretes: 'Morretes',
      munhoz_de_mello: 'Munhoz de Mello',
      nossa_senhora_das_gracas: 'Nossa Senhora das Graças',
      nova_alianca_do_ivai: 'Nova Aliança do Ivaí',
      nova_america_da_colina: 'Nova América da Colina',
      nova_aurora: 'Nova Aurora',
      nova_cantu: 'Nova Cantu',
      nova_esperanca_do_sudoeste: 'Nova Esperança do Sudoeste',
      nova_esperanca: 'Nova Esperança',
      nova_fatima: 'Nova Fátima',
      nova_laranjeiras: 'Nova Laranjeiras',
      nova_londrina: 'Nova Londrina',
      nova_olimpia: 'Nova Olímpia',
      nova_prata_do_iguacu: 'Nova Prata do Iguaçu',
      nova_santa_barbara: 'Nova Santa Bárbara',
      nova_santa_rosa: 'Nova Santa Rosa',
      nova_tebas: 'Nova Tebas',
      novo_itacolomi: 'Novo Itacolomi',
      ortigueira: 'Ortigueira',
      ourizona: 'Ourizona',
      ouro_verde_do_oeste: 'Ouro Verde do Oeste',
      paicandu: 'Paiçandu',
      palmas: 'Palmas',
      palmeira: 'Palmeira',
      palmital: 'Palmital',
      palotina: 'Palotina',
      paraiso_do_norte: 'Paraíso do Norte',
      paranacity: 'Paranacity',
      paranagua: 'Paranaguá',
      paranapoema: 'Paranapoema',
      paranavai: 'Paranavaí',
      pato_bragado: 'Pato Bragado',
      pato_branco: 'Pato Branco',
      paula_freitas: 'Paula Freitas',
      paulo_frontin: 'Paulo Frontin',
      peabiru: 'Peabiru',
      perobal: 'Perobal',
      perola: 'Pérola',
      perola_doeste: 'Pérola dOeste',
      pien: 'Piên',
      pinhais: 'Pinhais',
      pinhal_de_sao_bento: 'Pinhal de São Bento',
      pinhalao: 'Pinhalão',
      pinhao: 'Pinhão',
      pirai_do_sul: 'Piraí do Sul',
      piraquara: 'Piraquara',
      pitanga: 'Pitanga',
      pitangueiras: 'Pitangueiras',
      planaltina_do_parana: 'Planaltina do Paraná',
      planalto: 'Planalto',
      ponta_grossa: 'Ponta Grossa',
      pontal_do_parana: 'Pontal do Paraná',
      porecatu: 'Porecatu',
      porto_amazonas: 'Porto Amazonas',
      porto_barreiro: 'Porto Barreiro',
      porto_rico: 'Porto Rico',
      porto_vitoria: 'Porto Vitória',
      prado_ferreira: 'Prado Ferreira',
      pranchita: 'Pranchita',
      presidente_castelo_branco: 'Presidente Castelo Branco',
      primeiro_de_maio: 'Primeiro de Maio',
      prudentopolis: 'Prudentópolis',
      quarto_centenario: 'Quarto Centenário',
      quatigua: 'Quatiguá',
      quatro_barras: 'Quatro Barras',
      quatro_pontes: 'Quatro Pontes',
      quedas_do_iguacu: 'Quedas do Iguaçu',
      querencia_do_norte: 'Querência do Norte',
      quinta_do_sol: 'Quinta do Sol',
      quitandinha: 'Quitandinha',
      ramilandia: 'Ramilândia',
      rancho_alegre: 'Rancho Alegre',
      rancho_alegre_doeste: 'Rancho Alegre dOeste',
      realeza: 'Realeza',
      reboucas: 'Rebouças',
      renascenca: 'Renascença',
      reserva: 'Reserva',
      reserva_do_iguacu: 'Reserva do Iguaçu',
      ribeirao_claro: 'Ribeirão Claro',
      ribeirao_do_pinhal: 'Ribeirão do Pinhal',
      rio_azul: 'Rio Azul',
      rio_bom: 'Rio Bom',
      rio_bonito_do_iguacu: 'Rio Bonito do Iguaçu',
      rio_branco_do_ivai: 'Rio Branco do Ivaí',
      rio_branco_do_sul: 'Rio Branco do Sul',
      rio_negro: 'Rio Negro',
      rolandia: 'Rolândia',
      roncador: 'Roncador',
      rondon: 'Rondon',
      rosario_do_ivai: 'Rosário do Ivaí',
      sabaudia: 'Sabáudia',
      salgado_filho: 'Salgado Filho',
      salto_do_itarare: 'Salto do Itararé',
      salto_do_lontra: 'Salto do Lontra',
      santa_amelia: 'Santa Amélia',
      santa_cecilia_do_pavao: 'Santa Cecília do Pavão',
      santa_cruz_de_monte_castelo: 'Santa Cruz de Monte Castelo',
      santa_fe: 'Santa Fé',
      santa_helena: 'Santa Helena',
      santa_ines: 'Santa Inês',
      santa_isabel_do_ivai: 'Santa Isabel do Ivaí',
      santa_izabel_do_oeste: 'Santa Izabel do Oeste',
      santa_lucia: 'Santa Lúcia',
      santa_maria_do_oeste: 'Santa Maria do Oeste',
      santa_mariana: 'Santa Mariana',
      santa_monica: 'Santa Mônica',
      santa_tereza_do_oeste: 'Santa Tereza do Oeste',
      santa_terezinha_de_itaipu: 'Santa Terezinha de Itaipu',
      santana_do_itarare: 'Santana do Itararé',
      santo_antonio_da_platina: 'Santo Antônio da Platina',
      santo_antonio_do_caiua: 'Santo Antônio do Caiuá',
      santo_antonio_do_paraiso: 'Santo Antônio do Paraíso',
      santo_antonio_do_sudoeste: 'Santo Antônio do Sudoeste',
      santo_inacio: 'Santo Inácio',
      sao_carlos_do_ivai: 'São Carlos do Ivaí',
      sao_jeronimo_da_serra: 'São Jerônimo da Serra',
      sao_joao: 'São João',
      sao_joao_do_caiua: 'São João do Caiuá',
      sao_joao_do_ivai: 'São João do Ivaí',
      sao_joao_do_triunfo: 'São João do Triunfo',
      sao_jorge_do_ivai: 'São Jorge do Ivaí',
      sao_jorge_do_patrocinio: 'São Jorge do Patrocínio',
      sao_jorge_doeste: 'São Jorge dOeste',
      sao_jose_da_boa_vista: 'São José da Boa Vista',
      sao_jose_das_palmeiras: 'São José das Palmeiras',
      sao_jose_dos_pinhais: 'São José dos Pinhais',
      sao_manoel_do_parana: 'São Manoel do Paraná',
      sao_mateus_do_sul: 'São Mateus do Sul',
      sao_miguel_do_iguacu: 'São Miguel do Iguaçu',
      sao_pedro_do_iguacu: 'São Pedro do Iguaçu',
      sao_pedro_do_ivai: 'São Pedro do Ivaí',
      sao_pedro_do_parana: 'São Pedro do Paraná',
      sao_sebastiao_da_amoreira: 'São Sebastião da Amoreira',
      sao_tome: 'São Tomé',
      sapopema: 'Sapopema',
      sarandi: 'Sarandi',
      saudade_do_iguacu: 'Saudade do Iguaçu',
      senges: 'Sengés',
      serranopolis_do_iguacu: 'Serranópolis do Iguaçu',
      sertaneja: 'Sertaneja',
      sertanopolis: 'Sertanópolis',
      siqueira_campos: 'Siqueira Campos',
      sulina: 'Sulina',
      tamarana: 'Tamarana',
      tamboara: 'Tamboara',
      tapejara: 'Tapejara',
      tapira: 'Tapira',
      teixeira_soares: 'Teixeira Soares',
      telemaco_borba: 'Telêmaco Borba',
      terra_boa: 'Terra Boa',
      terra_rica: 'Terra Rica',
      terra_roxa: 'Terra Roxa',
      tibagi: 'Tibagi',
      tijucas_do_sul: 'Tijucas do Sul',
      toledo: 'Toledo',
      tomazina: 'Tomazina',
      tres_barras_do_parana: 'Três Barras do Paraná',
      tunas_do_parana: 'Tunas do Paraná',
      tuneiras_do_oeste: 'Tuneiras do Oeste',
      tupassi: 'Tupãssi',
      turvo: 'Turvo',
      ubirata: 'Ubiratã',
      umuarama: 'Umuarama',
      uniao_da_vitoria: 'União da Vitória',
      uniflor: 'Uniflor',
      urai: 'Uraí',
      ventania: 'Ventania',
      vera_cruz_do_oeste: 'Vera Cruz do Oeste',
      vere: 'Verê',
      virmond: 'Virmond',
      vitorino: 'Vitorino',
      wenceslau_braz: 'Wenceslau Braz',
      xambre: 'Xambrê',
    },
    '#Estado': 'PR',
  };
  
  export default cidadesPR;