// cidadesRO.js
const cidadesRO = {
    '#empty_option': '- Selecione a Cidade -',
    '#options': {
      alta_floresta_doeste: 'Alta Floresta dOeste',
      alto_alegre_dos_parecis: 'Alto Alegre dos Parecis',
      alto_paraiso: 'Alto Paraíso',
      alvorada_doeste: 'Alvorada dOeste',
      ariquemes: 'Ariquemes',
      buritis: 'Buritis',
      cabixi: 'Cabixi',
      cacaulandia: 'Cacaulândia',
      cacoal: 'Cacoal',
      campo_novo_de_rondonia: 'Campo Novo de Rondônia',
      candeias_do_jamari: 'Candeias do Jamari',
      castanheiras: 'Castanheiras',
      cerejeiras: 'Cerejeiras',
      chupinguaia: 'Chupinguaia',
      colorado_do_oeste: 'Colorado do Oeste',
      corumbiara: 'Corumbiara',
      costa_marques: 'Costa Marques',
      cujubim: 'Cujubim',
      espigao_doeste: 'Espigão dOeste',
      governador_jorge_teixeira: 'Governador Jorge Teixeira',
      guajara_mirim: 'Guajará-Mirim',
      itapua_do_oeste: 'Itapuã do Oeste',
      jaru: 'Jaru',
      ji_parana: 'Ji-Paraná',
      machadinho_doeste: 'Machadinho dOeste',
      ministro_andreazza: 'Ministro Andreazza',
      mirante_da_serra: 'Mirante da Serra',
      monte_negro: 'Monte Negro',
      nova_brasilandia_doeste: 'Nova Brasilândia dOeste',
      nova_mamore: 'Nova Mamoré',
      nova_uniao: 'Nova União',
      novo_horizonte_do_oeste: 'Novo Horizonte do Oeste',
      ouro_preto_do_oeste: 'Ouro Preto do Oeste',
      parecis: 'Parecis',
      pimenta_bueno: 'Pimenta Bueno',
      pimenteiras_do_oeste: 'Pimenteiras do Oeste',
      porto_velho: 'Porto Velho',
      presidente_medici: 'Presidente Médici',
      primavera_de_rondonia: 'Primavera de Rondônia',
      rio_crespo: 'Rio Crespo',
      rolim_de_moura: 'Rolim de Moura',
      santa_luzia_doeste: 'Santa Luzia dOeste',
      sao_felipe_doeste: 'São Felipe dOeste',
      sao_francisco_do_guapore: 'São Francisco do Guaporé',
      sao_miguel_do_guapore: 'São Miguel do Guaporé',
      seringueiras: 'Seringueiras',
      teixeiropolis: 'Teixeirópolis',
      theobroma: 'Theobroma',
      urupa: 'Urupá',
      vale_do_anari: 'Vale do Anari',
      vale_do_paraiso: 'Vale do Paraíso',
      vilhena: 'Vilhena',
    },
    '#Estado': 'RO',
  };
  
  export default cidadesRO;