// cidadesMT.js
const cidadesMT = {
    '#empty_option': '- Selecione a Cidade -',
    '#options': {
      acorizal: 'Acorizal',
      agua_boa: 'Água Boa',
      alta_floresta: 'Alta Floresta',
      alto_araguaia: 'Alto Araguaia',
      alto_boa_vista: 'Alto Boa Vista',
      alto_garcas: 'Alto Garças',
      alto_paraguai: 'Alto Paraguai',
      alto_taquari: 'Alto Taquari',
      apiacas: 'Apiacás',
      araguaiana: 'Araguaiana',
      araguainha: 'Araguainha',
      araputanga: 'Araputanga',
      arenapolis: 'Arenápolis',
      aripuana: 'Aripuanã',
      barao_de_melgaco: 'Barão de Melgaço',
      barra_do_bugres: 'Barra do Bugres',
      barra_do_garcas: 'Barra do Garças',
      boa_esperanca_do_norte: 'Boa Esperança do Norte',
      bom_jesus_do_araguaia: 'Bom Jesus do Araguaia',
      brasnorte: 'Brasnorte',
      caceres: 'Cáceres',
      campinapolis: 'Campinápolis',
      campo_novo_do_parecis: 'Campo Novo do Parecis',
      campo_verde: 'Campo Verde',
      campos_de_julio: 'Campos de Júlio',
      canabrava_do_norte: 'Canabrava do Norte',
      canarana: 'Canarana',
      carlinda: 'Carlinda',
      castanheira: 'Castanheira',
      chapada_dos_guimaraes: 'Chapada dos Guimarães',
      claudia: 'Cláudia',
      cocalinho: 'Cocalinho',
      colider: 'Colíder',
      colniza: 'Colniza',
      comodoro: 'Comodoro',
      confresa: 'Confresa',
      conquista_doeste: 'Conquista dOeste',
      cotriguacu: 'Cotriguaçu',
      cuiaba: 'Cuiabá',
      curvelandia: 'Curvelândia',
      denise: 'Denise',
      diamantino: 'Diamantino',
      dom_aquino: 'Dom Aquino',
      feliz_natal: 'Feliz Natal',
      figueiropolis_doeste: 'Figueirópolis dOeste',
      gaucha_do_norte: 'Gaúcha do Norte',
      general_carneiro: 'General Carneiro',
      gloria_doeste: 'Glória dOeste',
      guaranta_do_norte: 'Guarantã do Norte',
      guiratinga: 'Guiratinga',
      indiavai: 'Indiavaí',
      ipiranga_do_norte: 'Ipiranga do Norte',
      itanhanga: 'Itanhangá',
      itauba: 'Itaúba',
      itiquira: 'Itiquira',
      jaciara: 'Jaciara',
      jangada: 'Jangada',
      jauru: 'Jauru',
      juara: 'Juara',
      juina: 'Juína',
      juruena: 'Juruena',
      juscimeira: 'Juscimeira',
      lambari_doeste: 'Lambari dOeste',
      lucas_do_rio_verde: 'Lucas do Rio Verde',
      luciara: 'Luciara',
      marcelandia: 'Marcelândia',
      matupa: 'Matupá',
      mirassol_doeste: 'Mirassol dOeste',
      nobres: 'Nobres',
      nortelandia: 'Nortelândia',
      nossa_senhora_do_livramento: 'Nossa Senhora do Livramento',
      nova_bandeirantes: 'Nova Bandeirantes',
      nova_brasilandia: 'Nova Brasilândia',
      nova_canaa_do_norte: 'Nova Canaã do Norte',
      nova_guarita: 'Nova Guarita',
      nova_lacerda: 'Nova Lacerda',
      nova_marilandia: 'Nova Marilândia',
      nova_maringa: 'Nova Maringá',
      nova_monte_verde: 'Nova Monte Verde',
      nova_mutum: 'Nova Mutum',
      nova_nazare: 'Nova Nazaré',
      nova_olimpia: 'Nova Olímpia',
      nova_santa_helena: 'Nova Santa Helena',
      nova_ubirata: 'Nova Ubiratã',
      nova_xavantina: 'Nova Xavantina',
      novo_horizonte_do_norte: 'Novo Horizonte do Norte',
      novo_mundo: 'Novo Mundo',
      novo_santo_antonio: 'Novo Santo Antônio',
      novo_sao_joaquim: 'Novo São Joaquim',
      paranaita: 'Paranaíta',
      paranatinga: 'Paranatinga',
      pedra_preta: 'Pedra Preta',
      peixoto_de_azevedo: 'Peixoto de Azevedo',
      planalto_da_serra: 'Planalto da Serra',
      pocone: 'Poconé',
      pontal_do_araguaia: 'Pontal do Araguaia',
      ponte_branca: 'Ponte Branca',
      pontes_e_lacerda: 'Pontes e Lacerda',
      porto_alegre_do_norte: 'Porto Alegre do Norte',
      porto_dos_gauchos: 'Porto dos Gaúchos',
      porto_esperidiao: 'Porto Esperidião',
      porto_estrela: 'Porto Estrela',
      poxoreu: 'Poxoréu',
      primavera_do_leste: 'Primavera do Leste',
      querencia: 'Querência',
      reserva_do_cabacal: 'Reserva do Cabaçal',
      ribeirao_cascalheira: 'Ribeirão Cascalheira',
      ribeiraozinho: 'Ribeirãozinho',
      rio_branco: 'Rio Branco',
      rondolandia: 'Rondolândia',
      rondonopolis: 'Rondonópolis',
      rosario_oeste: 'Rosário Oeste',
      salto_do_ceu: 'Salto do Céu',
      santa_carmem: 'Santa Carmem',
      santa_cruz_do_xingu: 'Santa Cruz do Xingu',
      santa_rita_do_trivelato: 'Santa Rita do Trivelato',
      santa_terezinha: 'Santa Terezinha',
      santo_afonso: 'Santo Afonso',
      santo_antonio_do_leste: 'Santo Antônio do Leste',
      santo_antonio_de_leverger: 'Santo Antônio de Leverger',
      sao_felix_do_araguaia: 'São Félix do Araguaia',
      sao_jose_do_povo: 'São José do Povo',
      sao_jose_do_rio_claro: 'São José do Rio Claro',
      sao_jose_do_xingu: 'São José do Xingu',
      sao_jose_dos_quatro_marcos: 'São José dos Quatro Marcos',
      sao_pedro_da_cipa: 'São Pedro da Cipa',
      sapezal: 'Sapezal',
      serra_nova_dourada: 'Serra Nova Dourada',
      sinop: 'Sinop',
      sorriso: 'Sorriso',
      tabapora: 'Tabaporã',
      tangara_da_serra: 'Tangará da Serra',
      tapurah: 'Tapurah',
      terra_nova_do_norte: 'Terra Nova do Norte',
      tesouro: 'Tesouro',
      torixoreu: 'Torixoréu',
      uniao_do_sul: 'União do Sul',
      vale_de_sao_domingos: 'Vale de São Domingos',
      varzea_grande: 'Várzea Grande',
      vera: 'Vera',
      vila_bela_da_santissima_trindade: 'Vila Bela da Santíssima Trindade',
      vila_rica: 'Vila Rica',
    },
    '#Estado': 'MT',
  };
  
  export default cidadesMT;