// cidadesBA.jsx
const cidadesBA = {
    '#empty_option': '- Selecione a Cidade -',
    '#options': {
      abaira: 'Abaíra',
      abare: 'Abaré',
      acajutiba: 'Acajutiba',
      adustina: 'Adustina',
      agua_fria: 'Água Fria',
      aiquara: 'Aiquara',
      alagoinhas: 'Alagoinhas',
      alcobaca: 'Alcobaça',
      almadina: 'Almadina',
      amargosa: 'Amargosa',
      amelia_rodrigues: 'Amélia Rodrigues',
      america_dourada: 'América Dourada',
      anage: 'Anagé',
      andarai: 'Andaraí',
      andorinha: 'Andorinha',
      angical: 'Angical',
      anguera: 'Anguera',
      antas: 'Antas',
      antonio_cardoso: 'Antônio Cardoso',
      antonio_goncalves: 'Antônio Gonçalves',
      apora: 'Aporá',
      apuarema: 'Apuarema',
      aracas: 'Araçás',
      aracatu: 'Aracatu',
      araci: 'Araci',
      aramari: 'Aramari',
      arataca: 'Arataca',
      aratuipe: 'Aratuípe',
      aurelino_leal: 'Aurelino Leal',
      baianopolis: 'Baianópolis',
      baixa_grande: 'Baixa Grande',
      banzae: 'Banzaê',
      barra: 'Barra',
      barra_da_estiva: 'Barra da Estiva',
      barra_do_choca: 'Barra do Choça',
      barra_do_mendes: 'Barra do Mendes',
      barra_do_rocha: 'Barra do Rocha',
      barreiras: 'Barreiras',
      barro_alto: 'Barro Alto',
      barro_preto: 'Barro Preto',
      barrocas: 'Barrocas',
      belmonte: 'Belmonte',
      belo_campo: 'Belo Campo',
      biritinga: 'Biritinga',
      boa_nova: 'Boa Nova',
      boa_vista_do_tupim: 'Boa Vista do Tupim',
      bom_jesus_da_lapa: 'Bom Jesus da Lapa',
      bom_jesus_da_serra: 'Bom Jesus da Serra',
      boninal: 'Boninal',
      bonito: 'Bonito',
      boquira: 'Boquira',
      botupora: 'Botuporã',
      brejoes: 'Brejões',
      brejolandia: 'Brejolândia',
      brotas_de_macaubas: 'Brotas de Macaúbas',
      brumado: 'Brumado',
      buerarema: 'Buerarema',
      buritirama: 'Buritirama',
      caatiba: 'Caatiba',
      cabaceiras_do_paraguacu: 'Cabaceiras do Paraguaçu',
      cachoeira: 'Cachoeira',
      cacule: 'Caculé',
      caem: 'Caém',
      caetanos: 'Caetanos',
      caetite: 'Caetité',
      cafarnaum: 'Cafarnaum',
      cairu: 'Cairu',
      caldeirao_grande: 'Caldeirão Grande',
      camacan: 'Camacan',
      camacari: 'Camaçari',
      camamu: 'Camamu',
      campo_alegre_de_lourdes: 'Campo Alegre de Lourdes',
      campo_formoso: 'Campo Formoso',
      canapolis: 'Canápolis',
      canarana: 'Canarana',
      canavieiras: 'Canavieiras',
      candeal: 'Candeal',
      candeias: 'Candeias',
      candiba: 'Candiba',
      candido_sales: 'Cândido Sales',
      cansancao: 'Cansanção',
      canudos: 'Canudos',
      capela_do_alto_alegre: 'Capela do Alto Alegre',
      capim_grosso: 'Capim Grosso',
      caraibas: 'Caraíbas',
      caravelas: 'Caravelas',
      cardeal_da_silva: 'Cardeal da Silva',
      carinhanha: 'Carinhanha',
      casa_nova: 'Casa Nova',
      castro_alves: 'Castro Alves',
      catolandia: 'Catolândia',
      catu: 'Catu',
      caturama: 'Caturama',
      central: 'Central',
      chorrocho: 'Chorrochó',
      cicero_dantas: 'Cícero Dantas',
      cipo: 'Cipó',
      coaraci: 'Coaraci',
      cocos: 'Cocos',
      conceicao_da_feira: 'Conceição da Feira',
      conceicao_do_almeida: 'Conceição do Almeida',
      conceicao_do_coite: 'Conceição do Coité',
      conceicao_do_jacuipe: 'Conceição do Jacuípe',
      conde: 'Conde',
      condeuba: 'Condeúba',
      contendas_do_sincora: 'Contendas do Sincorá',
      coracao_de_maria: 'Coração de Maria',
      cordeiros: 'Cordeiros',
      coribe: 'Coribe',
      coronel_joao_sa: 'Coronel João Sá',
      correntina: 'Correntina',
      cotegipe: 'Cotegipe',
      cravolandia: 'Cravolândia',
      crisopolis: 'Crisópolis',
      cristopolis: 'Cristópolis',
      cruz_das_almas: 'Cruz das Almas',
      curaca: 'Curaçá',
      dario_meira: 'Dário Meira',
      dias_davila: 'Dias dÁvila',
      dom_basilio: 'Dom Basílio',
      dom_macedo_costa: 'Dom Macedo Costa',
      elisio_medrado: 'Elísio Medrado',
      encruzilhada: 'Encruzilhada',
      entre_rios: 'Entre Rios',
      erico_cardoso: 'Érico Cardoso',
      esplanada: 'Esplanada',
      euclides_da_cunha: 'Euclides da Cunha',
      eunapolis: 'Eunápolis',
      fatima: 'Fátima',
      feira_da_mata: 'Feira da Mata',
      feira_de_santana: 'Feira de Santana',
      filadelfia: 'Filadélfia',
      firmino_alves: 'Firmino Alves',
      floresta_azul: 'Floresta Azul',
      formosa_do_rio_preto: 'Formosa do Rio Preto',
      gandu: 'Gandu',
      gaviao: 'Gavião',
      gentio_do_ouro: 'Gentio do Ouro',
      gloria: 'Glória',
      gongogi: 'Gongogi',
      governador_mangabeira: 'Governador Mangabeira',
      guajeru: 'Guajeru',
      guanambi: 'Guanambi',
      guaratinga: 'Guaratinga',
      heliopolis: 'Heliópolis',
      iacu: 'Iaçu',
      ibiassuce: 'Ibiassucê',
      ibicarai: 'Ibicaraí',
      ibicoara: 'Ibicoara',
      ibicui: 'Ibicuí',
      ibipeba: 'Ibipeba',
      ibipitanga: 'Ibipitanga',
      ibiquera: 'Ibiquera',
      ibirapitanga: 'Ibirapitanga',
      ibirapua: 'Ibirapuã',
      ibirataia: 'Ibirataia',
      ibitiara: 'Ibitiara',
      ibitita: 'Ibititá',
      ibotirama: 'Ibotirama',
      ichu: 'Ichu',
      igapora: 'Igaporã',
      igrapiuna: 'Igrapiúna',
      iguai: 'Iguaí',
      ilheus: 'Ilhéus',
      inhambupe: 'Inhambupe',
      ipecaeta: 'Ipecaetá',
      ipiau: 'Ipiaú',
      ipira: 'Ipirá',
      ipupiara: 'Ipupiara',
      irajuba: 'Irajuba',
      iramaia: 'Iramaia',
      iraquara: 'Iraquara',
      irara: 'Irará',
      irece: 'Irecê',
      itabela: 'Itabela',
      itaberaba: 'Itaberaba',
      itabuna: 'Itabuna',
      itacare: 'Itacaré',
      itaete: 'Itaetê',
      itagi: 'Itagi',
      itagiba: 'Itagibá',
      itagimirim: 'Itagimirim',
      itaguacu_da_bahia: 'Itaguaçu da Bahia',
      itaju_do_colonia: 'Itaju do Colônia',
      itajuipe: 'Itajuípe',
      itamaraju: 'Itamaraju',
      itamari: 'Itamari',
      itambe: 'Itambé',
      itanagra: 'Itanagra',
      itanhem: 'Itanhém',
      itaparica: 'Itaparica',
      itape: 'Itapé',
      itapebi: 'Itapebi',
      itapetinga: 'Itapetinga',
      itapicuru: 'Itapicuru',
      itapitanga: 'Itapitanga',
      itaquara: 'Itaquara',
      itarantim: 'Itarantim',
      itatim: 'Itatim',
      itirucu: 'Itiruçu',
      itiuba: 'Itiúba',
      itororo: 'Itororó',
      ituacu: 'Ituaçu',
      itubera: 'Ituberá',
      iuiu: 'Iuiú',
      jaborandi: 'Jaborandi',
      jacaraci: 'Jacaraci',
      jacobina: 'Jacobina',
      jaguaquara: 'Jaguaquara',
      jaguarari: 'Jaguarari',
      jaguaripe: 'Jaguaripe',
      jandaira: 'Jandaíra',
      jequie: 'Jequié',
      jeremoabo: 'Jeremoabo',
      jiquirica: 'Jiquiriçá',
      jitauna: 'Jitaúna',
      joao_dourado: 'João Dourado',
      juazeiro: 'Juazeiro',
      jucurucu: 'Jucuruçu',
      jussara: 'Jussara',
      jussari: 'Jussari',
      jussiape: 'Jussiape',
      lafaiete_coutinho: 'Lafaiete Coutinho',
      lagoa_real: 'Lagoa Real',
      laje: 'Laje',
      lajedao: 'Lajedão',
      lajedinho: 'Lajedinho',
      lajedo_do_tabocal: 'Lajedo do Tabocal',
      lamarao: 'Lamarão',
      lapao: 'Lapão',
      lauro_de_freitas: 'Lauro de Freitas',
      lencois: 'Lençóis',
      licinio_de_almeida: 'Licínio de Almeida',
      livramento_de_nossa_senhora: 'Livramento de Nossa Senhora',
      luis_eduardo_magalhaes: 'Luís Eduardo Magalhães',
      macajuba: 'Macajuba',
      macarani: 'Macarani',
      macaubas: 'Macaúbas',
      macurure: 'Macururé',
      madre_de_deus: 'Madre de Deus',
      maetinga: 'Maetinga',
      maiquinique: 'Maiquinique',
      mairi: 'Mairi',
      malhada_de_pedras: 'Malhada de Pedras',
      malhada: 'Malhada',
      manoel_vitorino: 'Manoel Vitorino',
      mansidao: 'Mansidão',
      maracas: 'Maracás',
      maragogipe: 'Maragogipe',
      marau: 'Maraú',
      marcionilio_souza: 'Marcionílio Souza',
      mascote: 'Mascote',
      mata_de_sao_joao: 'Mata de São João',
      matina: 'Matina',
      medeiros_neto: 'Medeiros Neto',
      miguel_calmon: 'Miguel Calmon',
      milagres: 'Milagres',
      mirangaba: 'Mirangaba',
      mirante: 'Mirante',
      monte_santo: 'Monte Santo',
      morpara: 'Morpará',
      morro_do_chapeu: 'Morro do Chapéu',
      mortugaba: 'Mortugaba',
      mucuge: 'Mucugê',
      mucuri: 'Mucuri',
      mulungu_do_morro: 'Mulungu do Morro',
      mundo_novo: 'Mundo Novo',
      muniz_ferreira: 'Muniz Ferreira',
      muquem_do_sao_francisco: 'Muquém do São Francisco',
      muritiba: 'Muritiba',
      mutuipe: 'Mutuípe',
      nazare: 'Nazaré',
      nilo_pecanha: 'Nilo Peçanha',
      nordestina: 'Nordestina',
      nova_canaa: 'Nova Canaã',
      nova_fatima: 'Nova Fátima',
      nova_ibia: 'Nova Ibiá',
      nova_itarana: 'Nova Itarana',
      nova_redencao: 'Nova Redenção',
      nova_soure: 'Nova Soure',
      nova_vicosa: 'Nova Viçosa',
      novo_horizonte: 'Novo Horizonte',
      novo_triunfo: 'Novo Triunfo',
      olindina: 'Olindina',
      oliveira_dos_brejinhos: 'Oliveira dos Brejinhos',
      ouricangas: 'Ouriçangas',
      ourolandia: 'Ourolândia',
      palmas_de_monte_alto: 'Palmas de Monte Alto',
      palmeiras: 'Palmeiras',
      paramirim: 'Paramirim',
      paratinga: 'Paratinga',
      paripiranga: 'Paripiranga',
      pau_brasil: 'Pau Brasil',
      paulo_afonso: 'Paulo Afonso',
      pe_de_serra: 'Pé de Serra',
      pedrao: 'Pedrão',
      pedro_alexandre: 'Pedro Alexandre',
      piata: 'Piatã',
      pilao_arcado: 'Pilão Arcado',
      pindai: 'Pindaí',
      pindobacu: 'Pindobaçu',
      pintadas: 'Pintadas',
      pirai_do_norte: 'Piraí do Norte',
      piripa: 'Piripá',
      piritiba: 'Piritiba',
      planaltino: 'Planaltino',
      planalto: 'Planalto',
      pocoes: 'Poções',
      pojuca: 'Pojuca',
      ponto_novo: 'Ponto Novo',
      porto_seguro: 'Porto Seguro',
      potiragua: 'Potiraguá',
      prado: 'Prado',
      presidente_dutra: 'Presidente Dutra',
      presidente_janio_quadros: 'Presidente Jânio Quadros',
      presidente_tancredo_neves: 'Presidente Tancredo Neves',
      queimadas: 'Queimadas',
      quijingue: 'Quijingue',
      quixabeira: 'Quixabeira',
      rafael_jambeiro: 'Rafael Jambeiro',
      remanso: 'Remanso',
      retirolandia: 'Retirolândia',
      riachao_das_neves: 'Riachão das Neves',
      riachao_do_jacuipe: 'Riachão do Jacuípe',
      riacho_de_santana: 'Riacho de Santana',
      ribeira_do_amparo: 'Ribeira do Amparo',
      ribeira_do_pombal: 'Ribeira do Pombal',
      ribeirao_do_largo: 'Ribeirão do Largo',
      rio_de_contas: 'Rio de Contas',
      rio_do_antonio: 'Rio do Antônio',
      rio_do_pires: 'Rio do Pires',
      rio_real: 'Rio Real',
      rodelas: 'Rodelas',
      ruy_barbosa: 'Ruy Barbosa',
      salinas_da_margarida: 'Salinas da Margarida',
      salvador: 'Salvador',
      santa_barbara: 'Santa Bárbara',
      santa_brigida: 'Santa Brígida',
      santa_cruz_cabralia: 'Santa Cruz Cabrália',
      santa_cruz_da_vitoria: 'Santa Cruz da Vitória',
      santa_ines: 'Santa Inês',
      santa_luzia: 'Santa Luzia',
      santa_maria_da_vitoria: 'Santa Maria da Vitória',
      santa_rita_de_cassia: 'Santa Rita de Cássia',
      santa_teresinha: 'Santa Teresinha',
      santaluz: 'Santaluz',
      santana: 'Santana',
      santanopolis: 'Santanópolis',
      santo_amaro: 'Santo Amaro',
      santo_antonio_de_jesus: 'Santo Antônio de Jesus',
      santo_estevao: 'Santo Estêvão',
      sao_desiderio: 'São Desidério',
      sao_domingos: 'São Domingos',
      sao_felipe: 'São Felipe',
      sao_felix: 'São Félix',
      sao_felix_do_coribe: 'São Félix do Coribe',
      sao_francisco_do_conde: 'São Francisco do Conde',
      sao_gabriel: 'São Gabriel',
      sao_goncalo_dos_campos: 'São Gonçalo dos Campos',
      sao_jose_da_vitoria: 'São José da Vitória',
      sao_jose_do_jacuipe: 'São José do Jacuípe',
      sao_miguel_das_matas: 'São Miguel das Matas',
      sao_sebastiao_do_passe: 'São Sebastião do Passé',
      sapeacu: 'Sapeaçu',
      satiro_dias: 'Sátiro Dias',
      saubara: 'Saubara',
      saude: 'Saúde',
      seabra: 'Seabra',
      sebastiao_laranjeiras: 'Sebastião Laranjeiras',
      senhor_do_bonfim: 'Senhor do Bonfim',
      sento_se: 'Sento Sé',
      serra_do_ramalho: 'Serra do Ramalho',
      serra_dourada: 'Serra Dourada',
      serra_preta: 'Serra Preta',
      serrinha: 'Serrinha',
      serrolandia: 'Serrolândia',
      simoes_filho: 'Simões Filho',
      sitio_do_mato: 'Sítio do Mato',
      sitio_do_quinto: 'Sítio do Quinto',
      sobradinho: 'Sobradinho',
      souto_soares: 'Souto Soares',
      tabocas_do_brejo_velho: 'Tabocas do Brejo Velho',
      tanhacu: 'Tanhaçu',
      tanque_novo: 'Tanque Novo',
      tanquinho: 'Tanquinho',
      taperoa: 'Taperoá',
      tapiramuta: 'Tapiramutá',
      teixeira_de_freitas: 'Teixeira de Freitas',
      teodoro_sampaio: 'Teodoro Sampaio',
      teofilandia: 'Teofilândia',
      teolandia: 'Teolândia',
      terra_nova: 'Terra Nova',
      tremedal: 'Tremedal',
      tucano: 'Tucano',
      uaua: 'Uauá',
      ubaira: 'Ubaíra',
      ubaitaba: 'Ubaitaba',
      ubata: 'Ubatã',
      uibai: 'Uibaí',
      umburanas: 'Umburanas',
      una: 'Una',
      urandi: 'Urandi',
      urucuca: 'Uruçuca',
      utinga: 'Utinga',
      valenca: 'Valença',
      valente: 'Valente',
      varzea_da_roca: 'Várzea da Roça',
      varzea_do_poco: 'Várzea do Poço',
      varzea_nova: 'Várzea Nova',
      varzedo: 'Varzedo',
      vera_cruz: 'Vera Cruz',
      vereda: 'Vereda',
      vitoria_da_conquista: 'Vitória da Conquista',
      wagner: 'Wagner',
      wanderley: 'Wanderley',
      wenceslau_guimaraes: 'Wenceslau Guimarães',
      xique_xique: 'Xique-Xique',
    },
    '#Estado': 'BA',
  };
  
  export default cidadesBA;