// cidadesMS.js
const cidadesMS = {
    '#empty_option': '- Selecione a Cidade -',
    '#options': {
      agua_clara: 'Água Clara',
      alcinopolis: 'Alcinópolis',
      amambai: 'Amambai',
      anastacio: 'Anastácio',
      anaurilandia: 'Anaurilândia',
      angelica: 'Angélica',
      antonio_joao: 'Antônio João',
      aparecida_do_taboado: 'Aparecida do Taboado',
      aquidauana: 'Aquidauana',
      aral_moreira: 'Aral Moreira',
      bandeirantes: 'Bandeirantes',
      bataguassu: 'Bataguassu',
      bataypora: 'Batayporã',
      bela_vista: 'Bela Vista',
      bodoquena: 'Bodoquena',
      bonito: 'Bonito',
      brasilandia: 'Brasilândia',
      caarapo: 'Caarapó',
      camapua: 'Camapuã',
      campo_grande: 'Campo Grande',
      caracol: 'Caracol',
      cassilandia: 'Cassilândia',
      chapadao_do_sul: 'Chapadão do Sul',
      corguinho: 'Corguinho',
      coronel_sapucaia: 'Coronel Sapucaia',
      corumba: 'Corumbá',
      costa_rica: 'Costa Rica',
      coxim: 'Coxim',
      deodapolis: 'Deodápolis',
      dois_irmaos_do_buriti: 'Dois Irmãos do Buriti',
      douradina: 'Douradina',
      dourados: 'Dourados',
      eldorado: 'Eldorado',
      fatima_do_sul: 'Fátima do Sul',
      figueirao: 'Figueirão',
      gloria_de_dourados: 'Glória de Dourados',
      guia_lopes_da_laguna: 'Guia Lopes da Laguna',
      iguatemi: 'Iguatemi',
      inocencia: 'Inocência',
      itapora: 'Itaporã',
      itaquirai: 'Itaquiraí',
      ivinhema: 'Ivinhema',
      japora: 'Japorã',
      jaraguari: 'Jaraguari',
      jardim: 'Jardim',
      jatei: 'Jateí',
      juti: 'Juti',
      ladario: 'Ladário',
      laguna_carapa: 'Laguna Carapã',
      maracaju: 'Maracaju',
      miranda: 'Miranda',
      mundo_novo: 'Mundo Novo',
      navirai: 'Naviraí',
      nioaque: 'Nioaque',
      nova_alvorada_do_sul: 'Nova Alvorada do Sul',
      nova_andradina: 'Nova Andradina',
      novo_horizonte_do_sul: 'Novo Horizonte do Sul',
      paraiso_das_aguas: 'Paraíso das Águas',
      paranaiba: 'Paranaíba',
      paranhos: 'Paranhos',
      pedro_gomes: 'Pedro Gomes',
      ponta_pora: 'Ponta Porã',
      porto_murtinho: 'Porto Murtinho',
      ribas_do_rio_pardo: 'Ribas do Rio Pardo',
      rio_brilhante: 'Rio Brilhante',
      rio_negro: 'Rio Negro',
      rio_verde_de_mato_grosso: 'Rio Verde de Mato Grosso',
      rochedo: 'Rochedo',
      santa_rita_do_pardo: 'Santa Rita do Pardo',
      sao_gabriel_do_oeste: 'São Gabriel do Oeste',
      selviria: 'Selvíria',
      sete_quedas: 'Sete Quedas',
      sidrolandia: 'Sidrolândia',
      sonora: 'Sonora',
      tacuru: 'Tacuru',
      taquarussu: 'Taquarussu',
      terenos: 'Terenos',
      tres_lagoas: 'Três Lagoas',
      vicentina: 'Vicentina',
    },
    '#Estado': 'MS',
  };
  
  export default cidadesMS;