// cidadesES.js
const cidadesES = {
    '#empty_option': '- Selecione a Cidade -',
    '#options': {
      afonso_claudio: 'Afonso Cláudio',
      agua_doce_do_norte: 'Água Doce do Norte',
      aguia_branca: 'Águia Branca',
      alegre: 'Alegre',
      alfredo_chaves: 'Alfredo Chaves',
      alto_rio_novo: 'Alto Rio Novo',
      anchieta: 'Anchieta',
      apiaca: 'Apiacá',
      aracruz: 'Aracruz',
      atilio_vivacqua: 'Atílio Vivácqua',
      baixo_guandu: 'Baixo Guandu',
      barra_de_sao_francisco: 'Barra de São Francisco',
      boa_esperanca: 'Boa Esperança',
      bom_jesus_do_norte: 'Bom Jesus do Norte',
      brejetuba: 'Brejetuba',
      cachoeiro_de_itapemirim: 'Cachoeiro de Itapemirim',
      cariacica: 'Cariacica',
      castelo: 'Castelo',
      colatina: 'Colatina',
      conceicao_da_barra: 'Conceição da Barra',
      conceicao_do_castelo: 'Conceição do Castelo',
      divino_de_sao_lourenco: 'Divino de São Lourenço',
      domingos_martins: 'Domingos Martins',
      dores_do_rio_preto: 'Dores do Rio Preto',
      ecoporanga: 'Ecoporanga',
      fundao: 'Fundão',
      governador_lindenberg: 'Governador Lindenberg',
      guacui: 'Guaçuí',
      guarapari: 'Guarapari',
      ibatiba: 'Ibatiba',
      ibiracu: 'Ibiraçu',
      ibitirama: 'Ibitirama',
      iconha: 'Iconha',
      irupi: 'Irupi',
      itaguacu: 'Itaguaçu',
      itapemirim: 'Itapemirim',
      itarana: 'Itarana',
      iuna: 'Iúna',
      jaguare: 'Jaguaré',
      jeronimo_monteiro: 'Jerônimo Monteiro',
      joao_neiva: 'João Neiva',
      laranja_da_terra: 'Laranja da Terra',
      linhares: 'Linhares',
      mantenopolis: 'Mantenópolis',
      marataizes: 'Marataízes',
      marechal_floriano: 'Marechal Floriano',
      marilandia: 'Marilândia',
      mimoso_do_sul: 'Mimoso do Sul',
      montanha: 'Montanha',
      mucurici: 'Mucurici',
      muniz_freire: 'Muniz Freire',
      muqui: 'Muqui',
      nova_venecia: 'Nova Venécia',
      pancas: 'Pancas',
      pedro_canario: 'Pedro Canário',
      pinheiros: 'Pinheiros',
      piuma: 'Piúma',
      ponto_belo: 'Ponto Belo',
      presidente_kennedy: 'Presidente Kennedy',
      rio_bananal: 'Rio Bananal',
      rio_novo_do_sul: 'Rio Novo do Sul',
      santa_leopoldina: 'Santa Leopoldina',
      santa_maria_de_jetiba: 'Santa Maria de Jetibá',
      santa_teresa: 'Santa Teresa',
      sao_domingos_do_norte: 'São Domingos do Norte',
      sao_gabriel_da_palha: 'São Gabriel da Palha',
      sao_jose_do_calcado: 'São José do Calçado',
      sao_mateus: 'São Mateus',
      sao_roque_do_canaa: 'São Roque do Canaã',
      serra: 'Serra',
      sooretama: 'Sooretama',
      vargem_alta: 'Vargem Alta',
      venda_nova_do_imigrante: 'Venda Nova do Imigrante',
      viana: 'Viana',
      vila_pavao: 'Vila Pavão',
      vila_valerio: 'Vila Valério',
      vila_velha: 'Vila Velha',
      vitoria: 'Vitória',
    },
    '#Estado': 'ES',
  };
  
  export default cidadesES;