// cidadesMG.jsx
const cidadesMG = {
    '#empty_option': '- Selecione a Cidade -',
    '#options': {
      abadia_dos_dourados: 'Abadia dos Dourados',
      abaete: 'Abaeté',
      abre_campo: 'Abre Campo',
      acaiaca: 'Acaiaca',
      acucena: 'Açucena',
      agua_boa: 'Água Boa',
      agua_comprida: 'Água Comprida',
      aguanil: 'Aguanil',
      aguas_formosas: 'Águas Formosas',
      aguas_vermelhas: 'Águas Vermelhas',
      aimores: 'Aimorés',
      aiuruoca: 'Aiuruoca',
      alagoa: 'Alagoa',
      albertina: 'Albertina',
      alem_paraiba: 'Além Paraíba',
      alfenas: 'Alfenas',
      alfredo_vasconcelos: 'Alfredo Vasconcelos',
      almenara: 'Almenara',
      alpercata: 'Alpercata',
      alpinopolis: 'Alpinópolis',
      alterosa: 'Alterosa',
      alto_caparao: 'Alto Caparaó',
      alto_jequitiba: 'Alto Jequitibá',
      alto_rio_doce: 'Alto Rio Doce',
      alvarenga: 'Alvarenga',
      alvinopolis: 'Alvinópolis',
      alvorada_de_minas: 'Alvorada de Minas',
      amparo_da_serra: 'Amparo da Serra',
      andradas: 'Andradas',
      andrelandia: 'Andrelândia',
      angelandia: 'Angelândia',
      antonio_carlos: 'Antônio Carlos',
      antonio_dias: 'Antônio Dias',
      antonio_prado_de_minas: 'Antônio Prado de Minas',
      aracai: 'Araçaí',
      aracitaba: 'Aracitaba',
      aracuai: 'Araçuaí',
      araguari: 'Araguari',
      arantina: 'Arantina',
      araponga: 'Araponga',
      arapora: 'Araporã',
      arapua: 'Arapuá',
      araujos: 'Araújos',
      araxa: 'Araxá',
      arceburgo: 'Arceburgo',
      arcos: 'Arcos',
      areado: 'Areado',
      argirita: 'Argirita',
      aricanduva: 'Aricanduva',
      arinos: 'Arinos',
      astolfo_dutra: 'Astolfo Dutra',
      ataleia: 'Ataléia',
      augusto_de_lima: 'Augusto de Lima',
      baependi: 'Baependi',
      baldim: 'Baldim',
      bambui: 'Bambuí',
      bandeira: 'Bandeira',
      bandeira_do_sul: 'Bandeira do Sul',
      barao_de_cocais: 'Barão de Cocais',
      barao_de_monte_alto: 'Barão de Monte Alto',
      barbacena: 'Barbacena',
      barra_longa: 'Barra Longa',
      barroso: 'Barroso',
      bela_vista_de_minas: 'Bela Vista de Minas',
      belmiro_braga: 'Belmiro Braga',
      belo_horizonte: 'Belo Horizonte',
      belo_oriente: 'Belo Oriente',
      belo_vale: 'Belo Vale',
      berilo: 'Berilo',
      berizal: 'Berizal',
      bertopolis: 'Bertópolis',
      betim: 'Betim',
      bias_fortes: 'Bias Fortes',
      bicas: 'Bicas',
      biquinhas: 'Biquinhas',
      boa_esperanca: 'Boa Esperança',
      bocaina_de_minas: 'Bocaina de Minas',
      bocaiuva: 'Bocaiuva',
      bom_despacho: 'Bom Despacho',
      bom_jardim_de_minas: 'Bom Jardim de Minas',
      bom_jesus_da_penha: 'Bom Jesus da Penha',
      bom_jesus_do_amparo: 'Bom Jesus do Amparo',
      bom_jesus_do_galho: 'Bom Jesus do Galho',
      bom_repouso: 'Bom Repouso',
      bom_sucesso: 'Bom Sucesso',
      bonfim: 'Bonfim',
      bonfinopolis_de_minas: 'Bonfinópolis de Minas',
      bonito_de_minas: 'Bonito de Minas',
      borda_da_mata: 'Borda da Mata',
      botelhos: 'Botelhos',
      botumirim: 'Botumirim',
      bras_pires: 'Brás Pires',
      brasilandia_de_minas: 'Brasilândia de Minas',
      brasilia_de_minas: 'Brasília de Minas',
      braunas: 'Braúnas',
      brazopolis: 'Brazópolis',
      brumadinho: 'Brumadinho',
      bueno_brandao: 'Bueno Brandão',
      buenopolis: 'Buenópolis',
      bugre: 'Bugre',
      buritis: 'Buritis',
      buritizeiro: 'Buritizeiro',
      cabeceira_grande: 'Cabeceira Grande',
      cabo_verde: 'Cabo Verde',
      cachoeira_da_prata: 'Cachoeira da Prata',
      cachoeira_de_minas: 'Cachoeira de Minas',
      cachoeira_de_pajeu: 'Cachoeira de Pajeú',
      cachoeira_dourada: 'Cachoeira Dourada',
      caetanopolis: 'Caetanópolis',
      caete: 'Caeté',
      caiana: 'Caiana',
      cajuri: 'Cajuri',
      caldas: 'Caldas',
      camacho: 'Camacho',
      camanducaia: 'Camanducaia',
      cambui: 'Cambuí',
      cambuquira: 'Cambuquira',
      campanario: 'Campanário',
      campanha: 'Campanha',
      campestre: 'Campestre',
      campina_verde: 'Campina Verde',
      campo_azul: 'Campo Azul',
      campo_belo: 'Campo Belo',
      campo_do_meio: 'Campo do Meio',
      campo_florido: 'Campo Florido',
      campos_altos: 'Campos Altos',
      campos_gerais: 'Campos Gerais',
      cana_verde: 'Cana Verde',
      canaa: 'Canaã',
      canapolis: 'Canápolis',
      candeias: 'Candeias',
      cantagalo: 'Cantagalo',
      caparao: 'Caparaó',
      capela_nova: 'Capela Nova',
      capelinha: 'Capelinha',
      capetinga: 'Capetinga',
      capim_branco: 'Capim Branco',
      capinopolis: 'Capinópolis',
      capitao_andrade: 'Capitão Andrade',
      capitao_eneas: 'Capitão Enéas',
      capitolio: 'Capitólio',
      caputira: 'Caputira',
      carai: 'Caraí',
      caranaiba: 'Caranaíba',
      carandai: 'Carandaí',
      carangola: 'Carangola',
      caratinga: 'Caratinga',
      carbonita: 'Carbonita',
      careacu: 'Careaçu',
      carlos_chagas: 'Carlos Chagas',
      carmesia: 'Carmésia',
      carmo_da_cachoeira: 'Carmo da Cachoeira',
      carmo_da_mata: 'Carmo da Mata',
      carmo_de_minas: 'Carmo de Minas',
      carmo_do_cajuru: 'Carmo do Cajuru',
      carmo_do_paranaiba: 'Carmo do Paranaíba',
      carmo_do_rio_claro: 'Carmo do Rio Claro',
      carmopolis_de_minas: 'Carmópolis de Minas',
      carneirinho: 'Carneirinho',
      carrancas: 'Carrancas',
      carvalhopolis: 'Carvalhópolis',
      carvalhos: 'Carvalhos',
      casa_grande: 'Casa Grande',
      cascalho_rico: 'Cascalho Rico',
      cassia: 'Cássia',
      cataguases: 'Cataguases',
      catas_altas_da_noruega: 'Catas Altas da Noruega',
      catas_altas: 'Catas Altas',
      catuji: 'Catuji',
      catuti: 'Catuti',
      caxambu: 'Caxambu',
      cedro_do_abaete: 'Cedro do Abaeté',
      central_de_minas: 'Central de Minas',
      centralina: 'Centralina',
      chacara: 'Chácara',
      chale: 'Chalé',
      chapada_do_norte: 'Chapada do Norte',
      chapada_gaucha: 'Chapada Gaúcha',
      chiador: 'Chiador',
      cipotanea: 'Cipotânea',
      claraval: 'Claraval',
      claro_dos_pocoes: 'Claro dos Poções',
      claudio: 'Cláudio',
      coimbra: 'Coimbra',
      coluna: 'Coluna',
      comendador_gomes: 'Comendador Gomes',
      comercinho: 'Comercinho',
      conceicao_da_aparecida: 'Conceição da Aparecida',
      conceicao_da_barra_de_minas: 'Conceição da Barra de Minas',
      conceicao_das_alagoas: 'Conceição das Alagoas',
      conceicao_das_pedras: 'Conceição das Pedras',
      conceicao_de_ipanema: 'Conceição de Ipanema',
      conceicao_do_mato_dentro: 'Conceição do Mato Dentro',
      conceicao_do_para: 'Conceição do Pará',
      conceicao_do_rio_verde: 'Conceição do Rio Verde',
      conceicao_dos_ouros: 'Conceição dos Ouros',
      conego_marinho: 'Cônego Marinho',
      confins: 'Confins',
      congonhal: 'Congonhal',
      congonhas_do_norte: 'Congonhas do Norte',
      congonhas: 'Congonhas',
      conquista: 'Conquista',
      conselheiro_lafaiete: 'Conselheiro Lafaiete',
      conselheiro_pena: 'Conselheiro Pena',
      consolacao: 'Consolação',
      contagem: 'Contagem',
      coqueiral: 'Coqueiral',
      coracao_de_jesus: 'Coração de Jesus',
      cordisburgo: 'Cordisburgo',
      cordislandia: 'Cordislândia',
      corinto: 'Corinto',
      coroaci: 'Coroaci',
      coromandel: 'Coromandel',
      coronel_fabriciano: 'Coronel Fabriciano',
      coronel_murta: 'Coronel Murta',
      coronel_pacheco: 'Coronel Pacheco',
      coronel_xavier_chaves: 'Coronel Xavier Chaves',
      corrego_danta: 'Córrego Danta',
      corrego_do_bom_jesus: 'Córrego do Bom Jesus',
      corrego_fundo: 'Córrego Fundo',
      corrego_novo: 'Córrego Novo',
      couto_de_magalhaes_de_minas: 'Couto de Magalhães de Minas',
      crisolita: 'Crisólita',
      cristais: 'Cristais',
      cristalia: 'Cristália',
      cristiano_otoni: 'Cristiano Otoni',
      cristina: 'Cristina',
      crucilandia: 'Crucilândia',
      cruzeiro_da_fortaleza: 'Cruzeiro da Fortaleza',
      cruzilia: 'Cruzília',
      cuparaque: 'Cuparaque',
      curral_de_dentro: 'Curral de Dentro',
      curvelo: 'Curvelo',
      datas: 'Datas',
      delfim_moreira: 'Delfim Moreira',
      delfinopolis: 'Delfinópolis',
      delta: 'Delta',
      descoberto: 'Descoberto',
      desterro_de_entre_rios: 'Desterro de Entre Rios',
      desterro_do_melo: 'Desterro do Melo',
      diamantina: 'Diamantina',
      diogo_de_vasconcelos: 'Diogo de Vasconcelos',
      dionisio: 'Dionísio',
      divinesia: 'Divinésia',
      divino: 'Divino',
      divino_das_laranjeiras: 'Divino das Laranjeiras',
      divinolandia_de_minas: 'Divinolândia de Minas',
      divinopolis: 'Divinópolis',
      divisa_alegre: 'Divisa Alegre',
      divisa_nova: 'Divisa Nova',
      divisopolis: 'Divisópolis',
      dom_bosco: 'Dom Bosco',
      dom_cavati: 'Dom Cavati',
      dom_joaquim: 'Dom Joaquim',
      dom_silverio: 'Dom Silvério',
      dom_vicoso: 'Dom Viçoso',
      dona_euzebia: 'Dona Euzébia',
      dores_de_campos: 'Dores de Campos',
      dores_de_guanhaes: 'Dores de Guanhães',
      dores_do_indaia: 'Dores do Indaiá',
      dores_do_turvo: 'Dores do Turvo',
      doresopolis: 'Doresópolis',
      douradoquara: 'Douradoquara',
      durande: 'Durandé',
      eloi_mendes: 'Elói Mendes',
      engenheiro_caldas: 'Engenheiro Caldas',
      engenheiro_navarro: 'Engenheiro Navarro',
      entre_folhas: 'Entre Folhas',
      entre_rios_de_minas: 'Entre Rios de Minas',
      ervalia: 'Ervália',
      esmeraldas: 'Esmeraldas',
      espera_feliz: 'Espera Feliz',
      espinosa: 'Espinosa',
      espirito_santo_do_dourado: 'Espírito Santo do Dourado',
      estiva: 'Estiva',
      estrela_dalva: 'Estrela Dalva',
      estrela_do_indaia: 'Estrela do Indaiá',
      estrela_do_sul: 'Estrela do Sul',
      eugenopolis: 'Eugenópolis',
      ewbank_da_camara: 'Ewbank da Câmara',
      extrema: 'Extrema',
      fama: 'Fama',
      faria_lemos: 'Faria Lemos',
      felicio_dos_santos: 'Felício dos Santos',
      felisburgo: 'Felisburgo',
      felixlandia: 'Felixlândia',
      fernandes_tourinho: 'Fernandes Tourinho',
      ferros: 'Ferros',
      fervedouro: 'Fervedouro',
      florestal: 'Florestal',
      formiga: 'Formiga',
      formoso: 'Formoso',
      fortaleza_de_minas: 'Fortaleza de Minas',
      fortuna_de_minas: 'Fortuna de Minas',
      francisco_badaro: 'Francisco Badaró',
      francisco_dumont: 'Francisco Dumont',
      francisco_sa: 'Francisco Sá',
      franciscopolis: 'Franciscópolis',
      frei_gaspar: 'Frei Gaspar',
      frei_inocencio: 'Frei Inocêncio',
      frei_lagonegro: 'Frei Lagonegro',
      fronteira: 'Fronteira',
      fronteira_dos_vales: 'Fronteira dos Vales',
      fruta_de_leite: 'Fruta de Leite',
      frutal: 'Frutal',
      funilandia: 'Funilândia',
      galileia: 'Galileia',
      gameleiras: 'Gameleiras',
      glaucilandia: 'Glaucilândia',
      goiabeira: 'Goiabeira',
      goiana: 'Goianá',
      goncalves: 'Gonçalves',
      gonzaga: 'Gonzaga',
      gouveia: 'Gouveia',
      governador_valadares: 'Governador Valadares',
      grao_mogol: 'Grão Mogol',
      grupiara: 'Grupiara',
      guanhaes: 'Guanhães',
      guape: 'Guapé',
      guaraciaba: 'Guaraciaba',
      guaraciama: 'Guaraciama',
      guaranesia: 'Guaranésia',
      guarani: 'Guarani',
      guarara: 'Guarará',
      guarda_mor: 'Guarda-Mor',
      guaxupe: 'Guaxupé',
      guidoval: 'Guidoval',
      guimarania: 'Guimarânia',
      guiricema: 'Guiricema',
      gurinhata: 'Gurinhatã',
      heliodora: 'Heliodora',
      iapu: 'Iapu',
      ibertioga: 'Ibertioga',
      ibia: 'Ibiá',
      ibiai: 'Ibiaí',
      ibiracatu: 'Ibiracatu',
      ibiraci: 'Ibiraci',
      ibirite: 'Ibirité',
      ibitiura_de_minas: 'Ibitiúra de Minas',
      ibituruna: 'Ibituruna',
      icarai_de_minas: 'Icaraí de Minas',
      igarape: 'Igarapé',
      igaratinga: 'Igaratinga',
      iguatama: 'Iguatama',
      ijaci: 'Ijaci',
      ilicinea: 'Ilicínea',
      imbe_de_minas: 'Imbé de Minas',
      inconfidentes: 'Inconfidentes',
      indaiabira: 'Indaiabira',
      indianopolis: 'Indianópolis',
      ingai: 'Ingaí',
      inhapim: 'Inhapim',
      inhauma: 'Inhaúma',
      inimutaba: 'Inimutaba',
      ipaba: 'Ipaba',
      ipanema: 'Ipanema',
      ipatinga: 'Ipatinga',
      ipiacu: 'Ipiaçu',
      ipuiuna: 'Ipuiuna',
      irai_de_minas: 'Iraí de Minas',
      itabira: 'Itabira',
      itabirinha: 'Itabirinha',
      itabirito: 'Itabirito',
      itacambira: 'Itacambira',
      itacarambi: 'Itacarambi',
      itaguara: 'Itaguara',
      itaipe: 'Itaipé',
      itajuba: 'Itajubá',
      itamarandiba: 'Itamarandiba',
      itamarati_de_minas: 'Itamarati de Minas',
      itambacuri: 'Itambacuri',
      itambe_do_mato_dentro: 'Itambé do Mato Dentro',
      itamogi: 'Itamogi',
      itamonte: 'Itamonte',
      itanhandu: 'Itanhandu',
      itanhomi: 'Itanhomi',
      itaobim: 'Itaobim',
      itapagipe: 'Itapagipe',
      itapecerica: 'Itapecerica',
      itapeva: 'Itapeva',
      itatiaiucu: 'Itatiaiuçu',
      itau_de_minas: 'Itaú de Minas',
      itauna: 'Itaúna',
      itaverava: 'Itaverava',
      itinga: 'Itinga',
      itueta: 'Itueta',
      ituiutaba: 'Ituiutaba',
      itumirim: 'Itumirim',
      iturama: 'Iturama',
      itutinga: 'Itutinga',
      jaboticatubas: 'Jaboticatubas',
      jacinto: 'Jacinto',
      jacui: 'Jacuí',
      jacutinga: 'Jacutinga',
      jaguaracu: 'Jaguaraçu',
      jaiba: 'Jaíba',
      jampruca: 'Jampruca',
      janauba: 'Janaúba',
      januaria: 'Januária',
      japaraiba: 'Japaraíba',
      japonvar: 'Japonvar',
      jeceaba: 'Jeceaba',
      jenipapo_de_minas: 'Jenipapo de Minas',
      jequeri: 'Jequeri',
      jequitai: 'Jequitaí',
      jequitiba: 'Jequitibá',
      jequitinhonha: 'Jequitinhonha',
      jesuania: 'Jesuânia',
      joaima: 'Joaíma',
      joanesia: 'Joanésia',
      joao_monlevade: 'João Monlevade',
      joao_pinheiro: 'João Pinheiro',
      joaquim_felicio: 'Joaquim Felício',
      jordania: 'Jordânia',
      jose_goncalves_de_minas: 'José Gonçalves de Minas',
      jose_raydan: 'José Raydan',
      josenopolis: 'Josenópolis',
      juatuba: 'Juatuba',
      juiz_de_fora: 'Juiz de Fora',
      juramento: 'Juramento',
      juruaia: 'Juruaia',
      juvenilia: 'Juvenília',
      ladainha: 'Ladainha',
      lagamar: 'Lagamar',
      lagoa_da_prata: 'Lagoa da Prata',
      lagoa_dos_patos: 'Lagoa dos Patos',
      lagoa_dourada: 'Lagoa Dourada',
      lagoa_formosa: 'Lagoa Formosa',
      lagoa_grande: 'Lagoa Grande',
      lagoa_santa: 'Lagoa Santa',
      lajinha: 'Lajinha',
      lambari: 'Lambari',
      lamim: 'Lamim',
      laranjal: 'Laranjal',
      lassance: 'Lassance',
      lavras: 'Lavras',
      leandro_ferreira: 'Leandro Ferreira',
      leme_do_prado: 'Leme do Prado',
      leopoldina: 'Leopoldina',
      liberdade: 'Liberdade',
      lima_duarte: 'Lima Duarte',
      limeira_do_oeste: 'Limeira do Oeste',
      lontra: 'Lontra',
      luisburgo: 'Luisburgo',
      luislandia: 'Luislândia',
      luminarias: 'Luminárias',
      luz: 'Luz',
      machacalis: 'Machacalis',
      machado: 'Machado',
      madre_de_deus_de_minas: 'Madre de Deus de Minas',
      malacacheta: 'Malacacheta',
      mamonas: 'Mamonas',
      manga: 'Manga',
      manhuacu: 'Manhuaçu',
      manhumirim: 'Manhumirim',
      mantena: 'Mantena',
      mar_de_espanha: 'Mar de Espanha',
      maravilhas: 'Maravilhas',
      maria_da_fe: 'Maria da Fé',
      mariana: 'Mariana',
      marilac: 'Marilac',
      mario_campos: 'Mário Campos',
      maripa_de_minas: 'Maripá de Minas',
      marlieria: 'Marliéria',
      marmelopolis: 'Marmelópolis',
      martinho_campos: 'Martinho Campos',
      martins_soares: 'Martins Soares',
      mata_verde: 'Mata Verde',
      materlandia: 'Materlândia',
      mateus_leme: 'Mateus Leme',
      mathias_lobato: 'Mathias Lobato',
      matias_barbosa: 'Matias Barbosa',
      matias_cardoso: 'Matias Cardoso',
      matipo: 'Matipó',
      mato_verde: 'Mato Verde',
      matozinhos: 'Matozinhos',
      matutina: 'Matutina',
      medeiros: 'Medeiros',
      medina: 'Medina',
      mendes_pimentel: 'Mendes Pimentel',
      merces: 'Mercês',
      mesquita: 'Mesquita',
      minas_novas: 'Minas Novas',
      minduri: 'Minduri',
      mirabela: 'Mirabela',
      miradouro: 'Miradouro',
      mirai: 'Miraí',
      miravania: 'Miravânia',
      moeda: 'Moeda',
      moema: 'Moema',
      monjolos: 'Monjolos',
      monsenhor_paulo: 'Monsenhor Paulo',
      montalvania: 'Montalvânia',
      monte_alegre_de_minas: 'Monte Alegre de Minas',
      monte_azul: 'Monte Azul',
      monte_belo: 'Monte Belo',
      monte_carmelo: 'Monte Carmelo',
      monte_formoso: 'Monte Formoso',
      monte_santo_de_minas: 'Monte Santo de Minas',
      monte_siao: 'Monte Sião',
      montes_claros: 'Montes Claros',
      montezuma: 'Montezuma',
      morada_nova_de_minas: 'Morada Nova de Minas',
      morro_da_garca: 'Morro da Garça',
      morro_do_pilar: 'Morro do Pilar',
      munhoz: 'Munhoz',
      muriae: 'Muriaé',
      mutum: 'Mutum',
      muzambinho: 'Muzambinho',
      nacip_raydan: 'Nacip Raydan',
      nanuque: 'Nanuque',
      naque: 'Naque',
      natalandia: 'Natalândia',
      natercia: 'Natércia',
      nazareno: 'Nazareno',
      nepomuceno: 'Nepomuceno',
      ninheira: 'Ninheira',
      nova_belem: 'Nova Belém',
      nova_era: 'Nova Era',
      nova_lima: 'Nova Lima',
      nova_modica: 'Nova Módica',
      nova_ponte: 'Nova Ponte',
      nova_porteirinha: 'Nova Porteirinha',
      nova_resende: 'Nova Resende',
      nova_serrana: 'Nova Serrana',
      nova_uniao: 'Nova União',
      novo_cruzeiro: 'Novo Cruzeiro',
      novo_oriente_de_minas: 'Novo Oriente de Minas',
      novorizonte: 'Novorizonte',
      olaria: 'Olaria',
      olhos_dagua: 'Olhos-dÁgua',
      olimpio_noronha: 'Olímpio Noronha',
      oliveira: 'Oliveira',
      oliveira_fortes: 'Oliveira Fortes',
      onca_de_pitangui: 'Onça de Pitangui',
      oratorios: 'Oratórios',
      orizania: 'Orizânia',
      ouro_branco: 'Ouro Branco',
      ouro_fino: 'Ouro Fino',
      ouro_preto: 'Ouro Preto',
      ouro_verde_de_minas: 'Ouro Verde de Minas',
      padre_carvalho: 'Padre Carvalho',
      padre_paraiso: 'Padre Paraíso',
      pai_pedro: 'Pai Pedro',
      paineiras: 'Paineiras',
      pains: 'Pains',
      paiva: 'Paiva',
      palma: 'Palma',
      palmopolis: 'Palmópolis',
      papagaios: 'Papagaios',
      para_de_minas: 'Pará de Minas',
      paracatu: 'Paracatu',
      paraguacu: 'Paraguaçu',
      paraisopolis: 'Paraisópolis',
      paraopeba: 'Paraopeba',
      passa_quatro: 'Passa Quatro',
      passa_tempo: 'Passa Tempo',
      passa_vinte: 'Passa Vinte',
      passabem: 'Passabém',
      passos: 'Passos',
      patis: 'Patis',
      patos_de_minas: 'Patos de Minas',
      patrocinio_do_muriae: 'Patrocínio do Muriaé',
      patrocinio: 'Patrocínio',
      paula_candido: 'Paula Cândido',
      paulistas: 'Paulistas',
      pavao: 'Pavão',
      pecanha: 'Peçanha',
      pedra_azul: 'Pedra Azul',
      pedra_bonita: 'Pedra Bonita',
      pedra_do_anta: 'Pedra do Anta',
      pedra_do_indaia: 'Pedra do Indaiá',
      pedra_dourada: 'Pedra Dourada',
      pedralva: 'Pedralva',
      pedras_de_maria_da_cruz: 'Pedras de Maria da Cruz',
      pedrinopolis: 'Pedrinópolis',
      pedro_leopoldo: 'Pedro Leopoldo',
      pedro_teixeira: 'Pedro Teixeira',
      pequeri: 'Pequeri',
      pequi: 'Pequi',
      perdigao: 'Perdigão',
      perdizes: 'Perdizes',
      perdoes: 'Perdões',
      periquito: 'Periquito',
      pescador: 'Pescador',
      piau: 'Piau',
      piedade_de_caratinga: 'Piedade de Caratinga',
      piedade_de_ponte_nova: 'Piedade de Ponte Nova',
      piedade_do_rio_grande: 'Piedade do Rio Grande',
      piedade_dos_gerais: 'Piedade dos Gerais',
      pimenta: 'Pimenta',
      pingo_dagua: 'Pingo-dÁgua',
      pintopolis: 'Pintópolis',
      piracema: 'Piracema',
      pirajuba: 'Pirajuba',
      piranga: 'Piranga',
      pirangucu: 'Piranguçu',
      piranguinho: 'Piranguinho',
      pirapetinga: 'Pirapetinga',
      pirapora: 'Pirapora',
      pirauba: 'Piraúba',
      pitangui: 'Pitangui',
      piumhi: 'Piumhi',
      planura: 'Planura',
      poco_fundo: 'Poço Fundo',
      pocos_de_caldas: 'Poços de Caldas',
      pocrane: 'Pocrane',
      pompeu: 'Pompéu',
      ponte_nova: 'Ponte Nova',
      ponto_chique: 'Ponto Chique',
      ponto_dos_volantes: 'Ponto dos Volantes',
      porteirinha: 'Porteirinha',
      porto_firme: 'Porto Firme',
      pote: 'Poté',
      pouso_alegre: 'Pouso Alegre',
      pouso_alto: 'Pouso Alto',
      prados: 'Prados',
      prata: 'Prata',
      pratapolis: 'Pratápolis',
      pratinha: 'Pratinha',
      presidente_bernardes: 'Presidente Bernardes',
      presidente_juscelino: 'Presidente Juscelino',
      presidente_kubitschek: 'Presidente Kubitschek',
      presidente_olegario: 'Presidente Olegário',
      prudente_de_morais: 'Prudente de Morais',
      quartel_geral: 'Quartel Geral',
      queluzito: 'Queluzito',
      raposos: 'Raposos',
      raul_soares: 'Raul Soares',
      recreio: 'Recreio',
      reduto: 'Reduto',
      resende_costa: 'Resende Costa',
      resplendor: 'Resplendor',
      ressaquinha: 'Ressaquinha',
      riachinho: 'Riachinho',
      riacho_dos_machados: 'Riacho dos Machados',
      ribeirao_das_neves: 'Ribeirão das Neves',
      ribeirao_vermelho: 'Ribeirão Vermelho',
      rio_acima: 'Rio Acima',
      rio_casca: 'Rio Casca',
      rio_do_prado: 'Rio do Prado',
      rio_doce: 'Rio Doce',
      rio_espera: 'Rio Espera',
      rio_manso: 'Rio Manso',
      rio_novo: 'Rio Novo',
      rio_paranaiba: 'Rio Paranaíba',
      rio_pardo_de_minas: 'Rio Pardo de Minas',
      rio_piracicaba: 'Rio Piracicaba',
      rio_pomba: 'Rio Pomba',
      rio_preto: 'Rio Preto',
      rio_vermelho: 'Rio Vermelho',
      ritapolis: 'Ritápolis',
      rochedo_de_minas: 'Rochedo de Minas',
      rodeiro: 'Rodeiro',
      romaria: 'Romaria',
      rosario_da_limeira: 'Rosário da Limeira',
      rubelita: 'Rubelita',
      rubim: 'Rubim',
      sabara: 'Sabará',
      sabinopolis: 'Sabinópolis',
      sacramento: 'Sacramento',
      salinas: 'Salinas',
      salto_da_divisa: 'Salto da Divisa',
      santa_barbara: 'Santa Bárbara',
      santa_barbara_do_leste: 'Santa Bárbara do Leste',
      santa_barbara_do_monte_verde: 'Santa Bárbara do Monte Verde',
      santa_barbara_do_tugurio: 'Santa Bárbara do Tugúrio',
      santa_cruz_de_minas: 'Santa Cruz de Minas',
      santa_cruz_de_salinas: 'Santa Cruz de Salinas',
      santa_cruz_do_escalvado: 'Santa Cruz do Escalvado',
      santa_efigenia_de_minas: 'Santa Efigênia de Minas',
      santa_fe_de_minas: 'Santa Fé de Minas',
      santa_helena_de_minas: 'Santa Helena de Minas',
      santa_juliana: 'Santa Juliana',
      santa_luzia: 'Santa Luzia',
      santa_margarida: 'Santa Margarida',
      santa_maria_de_itabira: 'Santa Maria de Itabira',
      santa_maria_do_salto: 'Santa Maria do Salto',
      santa_maria_do_suacui: 'Santa Maria do Suaçuí',
      santa_rita_de_caldas: 'Santa Rita de Caldas',
      santa_rita_de_ibitipoca: 'Santa Rita de Ibitipoca',
      santa_rita_de_jacutinga: 'Santa Rita de Jacutinga',
      santa_rita_de_minas: 'Santa Rita de Minas',
      santa_rita_do_itueto: 'Santa Rita do Itueto',
      santa_rita_do_sapucai: 'Santa Rita do Sapucaí',
      santa_rosa_da_serra: 'Santa Rosa da Serra',
      santa_vitoria: 'Santa Vitória',
      santana_da_vargem: 'Santana da Vargem',
      santana_de_cataguases: 'Santana de Cataguases',
      santana_de_pirapama: 'Santana de Pirapama',
      santana_do_deserto: 'Santana do Deserto',
      santana_do_garambeu: 'Santana do Garambéu',
      santana_do_jacare: 'Santana do Jacaré',
      santana_do_manhuacu: 'Santana do Manhuaçu',
      santana_do_paraiso: 'Santana do Paraíso',
      santana_do_riacho: 'Santana do Riacho',
      santana_dos_montes: 'Santana dos Montes',
      santo_antonio_do_amparo: 'Santo Antônio do Amparo',
      santo_antonio_do_aventureiro: 'Santo Antônio do Aventureiro',
      santo_antonio_do_grama: 'Santo Antônio do Grama',
      santo_antonio_do_itambe: 'Santo Antônio do Itambé',
      santo_antonio_do_jacinto: 'Santo Antônio do Jacinto',
      santo_antonio_do_monte: 'Santo Antônio do Monte',
      santo_antonio_do_retiro: 'Santo Antônio do Retiro',
      santo_antonio_do_rio_abaixo: 'Santo Antônio do Rio Abaixo',
      santo_hipolito: 'Santo Hipólito',
      santos_dumont: 'Santos Dumont',
      sao_bento_abade: 'São Bento Abade',
      sao_bras_do_suacui: 'São Brás do Suaçuí',
      sao_domingos_das_dores: 'São Domingos das Dores',
      sao_domingos_do_prata: 'São Domingos do Prata',
      sao_felix_de_minas: 'São Félix de Minas',
      sao_francisco: 'São Francisco',
      sao_francisco_de_paula: 'São Francisco de Paula',
      sao_francisco_de_sales: 'São Francisco de Sales',
      sao_francisco_do_gloria: 'São Francisco do Glória',
      sao_geraldo: 'São Geraldo',
      sao_geraldo_da_piedade: 'São Geraldo da Piedade',
      sao_geraldo_do_baixio: 'São Geraldo do Baixio',
      sao_goncalo_do_abaete: 'São Gonçalo do Abaeté',
      sao_goncalo_do_para: 'São Gonçalo do Pará',
      sao_goncalo_do_rio_abaixo: 'São Gonçalo do Rio Abaixo',
      sao_goncalo_do_rio_preto: 'São Gonçalo do Rio Preto',
      sao_goncalo_do_sapucai: 'São Gonçalo do Sapucaí',
      sao_gotardo: 'São Gotardo',
      sao_joao_batista_do_gloria: 'São João Batista do Glória',
      sao_joao_da_lagoa: 'São João da Lagoa',
      sao_joao_da_mata: 'São João da Mata',
      sao_joao_da_ponte: 'São João da Ponte',
      sao_joao_das_missoes: 'São João das Missões',
      sao_joao_del_rei: 'São João del-Rei',
      sao_joao_do_manhuacu: 'São João do Manhuaçu',
      sao_joao_do_manteninha: 'São João do Manteninha',
      sao_joao_do_oriente: 'São João do Oriente',
      sao_joao_do_pacui: 'São João do Pacuí',
      sao_joao_do_paraiso: 'São João do Paraíso',
      sao_joao_evangelista: 'São João Evangelista',
      sao_joao_nepomuceno: 'São João Nepomuceno',
      sao_joaquim_de_bicas: 'São Joaquim de Bicas',
      sao_jose_da_barra: 'São José da Barra',
      sao_jose_da_lapa: 'São José da Lapa',
      sao_jose_da_safira: 'São José da Safira',
      sao_jose_da_varginha: 'São José da Varginha',
      sao_jose_do_alegre: 'São José do Alegre',
      sao_jose_do_divino: 'São José do Divino',
      sao_jose_do_goiabal: 'São José do Goiabal',
      sao_jose_do_jacuri: 'São José do Jacuri',
      sao_jose_do_mantimento: 'São José do Mantimento',
      sao_lourenco: 'São Lourenço',
      sao_miguel_do_anta: 'São Miguel do Anta',
      sao_pedro_da_uniao: 'São Pedro da União',
      sao_pedro_do_suacui: 'São Pedro do Suaçuí',
      sao_pedro_dos_ferros: 'São Pedro dos Ferros',
      sao_romao: 'São Romão',
      sao_roque_de_minas: 'São Roque de Minas',
      sao_sebastiao_da_bela_vista: 'São Sebastião da Bela Vista',
      sao_sebastiao_da_vargem_alegre: 'São Sebastião da Vargem Alegre',
      sao_sebastiao_do_anta: 'São Sebastião do Anta',
      sao_sebastiao_do_maranhao: 'São Sebastião do Maranhão',
      sao_sebastiao_do_oeste: 'São Sebastião do Oeste',
      sao_sebastiao_do_paraiso: 'São Sebastião do Paraíso',
      sao_sebastiao_do_rio_preto: 'São Sebastião do Rio Preto',
      sao_sebastiao_do_rio_verde: 'São Sebastião do Rio Verde',
      sao_tiago: 'São Tiago',
      sao_tomas_de_aquino: 'São Tomás de Aquino',
      sao_tome_das_letras: 'São Tomé das Letras',
      sao_vicente_de_minas: 'São Vicente de Minas',
      sapucai_mirim: 'Sapucaí-Mirim',
      sardoa: 'Sardoá',
      sarzedo: 'Sarzedo',
      sem_peixe: 'Sem-Peixe',
      senador_amaral: 'Senador Amaral',
      senador_cortes: 'Senador Cortes',
      senador_firmino: 'Senador Firmino',
      senador_jose_bento: 'Senador José Bento',
      senador_modestino_goncalves: 'Senador Modestino Gonçalves',
      senhora_de_oliveira: 'Senhora de Oliveira',
      senhora_do_porto: 'Senhora do Porto',
      senhora_dos_remedios: 'Senhora dos Remédios',
      sericita: 'Sericita',
      seritinga: 'Seritinga',
      serra_azul_de_minas: 'Serra Azul de Minas',
      serra_da_saudade: 'Serra da Saudade',
      serra_do_salitre: 'Serra do Salitre',
      serra_dos_aimores: 'Serra dos Aimorés',
      serrania: 'Serrania',
      serranopolis_de_minas: 'Serranópolis de Minas',
      serranos: 'Serranos',
      serro: 'Serro',
      sete_lagoas: 'Sete Lagoas',
      setubinha: 'Setubinha',
      silveirania: 'Silveirânia',
      silvianopolis: 'Silvianópolis',
      simao_pereira: 'Simão Pereira',
      simonesia: 'Simonésia',
      sobralia: 'Sobrália',
      soledade_de_minas: 'Soledade de Minas',
      tabuleiro: 'Tabuleiro',
      taiobeiras: 'Taiobeiras',
      taparuba: 'Taparuba',
      tapira: 'Tapira',
      tapirai: 'Tapiraí',
      taquaracu_de_minas: 'Taquaraçu de Minas',
      tarumirim: 'Tarumirim',
      teixeiras: 'Teixeiras',
      teofilo_otoni: 'Teófilo Otoni',
      timoteo: 'Timóteo',
      tiradentes: 'Tiradentes',
      tiros: 'Tiros',
      tocantins: 'Tocantins',
      tocos_do_moji: 'Tocos do Moji',
      toledo: 'Toledo',
      tombos: 'Tombos',
      tres_coracoes: 'Três Corações',
      tres_marias: 'Três Marias',
      tres_pontas: 'Três Pontas',
      tumiritinga: 'Tumiritinga',
      tupaciguara: 'Tupaciguara',
      turmalina: 'Turmalina',
      turvolandia: 'Turvolândia',
      uba: 'Ubá',
      ubai: 'Ubaí',
      ubaporanga: 'Ubaporanga',
      uberaba: 'Uberaba',
      uberlandia: 'Uberlândia',
      umburatiba: 'Umburatiba',
      unai: 'Unaí',
      uniao_de_minas: 'União de Minas',
      uruana_de_minas: 'Uruana de Minas',
      urucania: 'Urucânia',
      urucuia: 'Urucuia',
      vargem_alegre: 'Vargem Alegre',
      vargem_bonita: 'Vargem Bonita',
      vargem_grande_do_rio_pardo: 'Vargem Grande do Rio Pardo',
      varginha: 'Varginha',
      varjao_de_minas: 'Varjão de Minas',
      varzea_da_palma: 'Várzea da Palma',
      varzelandia: 'Varzelândia',
      vazante: 'Vazante',
      verdelandia: 'Verdelândia',
      veredinha: 'Veredinha',
      verissimo: 'Veríssimo',
      vermelho_novo: 'Vermelho Novo',
      vespasiano: 'Vespasiano',
      vicosa: 'Viçosa',
      vieiras: 'Vieiras',
      virgem_da_lapa: 'Virgem da Lapa',
      virginia: 'Virgínia',
      virginopolis: 'Virginópolis',
      virgolandia: 'Virgolândia',
      visconde_do_rio_branco: 'Visconde do Rio Branco',
      volta_grande: 'Volta Grande',
      wenceslau_braz: 'Wenceslau Braz',
    },
    '#Estado': 'MG',
  };
  
  export default cidadesMG;