const cidadesPE = {
    '#empty_option': '- Selecione a Cidade -',
    '#options': {
      abreu_e_lima: 'Abreu e Lima',
      afogados_da_ingazeira: 'Afogados da Ingazeira',
      afranio: 'Afrânio',
      agrestina: 'Agrestina',
      agua_preta: 'Água Preta',
      aguas_belas: 'Águas Belas',
      alagoinha: 'Alagoinha',
      alianca: 'Aliança',
      altinho: 'Altinho',
      amaraji: 'Amaraji',
      angelim: 'Angelim',
      aracoiaba: 'Araçoiaba',
      araripina: 'Araripina',
      arcoverde: 'Arcoverde',
      barra_de_guabiraba: 'Barra de Guabiraba',
      barreiros: 'Barreiros',
      belem_de_maria: 'Belém de Maria',
      belem_do_sao_francisco: 'Belém do São Francisco',
      belo_jardim: 'Belo Jardim',
      betania: 'Betânia',
      bezerros: 'Bezerros',
      bodoco: 'Bodocó',
      bom_conselho: 'Bom Conselho',
      bom_jardim: 'Bom Jardim',
      bonito: 'Bonito',
      brejao: 'Brejão',
      brejinho: 'Brejinho',
      brejo_da_madre_de_deus: 'Brejo da Madre de Deus',
      buenos_aires: 'Buenos Aires',
      buique: 'Buíque',
      cabo_de_santo_agostinho: 'Cabo de Santo Agostinho',
      cabrobo: 'Cabrobó',
      cachoeirinha: 'Cachoeirinha',
      caetes: 'Caetés',
      calcado: 'Calçado',
      calumbi: 'Calumbi',
      camaragibe: 'Camaragibe',
      camocim_de_sao_felix: 'Camocim de São Félix',
      camutanga: 'Camutanga',
      canhotinho: 'Canhotinho',
      capoeiras: 'Capoeiras',
      carnaiba: 'Carnaíba',
      carnaubeira_da_penha: 'Carnaubeira da Penha',
      carpina: 'Carpina',
      caruaru: 'Caruaru',
      casinhas: 'Casinhas',
      catende: 'Catende',
      cedro: 'Cedro',
      cha_de_alegria: 'Chã de Alegria',
      cha_grande: 'Chã Grande',
      condado: 'Condado',
      correntes: 'Correntes',
      cortes: 'Cortês',
      cumaru: 'Cumaru',
      cupira: 'Cupira',
      custodia: 'Custódia',
      dormentes: 'Dormentes',
      escada: 'Escada',
      exu: 'Exu',
      feira_nova: 'Feira Nova',
      fernando_de_noronha: 'Fernando de Noronha',
      ferreiros: 'Ferreiros',
      flores: 'Flores',
      floresta: 'Floresta',
      frei_miguelinho: 'Frei Miguelinho',
      gameleira: 'Gameleira',
      garanhuns: 'Garanhuns',
      gloria_do_goita: 'Glória do Goitá',
      goiana: 'Goiana',
      granito: 'Granito',
      gravata: 'Gravatá',
      iati: 'Iati',
      ibimirim: 'Ibimirim',
      ibirajuba: 'Ibirajuba',
      igarassu: 'Igarassu',
      iguaraci: 'Iguaraci',
      ilha_de_itamaraca: 'Ilha de Itamaracá',
      inaja: 'Inajá',
      ingazeira: 'Ingazeira',
      ipojuca: 'Ipojuca',
      ipubi: 'Ipubi',
      itacuruba: 'Itacuruba',
      itaiba: 'Itaíba',
      itambe: 'Itambé',
      itapetim: 'Itapetim',
      itapissuma: 'Itapissuma',
      itaquitinga: 'Itaquitinga',
      jaboatao_dos_guararapes: 'Jaboatão dos Guararapes',
      jaqueira: 'Jaqueira',
      jatauba: 'Jataúba',
      jatoba: 'Jatobá',
      joao_alfredo: 'João Alfredo',
      joaquim_nabuco: 'Joaquim Nabuco',
      jucati: 'Jucati',
      jupi: 'Jupi',
      jurema: 'Jurema',
      lagoa_de_itaenga: 'Lagoa de Itaenga',
      lagoa_do_carro: 'Lagoa do Carro',
      lagoa_do_ouro: 'Lagoa do Ouro',
      lagoa_dos_gatos: 'Lagoa dos Gatos',
      lagoa_grande: 'Lagoa Grande',
      lajedo: 'Lajedo',
      limoeiro: 'Limoeiro',
      macaparana: 'Macaparana',
      machados: 'Machados',
      manari: 'Manari',
      maraial: 'Maraial',
      mirandiba: 'Mirandiba',
      moreilandia: 'Moreilândia',
      moreno: 'Moreno',
      nazare_da_mata: 'Nazaré da Mata',
      olinda: 'Olinda',
      orobo: 'Orobó',
      oroco: 'Orocó',
      ouricuri: 'Ouricuri',
      palmares: 'Palmares',
      palmeirina: 'Palmeirina',
      panelas: 'Panelas',
      paranatama: 'Paranatama',
      parnamirim: 'Parnamirim',
      passira: 'Passira',
      paudalho: 'Paudalho',
      paulista: 'Paulista',
      pedra: 'Pedra',
      pesqueira: 'Pesqueira',
      petrolandia: 'Petrolândia',
      petrolina: 'Petrolina',
      pocao: 'Poção',
      pombos: 'Pombos',
      primavera: 'Primavera',
      quipapa: 'Quipapá',
      quixaba: 'Quixaba',
      recife: 'Recife',
      riacho_das_almas: 'Riacho das Almas',
      ribeirao: 'Ribeirão',
      rio_formoso: 'Rio Formoso',
      saire: 'Sairé',
      salgadinho: 'Salgadinho',
      salgueiro: 'Salgueiro',
      saloa: 'Saloá',
      sanharo: 'Sanharó',
      santa_cruz: 'Santa Cruz',
      santa_cruz_da_baixa_verde: 'Santa Cruz da Baixa Verde',
      santa_cruz_do_capibaribe: 'Santa Cruz do Capibaribe',
      santa_filomena: 'Santa Filomena',
      santa_maria_da_boa_vista: 'Santa Maria da Boa Vista',
      santa_maria_do_cambuca: 'Santa Maria do Cambucá',
      santa_terezinha: 'Santa Terezinha',
      sao_benedito_do_sul: 'São Benedito do Sul',
      sao_bento_do_una: 'São Bento do Una',
      sao_caetano: 'São Caetano',
      sao_joao: 'São João',
      sao_joaquim_do_monte: 'São Joaquim do Monte',
      sao_jose_da_coroa_grande: 'São José da Coroa Grande',
      sao_jose_do_belmonte: 'São José do Belmonte',
      sao_jose_do_egito: 'São José do Egito',
      sao_lourenco_da_mata: 'São Lourenço da Mata',
      sao_vicente_ferrer: 'São Vicente Férrer',
      serra_talhada: 'Serra Talhada',
      serrita: 'Serrita',
      sertania: 'Sertânia',
      sirinhaem: 'Sirinhaém',
      solidao: 'Solidão',
      surubim: 'Surubim',
      tabira: 'Tabira',
      tacaimbo: 'Tacaimbó',
      tacaratu: 'Tacaratu',
      tamandare: 'Tamandaré',
      taquaritinga_do_norte: 'Taquaritinga do Norte',
      terezinha: 'Terezinha',
      terra_nova: 'Terra Nova',
      timbauba: 'Timbaúba',
      toritama: 'Toritama',
      tracunhaem: 'Tracunhaém',
      trindade: 'Trindade',
      triunfo: 'Triunfo',
      tupanatinga: 'Tupanatinga',
      tuparetama: 'Tuparetama',
      venturosa: 'Venturosa',
      verdejante: 'Verdejante',
      vertente_do_lerio: 'Vertente do Lério',
      vertentes: 'Vertentes',
      vicencia: 'Vicência',
      vitoria_de_santo_antao: 'Vitória de Santo Antão',
      xexeu: 'Xexéu',
    },
    '#Estado': 'PE',
  };
  
  export default cidadesPE;