// cidadesAL.js
const cidadesAL = {
    '#empty_option': '- Selecione a Cidade -',
    '#options': {
      agua_branca: 'Água Branca',
      anadia: 'Anadia',
      arapiraca: 'Arapiraca',
      atalaia: 'Atalaia',
      barra_de_santo_antonio: 'Barra de Santo Antônio',
      barra_de_sao_miguel: 'Barra de São Miguel',
      batalha: 'Batalha',
      belem: 'Belém',
      belo_monte: 'Belo Monte',
      boca_da_mata: 'Boca da Mata',
      branquinha: 'Branquinha',
      cacimbinhas: 'Cacimbinhas',
      cajueiro: 'Cajueiro',
      campestre: 'Campestre',
      campo_alegre: 'Campo Alegre',
      campo_grande: 'Campo Grande',
      canapi: 'Canapi',
      capela: 'Capela',
      carneiros: 'Carneiros',
      cha_preta: 'Chã Preta',
      coite_do_noia: 'Coité do Noia',
      colonia_leopoldina: 'Colônia Leopoldina',
      coqueiro_seco: 'Coqueiro Seco',
      coruripe: 'Coruripe',
      craibas: 'Craíbas',
      delmiro_gouveia: 'Delmiro Gouveia',
      dois_riachos: 'Dois Riachos',
      estrela_de_alagoas: 'Estrela de Alagoas',
      feira_grande: 'Feira Grande',
      feliz_deserto: 'Feliz Deserto',
      flexeiras: 'Flexeiras',
      girau_do_ponciano: 'Girau do Ponciano',
      ibateguara: 'Ibateguara',
      igaci: 'Igaci',
      igreja_nova: 'Igreja Nova',
      inhapi: 'Inhapi',
      jacare_dos_homens: 'Jacaré dos Homens',
      jacuipe: 'Jacuípe',
      japaratinga: 'Japaratinga',
      jaramataia: 'Jaramataia',
      jequia_da_praia: 'Jequiá da Praia',
      joaquim_gomes: 'Joaquim Gomes',
      jundia: 'Jundiá',
      junqueiro: 'Junqueiro',
      lagoa_da_canoa: 'Lagoa da Canoa',
      limoeiro_de_anadia: 'Limoeiro de Anadia',
      maceio: 'Maceió',
      major_izidoro: 'Major Izidoro',
      mar_vermelho: 'Mar Vermelho',
      maragogi: 'Maragogi',
      maravilha: 'Maravilha',
      marechal_deodoro: 'Marechal Deodoro',
      maribondo: 'Maribondo',
      mata_grande: 'Mata Grande',
      matriz_de_camaragibe: 'Matriz de Camaragibe',
      messias: 'Messias',
      minador_do_negrao: 'Minador do Negrão',
      monteiropolis: 'Monteirópolis',
      murici: 'Murici',
      novo_lino: 'Novo Lino',
      olho_dagua_das_flores: 'Olho dÁgua das Flores',
      olho_dagua_do_casado: 'Olho dÁgua do Casado',
      olho_dagua_grande: 'Olho dÁgua Grande',
      olivenca: 'Olivença',
      ouro_branco: 'Ouro Branco',
      palestina: 'Palestina',
      palmeira_dos_indios: 'Palmeira dos Índios',
      pao_de_acucar: 'Pão de Açúcar',
      pariconha: 'Pariconha',
      paripueira: 'Paripueira',
      passo_de_camaragibe: 'Passo de Camaragibe',
      paulo_jacinto: 'Paulo Jacinto',
      penedo: 'Penedo',
      piacabucu: 'Piaçabuçu',
      pilar: 'Pilar',
      pindoba: 'Pindoba',
      piranhas: 'Piranhas',
      poco_das_trincheiras: 'Poço das Trincheiras',
      porto_calvo: 'Porto Calvo',
      porto_de_pedras: 'Porto de Pedras',
      porto_real_do_colegio: 'Porto Real do Colégio',
      quebrangulo: 'Quebrangulo',
      rio_largo: 'Rio Largo',
      roteiro: 'Roteiro',
      santa_luzia_do_norte: 'Santa Luzia do Norte',
      santana_do_ipanema: 'Santana do Ipanema',
      santana_do_mundau: 'Santana do Mundaú',
      sao_bras: 'São Brás',
      sao_jose_da_laje: 'São José da Laje',
      sao_jose_da_tapera: 'São José da Tapera',
      sao_luis_do_quitunde: 'São Luís do Quitunde',
      sao_miguel_dos_campos: 'São Miguel dos Campos',
      sao_miguel_dos_milagres: 'São Miguel dos Milagres',
      sao_sebastiao: 'São Sebastião',
      satuba: 'Satuba',
      senador_rui_palmeira: 'Senador Rui Palmeira',
      tanque_darca: 'Tanque dArca',
      taquarana: 'Taquarana',
      teotonio_vilela: 'Teotônio Vilela',
      traipu: 'Traipu',
      uniao_dos_palmares: 'União dos Palmares',
      vicosa: 'Viçosa',
    },
    '#Estado': 'AL',
  };
  
  export default cidadesAL;