const cidadesPI = {
    '#empty_option': '- Selecione a Cidade -',
    '#options': {
      acaua: 'Acauã',
      agricolandia: 'Agricolândia',
      agua_branca: 'Água Branca',
      alagoinha_do_piaui: 'Alagoinha do Piauí',
      alegrete_do_piaui: 'Alegrete do Piauí',
      alto_longa: 'Alto Longá',
      altos: 'Altos',
      alvorada_do_gurgueia: 'Alvorada do Gurgueia',
      amarante: 'Amarante',
      angical_do_piaui: 'Angical do Piauí',
      anisio_de_abreu: 'Anísio de Abreu',
      antonio_almeida: 'Antônio Almeida',
      aroazes: 'Aroazes',
      aroeiras_do_itaim: 'Aroeiras do Itaim',
      arraial: 'Arraial',
      assuncao_do_piaui: 'Assunção do Piauí',
      avelino_lopes: 'Avelino Lopes',
      baixa_grande_do_ribeiro: 'Baixa Grande do Ribeiro',
      barra_dalcantara: 'Barra dAlcântara',
      barras: 'Barras',
      barreiras_do_piaui: 'Barreiras do Piauí',
      barro_duro: 'Barro Duro',
      batalha: 'Batalha',
      bela_vista_do_piaui: 'Bela Vista do Piauí',
      belem_do_piaui: 'Belém do Piauí',
      beneditinos: 'Beneditinos',
      bertolinia: 'Bertolínia',
      betania_do_piaui: 'Betânia do Piauí',
      boa_hora: 'Boa Hora',
      bocaina: 'Bocaina',
      bom_jesus: 'Bom Jesus',
      bom_principio_do_piaui: 'Bom Princípio do Piauí',
      bonfim_do_piaui: 'Bonfim do Piauí',
      boqueirao_do_piaui: 'Boqueirão do Piauí',
      brasileira: 'Brasileira',
      brejo_do_piaui: 'Brejo do Piauí',
      buriti_dos_lopes: 'Buriti dos Lopes',
      buriti_dos_montes: 'Buriti dos Montes',
      cabeceiras_do_piaui: 'Cabeceiras do Piauí',
      cajazeiras_do_piaui: 'Cajazeiras do Piauí',
      cajueiro_da_praia: 'Cajueiro da Praia',
      caldeirao_grande_do_piaui: 'Caldeirão Grande do Piauí',
      campinas_do_piaui: 'Campinas do Piauí',
      campo_alegre_do_fidalgo: 'Campo Alegre do Fidalgo',
      campo_grande_do_piaui: 'Campo Grande do Piauí',
      campo_largo_do_piaui: 'Campo Largo do Piauí',
      campo_maior: 'Campo Maior',
      canavieira: 'Canavieira',
      canto_do_buriti: 'Canto do Buriti',
      capitao_de_campos: 'Capitão de Campos',
      capitao_gervasio_oliveira: 'Capitão Gervásio Oliveira',
      caracol: 'Caracol',
      caraubas_do_piaui: 'Caraúbas do Piauí',
      caridade_do_piaui: 'Caridade do Piauí',
      castelo_do_piaui: 'Castelo do Piauí',
      caxingo: 'Caxingó',
      cocal: 'Cocal',
      cocal_de_telha: 'Cocal de Telha',
      cocal_dos_alves: 'Cocal dos Alves',
      coivaras: 'Coivaras',
      colonia_do_gurgueia: 'Colônia do Gurgueia',
      colonia_do_piaui: 'Colônia do Piauí',
      conceicao_do_caninde: 'Conceição do Canindé',
      coronel_jose_dias: 'Coronel José Dias',
      corrente: 'Corrente',
      cristalandia_do_piaui: 'Cristalândia do Piauí',
      cristino_castro: 'Cristino Castro',
      curimata: 'Curimatá',
      currais: 'Currais',
      curral_novo_do_piaui: 'Curral Novo do Piauí',
      curralinhos: 'Curralinhos',
      demerval_lobao: 'Demerval Lobão',
      dirceu_arcoverde: 'Dirceu Arcoverde',
      dom_expedito_lopes: 'Dom Expedito Lopes',
      dom_inocencio: 'Dom Inocêncio',
      domingos_mourao: 'Domingos Mourão',
      elesbao_veloso: 'Elesbão Veloso',
      eliseu_martins: 'Eliseu Martins',
      esperantina: 'Esperantina',
      fartura_do_piaui: 'Fartura do Piauí',
      flores_do_piaui: 'Flores do Piauí',
      floresta_do_piaui: 'Floresta do Piauí',
      floriano: 'Floriano',
      francinopolis: 'Francinópolis',
      francisco_ayres: 'Francisco Ayres',
      francisco_macedo: 'Francisco Macedo',
      francisco_santos: 'Francisco Santos',
      fronteiras: 'Fronteiras',
      geminiano: 'Geminiano',
      gilbues: 'Gilbués',
      guadalupe: 'Guadalupe',
      guaribas: 'Guaribas',
      hugo_napoleao: 'Hugo Napoleão',
      ilha_grande: 'Ilha Grande',
      inhuma: 'Inhuma',
      ipiranga_do_piaui: 'Ipiranga do Piauí',
      isaias_coelho: 'Isaías Coelho',
      itainopolis: 'Itainópolis',
      itaueira: 'Itaueira',
      jacobina_do_piaui: 'Jacobina do Piauí',
      jaicos: 'Jaicós',
      jardim_do_mulato: 'Jardim do Mulato',
      jatoba_do_piaui: 'Jatobá do Piauí',
      jerumenha: 'Jerumenha',
      joao_costa: 'João Costa',
      joaquim_pires: 'Joaquim Pires',
      joca_marques: 'Joca Marques',
      jose_de_freitas: 'José de Freitas',
      juazeiro_do_piaui: 'Juazeiro do Piauí',
      julio_borges: 'Júlio Borges',
      jurema: 'Jurema',
      lagoa_alegre: 'Lagoa Alegre',
      lagoa_de_sao_francisco: 'Lagoa de São Francisco',
      lagoa_do_barro_do_piaui: 'Lagoa do Barro do Piauí',
      lagoa_do_piaui: 'Lagoa do Piauí',
      lagoa_do_sitio: 'Lagoa do Sítio',
      lagoinha_do_piaui: 'Lagoinha do Piauí',
      landri_sales: 'Landri Sales',
      luis_correia: 'Luís Correia',
      luzilandia: 'Luzilândia',
      madeiro: 'Madeiro',
      manoel_emidio: 'Manoel Emídio',
      marcolandia: 'Marcolândia',
      marcos_parente: 'Marcos Parente',
      massape_do_piaui: 'Massapê do Piauí',
      matias_olimpio: 'Matias Olímpio',
      miguel_alves: 'Miguel Alves',
      miguel_leao: 'Miguel Leão',
      milton_brandao: 'Milton Brandão',
      monsenhor_gil: 'Monsenhor Gil',
      monsenhor_hipolito: 'Monsenhor Hipólito',
      monte_alegre_do_piaui: 'Monte Alegre do Piauí',
      morro_cabeca_no_tempo: 'Morro Cabeça no Tempo',
      morro_do_chapeu_do_piaui: 'Morro do Chapéu do Piauí',
      murici_dos_portelas: 'Murici dos Portelas',
      nazare_do_piaui: 'Nazaré do Piauí',
      nazaria: 'Nazária',
      nossa_senhora_de_nazare: 'Nossa Senhora de Nazaré',
      nossa_senhora_dos_remedios: 'Nossa Senhora dos Remédios',
      nova_santa_rita: 'Nova Santa Rita',
      novo_oriente_do_piaui: 'Novo Oriente do Piauí',
      novo_santo_antonio: 'Novo Santo Antônio',
      oeiras: 'Oeiras',
      olho_dagua_do_piaui: 'Olho dÁgua do Piauí',
      padre_marcos: 'Padre Marcos',
      paes_landim: 'Paes Landim',
      pajeu_do_piaui: 'Pajeú do Piauí',
      palmeira_do_piaui: 'Palmeira do Piauí',
      palmeirais: 'Palmeirais',
      paqueta: 'Paquetá',
      parnagua: 'Parnaguá',
      parnaiba: 'Parnaíba',
      passagem_franca_do_piaui: 'Passagem Franca do Piauí',
      patos_do_piaui: 'Patos do Piauí',
      pau_darco_do_piaui: 'Pau dArco do Piauí',
      paulistana: 'Paulistana',
      pavussu: 'Pavussu',
      pedro_ii: 'Pedro II',
      pedro_laurentino: 'Pedro Laurentino',
      picos: 'Picos',
      pimenteiras: 'Pimenteiras',
      pio_ix: 'Pio IX',
      piracuruca: 'Piracuruca',
      piripiri: 'Piripiri',
      porto: 'Porto',
      porto_alegre_do_piaui: 'Porto Alegre do Piauí',
      prata_do_piaui: 'Prata do Piauí',
      queimada_nova: 'Queimada Nova',
      redencao_do_gurgueia: 'Redenção do Gurgueia',
      regeneracao: 'Regeneração',
      riacho_frio: 'Riacho Frio',
      ribeira_do_piaui: 'Ribeira do Piauí',
      ribeiro_goncalves: 'Ribeiro Gonçalves',
      rio_grande_do_piaui: 'Rio Grande do Piauí',
      santa_cruz_do_piaui: 'Santa Cruz do Piauí',
      santa_cruz_dos_milagres: 'Santa Cruz dos Milagres',
      santa_filomena: 'Santa Filomena',
      santa_luz: 'Santa Luz',
      santa_rosa_do_piaui: 'Santa Rosa do Piauí',
      santana_do_piaui: 'Santana do Piauí',
      santo_antonio_de_lisboa: 'Santo Antônio de Lisboa',
      santo_antonio_dos_milagres: 'Santo Antônio dos Milagres',
      santo_inacio_do_piaui: 'Santo Inácio do Piauí',
      sao_braz_do_piaui: 'São Braz do Piauí',
      sao_felix_do_piaui: 'São Félix do Piauí',
      sao_francisco_de_assis_do_piaui: 'São Francisco de Assis do Piauí',
      sao_francisco_do_piaui: 'São Francisco do Piauí',
      sao_goncalo_do_gurgueia: 'São Gonçalo do Gurgueia',
      sao_goncalo_do_piaui: 'São Gonçalo do Piauí',
      sao_joao_da_canabrava: 'São João da Canabrava',
      sao_joao_da_fronteira: 'São João da Fronteira',
      sao_joao_da_serra: 'São João da Serra',
      sao_joao_da_varjota: 'São João da Varjota',
      sao_joao_do_arraial: 'São João do Arraial',
      sao_joao_do_piaui: 'São João do Piauí',
      sao_jose_do_divino: 'São José do Divino',
      sao_jose_do_peixe: 'São José do Peixe',
      sao_jose_do_piaui: 'São José do Piauí',
      sao_juliao: 'São Julião',
      sao_lourenco_do_piaui: 'São Lourenço do Piauí',
      sao_luis_do_piaui: 'São Luís do Piauí',
      sao_miguel_da_baixa_grande: 'São Miguel da Baixa Grande',
      sao_miguel_do_fidalgo: 'São Miguel do Fidalgo',
      sao_miguel_do_tapuio: 'São Miguel do Tapuio',
      sao_pedro_do_piaui: 'São Pedro do Piauí',
      sao_raimundo_nonato: 'São Raimundo Nonato',
      sebastiao_barros: 'Sebastião Barros',
      sebastiao_leal: 'Sebastião Leal',
      sigefredo_pacheco: 'Sigefredo Pacheco',
      simoes: 'Simões',
      simplicio_mendes: 'Simplício Mendes',
      socorro_do_piaui: 'Socorro do Piauí',
      sussuapara: 'Sussuapara',
      tamboril_do_piaui: 'Tamboril do Piauí',
      tanque_do_piaui: 'Tanque do Piauí',
      teresina: 'Teresina',
      uniao: 'União',
      urucui: 'Uruçuí',
      valenca_do_piaui: 'Valença do Piauí',
      varzea_branca: 'Várzea Branca',
      varzea_grande: 'Várzea Grande',
      vera_mendes: 'Vera Mendes',
      vila_nova_do_piaui: 'Vila Nova do Piauí',
      wall_ferraz: 'Wall Ferraz',
    },
    '#Estado': 'PI',
  };
  
  export default cidadesPI;
  