// cidadesSP.jsx
const cidadesSP = {
    '#empty_option': '- Selecione a Cidade -',
    '#options': {
      adamantina: 'Adamantina',
      adolfo: 'Adolfo',
      aguai: 'Aguaí',
      aguas_da_prata: 'Águas da Prata',
      aguas_de_lindoia: 'Águas de Lindóia',
      aguas_de_santa_barbara: 'Águas de Santa Bárbara',
      aguas_de_sao_pedro: 'Águas de São Pedro',
      agudos: 'Agudos',
      alambari: 'Alambari',
      alfredo_marcondes: 'Alfredo Marcondes',
      altair: 'Altair',
      altinopolis: 'Altinópolis',
      alto_alegre: 'Alto Alegre',
      aluminio: 'Alumínio',
      alvares_florence: 'Álvares Florence',
      alvares_machado: 'Álvares Machado',
      alvaro_de_carvalho: 'Álvaro de Carvalho',
      alvinlandia: 'Alvinlândia',
      americana: 'Americana',
      americo_brasiliense: 'Américo Brasiliense',
      americo_de_campos: 'Américo de Campos',
      amparo: 'Amparo',
      analandia: 'Analândia',
      andradina: 'Andradina',
      angatuba: 'Angatuba',
      anhembi: 'Anhembi',
      anhumas: 'Anhumas',
      aparecida: 'Aparecida',
      aparecida_doeste: 'Aparecida dOeste',
      apiai: 'Apiaí',
      aracariguama: 'Araçariguama',
      aracatuba: 'Araçatuba',
      aracoiaba_da_serra: 'Araçoiaba da Serra',
      aramina: 'Aramina',
      arandu: 'Arandu',
      arapei: 'Arapeí',
      araraquara: 'Araraquara',
      araras: 'Araras',
      arco_iris: 'Arco-Íris',
      arealva: 'Arealva',
      areias: 'Areias',
      areiopolis: 'Areiópolis',
      ariranha: 'Ariranha',
      artur_nogueira: 'Artur Nogueira',
      aruja: 'Arujá',
      aspasia: 'Aspásia',
      assis: 'Assis',
      atibaia: 'Atibaia',
      auriflama: 'Auriflama',
      avai: 'Avaí',
      avanhandava: 'Avanhandava',
      avare: 'Avaré',
      bady_bassitt: 'Bady Bassitt',
      balbinos: 'Balbinos',
      balsamo: 'Bálsamo',
      bananal: 'Bananal',
      barao_de_antonina: 'Barão de Antonina',
      barbosa: 'Barbosa',
      bariri: 'Bariri',
      barra_bonita: 'Barra Bonita',
      barra_do_chapeu: 'Barra do Chapéu',
      barra_do_turvo: 'Barra do Turvo',
      barretos: 'Barretos',
      barrinha: 'Barrinha',
      barueri: 'Barueri',
      bastos: 'Bastos',
      batatais: 'Batatais',
      bauru: 'Bauru',
      bebedouro: 'Bebedouro',
      bento_de_abreu: 'Bento de Abreu',
      bernardino_de_campos: 'Bernardino de Campos',
      bertioga: 'Bertioga',
      bilac: 'Bilac',
      birigui: 'Birigui',
      biritiba_mirim: 'Biritiba Mirim',
      boa_esperanca_do_sul: 'Boa Esperança do Sul',
      bocaina: 'Bocaina',
      bofete: 'Bofete',
      boituva: 'Boituva',
      bom_jesus_dos_perdoes: 'Bom Jesus dos Perdões',
      bom_sucesso_de_itarare: 'Bom Sucesso de Itararé',
      bora: 'Borá',
      boraceia: 'Boraceia',
      borborema: 'Borborema',
      borebi: 'Borebi',
      botucatu: 'Botucatu',
      braganca_paulista: 'Bragança Paulista',
      brauna: 'Braúna',
      brejo_alegre: 'Brejo Alegre',
      brodowski: 'Brodowski',
      brotas: 'Brotas',
      buri: 'Buri',
      buritama: 'Buritama',
      buritizal: 'Buritizal',
      cabralia_paulista: 'Cabrália Paulista',
      cabreuva: 'Cabreúva',
      cacapava: 'Caçapava',
      cachoeira_paulista: 'Cachoeira Paulista',
      caconde: 'Caconde',
      cafelandia: 'Cafelândia',
      caiabu: 'Caiabu',
      caieiras: 'Caieiras',
      caiua: 'Caiuá',
      cajamar: 'Cajamar',
      cajati: 'Cajati',
      cajobi: 'Cajobi',
      cajuru: 'Cajuru',
      campina_do_monte_alegre: 'Campina do Monte Alegre',
      campinas: 'Campinas',
      campo_limpo_paulista: 'Campo Limpo Paulista',
      campos_do_jordao: 'Campos do Jordão',
      campos_novos_paulista: 'Campos Novos Paulista',
      cananeia: 'Cananéia',
      canas: 'Canas',
      candido_mota: 'Cândido Mota',
      candido_rodrigues: 'Cândido Rodrigues',
      canitar: 'Canitar',
      capao_bonito: 'Capão Bonito',
      capela_do_alto: 'Capela do Alto',
      capivari: 'Capivari',
      caraguatatuba: 'Caraguatatuba',
      carapicuiba: 'Carapicuíba',
      cardoso: 'Cardoso',
      casa_branca: 'Casa Branca',
      cassia_dos_coqueiros: 'Cássia dos Coqueiros',
      castilho: 'Castilho',
      catanduva: 'Catanduva',
      catigua: 'Catiguá',
      cedral: 'Cedral',
      cerqueira_cesar: 'Cerqueira César',
      cerquilho: 'Cerquilho',
      cesario_lange: 'Cesário Lange',
      charqueada: 'Charqueada',
      chavantes: 'Chavantes',
      clementina: 'Clementina',
      colina: 'Colina',
      colombia: 'Colômbia',
      conchal: 'Conchal',
      conchas: 'Conchas',
      cordeiropolis: 'Cordeirópolis',
      coroados: 'Coroados',
      coronel_macedo: 'Coronel Macedo',
      corumbatai: 'Corumbataí',
      cosmopolis: 'Cosmópolis',
      cosmorama: 'Cosmorama',
      cotia: 'Cotia',
      cravinhos: 'Cravinhos',
      cristais_paulista: 'Cristais Paulista',
      cruzalia: 'Cruzália',
      cruzeiro: 'Cruzeiro',
      cubatao: 'Cubatão',
      cunha: 'Cunha',
      descalvado: 'Descalvado',
      diadema: 'Diadema',
      dirce_reis: 'Dirce Reis',
      divinolandia: 'Divinolândia',
      dobrada: 'Dobrada',
      dois_corregos: 'Dois Córregos',
      dolcinopolis: 'Dolcinópolis',
      dourado: 'Dourado',
      dracena: 'Dracena',
      duartina: 'Duartina',
      dumont: 'Dumont',
      echapora: 'Echaporã',
      eldorado: 'Eldorado',
      elias_fausto: 'Elias Fausto',
      elisiario: 'Elisiário',
      embauba: 'Embaúba',
      embu_das_artes: 'Embu das Artes',
      embu_guacu: 'Embu-Guaçu',
      emilianopolis: 'Emilianópolis',
      engenheiro_coelho: 'Engenheiro Coelho',
      espirito_santo_do_pinhal: 'Espírito Santo do Pinhal',
      espirito_santo_do_turvo: 'Espírito Santo do Turvo',
      estiva_gerbi: 'Estiva Gerbi',
      estrela_do_norte: 'Estrela do Norte',
      estrela_doeste: 'Estrela dOeste',
      euclides_da_cunha_paulista: 'Euclides da Cunha Paulista',
      fartura: 'Fartura',
      fernando_prestes: 'Fernando Prestes',
      fernandopolis: 'Fernandópolis',
      fernao: 'Fernão',
      ferraz_de_vasconcelos: 'Ferraz de Vasconcelos',
      flora_rica: 'Flora Rica',
      floreal: 'Floreal',
      florida_paulista: 'Flórida Paulista',
      florinea: 'Florínea',
      franca: 'Franca',
      francisco_morato: 'Francisco Morato',
      franco_da_rocha: 'Franco da Rocha',
      gabriel_monteiro: 'Gabriel Monteiro',
      galia: 'Gália',
      garca: 'Garça',
      gastao_vidigal: 'Gastão Vidigal',
      gaviao_peixoto: 'Gavião Peixoto',
      general_salgado: 'General Salgado',
      getulina: 'Getulina',
      glicerio: 'Glicério',
      guaicara: 'Guaiçara',
      guaimbe: 'Guaimbê',
      guaira: 'Guaíra',
      guapiacu: 'Guapiaçu',
      guapiara: 'Guapiara',
      guara: 'Guará',
      guaracai: 'Guaraçaí',
      guaraci: 'Guaraci',
      guarani_doeste: 'Guarani dOeste',
      guaranta: 'Guarantã',
      guararapes: 'Guararapes',
      guararema: 'Guararema',
      guaratingueta: 'Guaratinguetá',
      guarei: 'Guareí',
      guariba: 'Guariba',
      guaruja: 'Guarujá',
      guarulhos: 'Guarulhos',
      guatapara: 'Guatapará',
      guzolandia: 'Guzolândia',
      herculandia: 'Herculândia',
      holambra: 'Holambra',
      hortolandia: 'Hortolândia',
      iacanga: 'Iacanga',
      iacri: 'Iacri',
      iaras: 'Iaras',
      ibate: 'Ibaté',
      ibira: 'Ibirá',
      ibirarema: 'Ibirarema',
      ibitinga: 'Ibitinga',
      ibiuna: 'Ibiúna',
      icem: 'Icém',
      iepe: 'Iepê',
      igaracu_do_tiete: 'Igaraçu do Tietê',
      igarapava: 'Igarapava',
      igarata: 'Igaratá',
      iguape: 'Iguape',
      ilha_comprida: 'Ilha Comprida',
      ilha_solteira: 'Ilha Solteira',
      ilhabela: 'Ilhabela',
      indaiatuba: 'Indaiatuba',
      indiana: 'Indiana',
      indiapora: 'Indiaporã',
      inubia_paulista: 'Inúbia Paulista',
      ipaussu: 'Ipaussu',
      ipero: 'Iperó',
      ipeuna: 'Ipeúna',
      ipigua: 'Ipiguá',
      iporanga: 'Iporanga',
      ipua: 'Ipuã',
      iracemapolis: 'Iracemápolis',
      irapua: 'Irapuã',
      irapuru: 'Irapuru',
      itabera: 'Itaberá',
      itai: 'Itaí',
      itajobi: 'Itajobi',
      itaju: 'Itaju',
      itanhaem: 'Itanhaém',
      itaoca: 'Itaoca',
      itapecerica_da_serra: 'Itapecerica da Serra',
      itapetininga: 'Itapetininga',
      itapeva: 'Itapeva',
      itapevi: 'Itapevi',
      itapira: 'Itapira',
      itapirapua_paulista: 'Itapirapuã Paulista',
      itapolis: 'Itápolis',
      itaporanga: 'Itaporanga',
      itapui: 'Itapuí',
      itapura: 'Itapura',
      itaquaquecetuba: 'Itaquaquecetuba',
      itarare: 'Itararé',
      itariri: 'Itariri',
      itatiba: 'Itatiba',
      itatinga: 'Itatinga',
      itirapina: 'Itirapina',
      itirapua: 'Itirapuã',
      itobi: 'Itobi',
      itu: 'Itu',
      itupeva: 'Itupeva',
      ituverava: 'Ituverava',
      jaborandi: 'Jaborandi',
      jaboticabal: 'Jaboticabal',
      jacarei: 'Jacareí',
      jaci: 'Jaci',
      jacupiranga: 'Jacupiranga',
      jaguariuna: 'Jaguariúna',
      jales: 'Jales',
      jambeiro: 'Jambeiro',
      jandira: 'Jandira',
      jardinopolis: 'Jardinópolis',
      jarinu: 'Jarinu',
      jau: 'Jaú',
      jeriquara: 'Jeriquara',
      joanopolis: 'Joanópolis',
      joao_ramalho: 'João Ramalho',
      jose_bonifacio: 'José Bonifácio',
      julio_mesquita: 'Júlio Mesquita',
      jumirim: 'Jumirim',
      jundiai: 'Jundiaí',
      junqueiropolis: 'Junqueirópolis',
      juquia: 'Juquiá',
      juquitiba: 'Juquitiba',
      lagoinha: 'Lagoinha',
      laranjal_paulista: 'Laranjal Paulista',
      lavinia: 'Lavínia',
      lavrinhas: 'Lavrinhas',
      leme: 'Leme',
      lencois_paulista: 'Lençóis Paulista',
      limeira: 'Limeira',
      lindoia: 'Lindoia',
      lins: 'Lins',
      lorena: 'Lorena',
      lourdes: 'Lourdes',
      louveira: 'Louveira',
      lucelia: 'Lucélia',
      lucianopolis: 'Lucianópolis',
      luiz_antonio: 'Luiz Antônio',
      luiziania: 'Luiziânia',
      lupercio: 'Lupércio',
      lutecia: 'Lutécia',
      macatuba: 'Macatuba',
      macaubal: 'Macaubal',
      macedonia: 'Macedônia',
      magda: 'Magda',
      mairinque: 'Mairinque',
      mairipora: 'Mairiporã',
      manduri: 'Manduri',
      maraba_paulista: 'Marabá Paulista',
      maracai: 'Maracaí',
      marapoama: 'Marapoama',
      mariapolis: 'Mariápolis',
      marilia: 'Marília',
      marinopolis: 'Marinópolis',
      martinopolis: 'Martinópolis',
      matao: 'Matão',
      maua: 'Mauá',
      mendonca: 'Mendonça',
      meridiano: 'Meridiano',
      mesopolis: 'Mesópolis',
      miguelopolis: 'Miguelópolis',
      mineiros_do_tiete: 'Mineiros do Tietê',
      mira_estrela: 'Mira Estrela',
      miracatu: 'Miracatu',
      mirandopolis: 'Mirandópolis',
      mirante_do_paranapanema: 'Mirante do Paranapanema',
      mirassol: 'Mirassol',
      mirassolandia: 'Mirassolândia',
      mococa: 'Mococa',
      mogi_das_cruzes: 'Mogi das Cruzes',
      mogi_guacu: 'Mogi Guaçu',
      mogi_mirim: 'Mogi Mirim',
      mombuca: 'Mombuca',
      moncoes: 'Monções',
      mongagua: 'Mongaguá',
      monte_alegre_do_sul: 'Monte Alegre do Sul',
      monte_alto: 'Monte Alto',
      monte_aprazivel: 'Monte Aprazível',
      monte_azul_paulista: 'Monte Azul Paulista',
      monte_castelo: 'Monte Castelo',
      monte_mor: 'Monte Mor',
      monteiro_lobato: 'Monteiro Lobato',
      morro_agudo: 'Morro Agudo',
      morungaba: 'Morungaba',
      motuca: 'Motuca',
      murutinga_do_sul: 'Murutinga do Sul',
      nantes: 'Nantes',
      narandiba: 'Narandiba',
      natividade_da_serra: 'Natividade da Serra',
      nazare_paulista: 'Nazaré Paulista',
      neves_paulista: 'Neves Paulista',
      nhandeara: 'Nhandeara',
      nipoa: 'Nipoã',
      nova_alianca: 'Nova Aliança',
      nova_campina: 'Nova Campina',
      nova_canaa_paulista: 'Nova Canaã Paulista',
      nova_castilho: 'Nova Castilho',
      nova_europa: 'Nova Europa',
      nova_granada: 'Nova Granada',
      nova_guataporanga: 'Nova Guataporanga',
      nova_independencia: 'Nova Independência',
      nova_luzitania: 'Nova Luzitânia',
      nova_odessa: 'Nova Odessa',
      novais: 'Novais',
      novo_horizonte: 'Novo Horizonte',
      nuporanga: 'Nuporanga',
      ocaucu: 'Ocauçu',
      oleo: 'Óleo',
      olimpia: 'Olímpia',
      onda_verde: 'Onda Verde',
      oriente: 'Oriente',
      orindiuva: 'Orindiúva',
      orlandia: 'Orlândia',
      osasco: 'Osasco',
      oscar_bressane: 'Oscar Bressane',
      osvaldo_cruz: 'Osvaldo Cruz',
      ourinhos: 'Ourinhos',
      ouro_verde: 'Ouro Verde',
      ouroeste: 'Ouroeste',
      pacaembu: 'Pacaembu',
      palestina: 'Palestina',
      palmares_paulista: 'Palmares Paulista',
      palmeira_doeste: 'Palmeira dOeste',
      palmital: 'Palmital',
      panorama: 'Panorama',
      paraguacu_paulista: 'Paraguaçu Paulista',
      paraibuna: 'Paraibuna',
      paraiso: 'Paraíso',
      paranapanema: 'Paranapanema',
      paranapua: 'Paranapuã',
      parapua: 'Parapuã',
      pardinho: 'Pardinho',
      pariquera_acu: 'Pariquera-Açu',
      parisi: 'Parisi',
      patrocinio_paulista: 'Patrocínio Paulista',
      pauliceia: 'Paulicéia',
      paulinia: 'Paulínia',
      paulistania: 'Paulistânia',
      paulo_de_faria: 'Paulo de Faria',
      pederneiras: 'Pederneiras',
      pedra_bela: 'Pedra Bela',
      pedranopolis: 'Pedranópolis',
      pedregulho: 'Pedregulho',
      pedreira: 'Pedreira',
      pedrinhas_paulista: 'Pedrinhas Paulista',
      pedro_de_toledo: 'Pedro de Toledo',
      penapolis: 'Penápolis',
      pereira_barreto: 'Pereira Barreto',
      pereiras: 'Pereiras',
      peruibe: 'Peruíbe',
      piacatu: 'Piacatu',
      piedade: 'Piedade',
      pilar_do_sul: 'Pilar do Sul',
      pindamonhangaba: 'Pindamonhangaba',
      pindorama: 'Pindorama',
      pinhalzinho: 'Pinhalzinho',
      piquerobi: 'Piquerobi',
      piquete: 'Piquete',
      piracaia: 'Piracaia',
      piracicaba: 'Piracicaba',
      piraju: 'Piraju',
      pirajui: 'Pirajuí',
      pirangi: 'Pirangi',
      pirapora_do_bom_jesus: 'Pirapora do Bom Jesus',
      pirapozinho: 'Pirapozinho',
      pirassununga: 'Pirassununga',
      piratininga: 'Piratininga',
      pitangueiras: 'Pitangueiras',
      planalto: 'Planalto',
      platina: 'Platina',
      poa: 'Poá',
      poloni: 'Poloni',
      pompeia: 'Pompeia',
      pongai: 'Pongaí',
      pontal: 'Pontal',
      pontalinda: 'Pontalinda',
      pontes_gestal: 'Pontes Gestal',
      populina: 'Populina',
      porangaba: 'Porangaba',
      porto_feliz: 'Porto Feliz',
      porto_ferreira: 'Porto Ferreira',
      potim: 'Potim',
      potirendaba: 'Potirendaba',
      pracinha: 'Pracinha',
      pradopolis: 'Pradópolis',
      praia_grande: 'Praia Grande',
      pratania: 'Pratânia',
      presidente_alves: 'Presidente Alves',
      presidente_bernardes: 'Presidente Bernardes',
      presidente_epitacio: 'Presidente Epitácio',
      presidente_prudente: 'Presidente Prudente',
      presidente_venceslau: 'Presidente Venceslau',
      promissao: 'Promissão',
      quadra: 'Quadra',
      quata: 'Quatá',
      queiroz: 'Queiroz',
      queluz: 'Queluz',
      quintana: 'Quintana',
      rafard: 'Rafard',
      rancharia: 'Rancharia',
      redencao_da_serra: 'Redenção da Serra',
      regente_feijo: 'Regente Feijó',
      reginopolis: 'Reginópolis',
      registro: 'Registro',
      restinga: 'Restinga',
      ribeira: 'Ribeira',
      ribeirao_bonito: 'Ribeirão Bonito',
      ribeirao_branco: 'Ribeirão Branco',
      ribeirao_corrente: 'Ribeirão Corrente',
      ribeirao_do_sul: 'Ribeirão do Sul',
      ribeirao_dos_indios: 'Ribeirão dos Índios',
      ribeirao_grande: 'Ribeirão Grande',
      ribeirao_pires: 'Ribeirão Pires',
      ribeirao_preto: 'Ribeirão Preto',
      rifaina: 'Rifaina',
      rincao: 'Rincão',
      rinopolis: 'Rinópolis',
      rio_claro: 'Rio Claro',
      rio_das_pedras: 'Rio das Pedras',
      rio_grande_da_serra: 'Rio Grande da Serra',
      riolandia: 'Riolândia',
      riversul: 'Riversul',
      rosana: 'Rosana',
      roseira: 'Roseira',
      rubiacea: 'Rubiácea',
      rubineia: 'Rubinéia',
      sabino: 'Sabino',
      sagres: 'Sagres',
      sales: 'Sales',
      sales_oliveira: 'Sales Oliveira',
      salesopolis: 'Salesópolis',
      salmourao: 'Salmourão',
      saltinho: 'Saltinho',
      salto: 'Salto',
      salto_de_pirapora: 'Salto de Pirapora',
      salto_grande: 'Salto Grande',
      sandovalina: 'Sandovalina',
      santa_adelia: 'Santa Adélia',
      santa_albertina: 'Santa Albertina',
      santa_barbara_doeste: 'Santa Bárbara dOeste',
      santa_branca: 'Santa Branca',
      santa_clara_doeste: 'Santa Clara dOeste',
      santa_cruz_da_conceicao: 'Santa Cruz da Conceição',
      santa_cruz_da_esperanca: 'Santa Cruz da Esperança',
      santa_cruz_das_palmeiras: 'Santa Cruz das Palmeiras',
      santa_cruz_do_rio_pardo: 'Santa Cruz do Rio Pardo',
      santa_ernestina: 'Santa Ernestina',
      santa_fe_do_sul: 'Santa Fé do Sul',
      santa_gertrudes: 'Santa Gertrudes',
      santa_isabel: 'Santa Isabel',
      santa_lucia: 'Santa Lúcia',
      santa_maria_da_serra: 'Santa Maria da Serra',
      santa_mercedes: 'Santa Mercedes',
      santa_rita_do_passa_quatro: 'Santa Rita do Passa Quatro',
      santa_rita_doeste: 'Santa Rita dOeste',
      santa_rosa_de_viterbo: 'Santa Rosa de Viterbo',
      santa_salete: 'Santa Salete',
      santana_da_ponte_pensa: 'Santana da Ponte Pensa',
      santana_de_parnaiba: 'Santana de Parnaíba',
      santo_anastacio: 'Santo Anastácio',
      santo_andre: 'Santo André',
      santo_antonio_da_alegria: 'Santo Antônio da Alegria',
      santo_antonio_de_posse: 'Santo Antônio de Posse',
      santo_antonio_do_aracangua: 'Santo Antônio do Aracanguá',
      santo_antonio_do_jardim: 'Santo Antônio do Jardim',
      santo_antonio_do_pinhal: 'Santo Antônio do Pinhal',
      santo_expedito: 'Santo Expedito',
      santopolis_do_aguapei: 'Santópolis do Aguapeí',
      santos: 'Santos',
      sao_bento_do_sapucai: 'São Bento do Sapucaí',
      sao_bernardo_do_campo: 'São Bernardo do Campo',
      sao_caetano_do_sul: 'São Caetano do Sul',
      sao_carlos: 'São Carlos',
      sao_francisco: 'São Francisco',
      sao_joao_da_boa_vista: 'São João da Boa Vista',
      sao_joao_das_duas_pontes: 'São João das Duas Pontes',
      sao_joao_de_iracema: 'São João de Iracema',
      sao_joao_do_pau_dalho: 'São João do Pau-dAlho',
      sao_joaquim_da_barra: 'São Joaquim da Barra',
      sao_jose_da_bela_vista: 'São José da Bela Vista',
      sao_jose_do_barreiro: 'São José do Barreiro',
      sao_jose_do_rio_pardo: 'São José do Rio Pardo',
      sao_jose_do_rio_preto: 'São José do Rio Preto',
      sao_jose_dos_campos: 'São José dos Campos',
      sao_lourenco_da_serra: 'São Lourenço da Serra',
      sao_luiz_do_paraitinga: 'São Luiz do Paraitinga',
      sao_manuel: 'São Manuel',
      sao_miguel_arcanjo: 'São Miguel Arcanjo',
      sao_paulo: 'São Paulo',
      sao_pedro: 'São Pedro',
      sao_pedro_do_turvo: 'São Pedro do Turvo',
      sao_roque: 'São Roque',
      sao_sebastiao: 'São Sebastião',
      sao_sebastiao_da_grama: 'São Sebastião da Grama',
      sao_simao: 'São Simão',
      sao_vicente: 'São Vicente',
      sarapui: 'Sarapuí',
      sarutaia: 'Sarutaiá',
      sebastianopolis_do_sul: 'Sebastianópolis do Sul',
      serra_azul: 'Serra Azul',
      serra_negra: 'Serra Negra',
      serrana: 'Serrana',
      sertaozinho: 'Sertãozinho',
      sete_barras: 'Sete Barras',
      severinia: 'Severínia',
      silveiras: 'Silveiras',
      socorro: 'Socorro',
      sorocaba: 'Sorocaba',
      sud_mennucci: 'Sud Mennucci',
      sumare: 'Sumaré',
      suzanapolis: 'Suzanápolis',
      suzano: 'Suzano',
      tabapua: 'Tabapuã',
      tabatinga: 'Tabatinga',
      taboao_da_serra: 'Taboão da Serra',
      taciba: 'Taciba',
      taguai: 'Taguaí',
      taiacu: 'Taiaçu',
      taiuva: 'Taiúva',
      tambau: 'Tambaú',
      tanabi: 'Tanabi',
      tapirai: 'Tapiraí',
      tapiratiba: 'Tapiratiba',
      taquaral: 'Taquaral',
      taquaritinga: 'Taquaritinga',
      taquarituba: 'Taquarituba',
      taquarivai: 'Taquarivaí',
      tarabai: 'Tarabai',
      taruma: 'Tarumã',
      tatui: 'Tatuí',
      taubate: 'Taubaté',
      tejupa: 'Tejupá',
      teodoro_sampaio: 'Teodoro Sampaio',
      terra_roxa: 'Terra Roxa',
      tiete: 'Tietê',
      timburi: 'Timburi',
      torre_de_pedra: 'Torre de Pedra',
      torrinha: 'Torrinha',
      trabiju: 'Trabiju',
      tremembe: 'Tremembé',
      tres_fronteiras: 'Três Fronteiras',
      tuiuti: 'Tuiuti',
      tupa: 'Tupã',
      tupi_paulista: 'Tupi Paulista',
      turiuba: 'Turiúba',
      turmalina: 'Turmalina',
      ubarana: 'Ubarana',
      ubatuba: 'Ubatuba',
      ubirajara: 'Ubirajara',
      uchoa: 'Uchoa',
      uniao_paulista: 'União Paulista',
      urania: 'Urânia',
      uru: 'Uru',
      urupes: 'Urupês',
      valentim_gentil: 'Valentim Gentil',
      valinhos: 'Valinhos',
      valparaiso: 'Valparaíso',
      vargem: 'Vargem',
      vargem_grande_do_sul: 'Vargem Grande do Sul',
      vargem_grande_paulista: 'Vargem Grande Paulista',
      varzea_paulista: 'Várzea Paulista',
      vera_cruz: 'Vera Cruz',
      vinhedo: 'Vinhedo',
      viradouro: 'Viradouro',
      vista_alegre_do_alto: 'Vista Alegre do Alto',
      vitoria_brasil: 'Vitória Brasil',
      votorantim: 'Votorantim',
      votuporanga: 'Votuporanga',
      zacarias: 'Zacarias',
    },
    '#Estado': 'SP',
  };
  
  export default cidadesSP;