const cidadesMA = {
    '#empty_option': '- Selecione a Cidade -',
    '#options': {
      acailandia: 'Açailândia',
      afonso_cunha: 'Afonso Cunha',
      agua_doce_do_maranhao: 'Água Doce do Maranhão',
      alcantara: 'Alcântara',
      aldeias_altas: 'Aldeias Altas',
      altamira_do_maranhao: 'Altamira do Maranhão',
      alto_alegre_do_maranhao: 'Alto Alegre do Maranhão',
      alto_alegre_do_pindare: 'Alto Alegre do Pindaré',
      alto_parnaiba: 'Alto Parnaíba',
      amapa_do_maranhao: 'Amapá do Maranhão',
      amarante_do_maranhao: 'Amarante do Maranhão',
      anajatuba: 'Anajatuba',
      anapurus: 'Anapurus',
      apicum_acu: 'Apicum-Açu',
      araguana: 'Araguanã',
      araioses: 'Araioses',
      arame: 'Arame',
      arari: 'Arari',
      axixa: 'Axixá',
      bacabal: 'Bacabal',
      bacabeira: 'Bacabeira',
      bacuri: 'Bacuri',
      bacurituba: 'Bacurituba',
      balsas: 'Balsas',
      barao_de_grajau: 'Barão de Grajaú',
      barra_do_corda: 'Barra do Corda',
      barreirinhas: 'Barreirinhas',
      bela_vista_do_maranhao: 'Bela Vista do Maranhão',
      belagua: 'Belágua',
      benedito_leite: 'Benedito Leite',
      bequimao: 'Bequimão',
      bernardo_do_mearim: 'Bernardo do Mearim',
      boa_vista_do_gurupi: 'Boa Vista do Gurupi',
      bom_jardim: 'Bom Jardim',
      bom_jesus_das_selvas: 'Bom Jesus das Selvas',
      bom_lugar: 'Bom Lugar',
      brejo: 'Brejo',
      brejo_de_areia: 'Brejo de Areia',
      buriti: 'Buriti',
      buriti_bravo: 'Buriti Bravo',
      buriticupu: 'Buriticupu',
      buritirana: 'Buritirana',
      cachoeira_grande: 'Cachoeira Grande',
      cajapio: 'Cajapió',
      cajari: 'Cajari',
      campestre_do_maranhao: 'Campestre do Maranhão',
      candido_mendes: 'Cândido Mendes',
      cantanhede: 'Cantanhede',
      capinzal_do_norte: 'Capinzal do Norte',
      carolina: 'Carolina',
      carutapera: 'Carutapera',
      caxias: 'Caxias',
      cedral: 'Cedral',
      central_do_maranhao: 'Central do Maranhão',
      centro_do_guilherme: 'Centro do Guilherme',
      centro_novo_do_maranhao: 'Centro Novo do Maranhão',
      chapadinha: 'Chapadinha',
      cidelandia: 'Cidelândia',
      codo: 'Codó',
      coelho_neto: 'Coelho Neto',
      colinas: 'Colinas',
      conceicao_do_lago_acu: 'Conceição do Lago Açu',
      coroata: 'Coroatá',
      cururupu: 'Cururupu',
      davinopolis: 'Davinópolis',
      dom_pedro: 'Dom Pedro',
      duque_bacelar: 'Duque Bacelar',
      esperantinopolis: 'Esperantinópolis',
      estreito: 'Estreito',
      feira_nova_do_maranhao: 'Feira Nova do Maranhão',
      fernando_falcao: 'Fernando Falcão',
      formosa_da_serra_negra: 'Formosa da Serra Negra',
      fortaleza_dos_nogueiras: 'Fortaleza dos Nogueiras',
      fortuna: 'Fortuna',
      godofredo_viana: 'Godofredo Viana',
      goncalves_dias: 'Gonçalves Dias',
      governador_archer: 'Governador Archer',
      governador_edison_lobao: 'Governador Edison Lobão',
      governador_eugenio_barros: 'Governador Eugênio Barros',
      governador_luiz_rocha: 'Governador Luiz Rocha',
      governador_newton_bello: 'Governador Newton Bello',
      governador_nunes_freire: 'Governador Nunes Freire',
      graca_aranha: 'Graça Aranha',
      grajau: 'Grajaú',
      guimaraes: 'Guimarães',
      humberto_de_campos: 'Humberto de Campos',
      icatu: 'Icatu',
      igarape_do_meio: 'Igarapé do Meio',
      igarape_grande: 'Igarapé Grande',
      imperatriz: 'Imperatriz',
      itaipava_do_grajau: 'Itaipava do Grajaú',
      itapecuru_mirim: 'Itapecuru-Mirim',
      itinga_do_maranhao: 'Itinga do Maranhão',
      jatoba: 'Jatobá',
      jenipapo_dos_vieiras: 'Jenipapo dos Vieiras',
      joao_lisboa: 'João Lisboa',
      joselandia: 'Joselândia',
      junco_do_maranhao: 'Junco do Maranhão',
      lago_da_pedra: 'Lago da Pedra',
      lago_do_junco: 'Lago do Junco',
      lago_dos_rodrigues: 'Lago dos Rodrigues',
      lago_verde: 'Lago Verde',
      lagoa_do_mato: 'Lagoa do Mato',
      lagoa_grande_do_maranhao: 'Lagoa Grande do Maranhão',
      lajeado_novo: 'Lajeado Novo',
      lima_campos: 'Lima Campos',
      loreto: 'Loreto',
      luis_domingues: 'Luís Domingues',
      magalhaes_de_almeida: 'Magalhães de Almeida',
      maracacume: 'Maracaçumé',
      maraja_do_sena: 'Marajá do Sena',
      maranhaozinho: 'Maranhãozinho',
      mata_roma: 'Mata Roma',
      matinha: 'Matinha',
      matoes: 'Matões',
      matoes_do_norte: 'Matões do Norte',
      milagres_do_maranhao: 'Milagres do Maranhão',
      mirador: 'Mirador',
      miranda_do_norte: 'Miranda do Norte',
      mirinzal: 'Mirinzal',
      moncao: 'Monção',
      montes_altos: 'Montes Altos',
      morros: 'Morros',
      nina_rodrigues: 'Nina Rodrigues',
      nova_colinas: 'Nova Colinas',
      nova_iorque: 'Nova Iorque',
      nova_olinda_do_maranhao: 'Nova Olinda do Maranhão',
      olho_dagua_das_cunhas: 'Olho dÁgua das Cunhãs',
      olinda_nova_do_maranhao: 'Olinda Nova do Maranhão',
      paco_do_lumiar: 'Paço do Lumiar',
      palmeirandia: 'Palmeirândia',
      paraibano: 'Paraibano',
      parnarama: 'Parnarama',
      passagem_franca: 'Passagem Franca',
      pastos_bons: 'Pastos Bons',
      paulino_neves: 'Paulino Neves',
      paulo_ramos: 'Paulo Ramos',
      pedreiras: 'Pedreiras',
      pedro_do_rosario: 'Pedro do Rosário',
      penalva: 'Penalva',
      peri_mirim: 'Peri Mirim',
      peritoro: 'Peritoró',
      pindare_mirim: 'Pindaré-Mirim',
      pinheiro: 'Pinheiro',
      pio_xii: 'Pio XII',
      pirapemas: 'Pirapemas',
      pocao_de_pedras: 'Poção de Pedras',
      porto_franco: 'Porto Franco',
      porto_rico_do_maranhao: 'Porto Rico do Maranhão',
      presidente_dutra: 'Presidente Dutra',
      presidente_juscelino: 'Presidente Juscelino',
      presidente_medici: 'Presidente Médici',
      presidente_sarney: 'Presidente Sarney',
      presidente_vargas: 'Presidente Vargas',
      primeira_cruz: 'Primeira Cruz',
      raposa: 'Raposa',
      riachao: 'Riachão',
      ribamar_fiquene: 'Ribamar Fiquene',
      rosario: 'Rosário',
      sambaiba: 'Sambaíba',
      santa_filomena_do_maranhao: 'Santa Filomena do Maranhão',
      santa_helena: 'Santa Helena',
      santa_ines: 'Santa Inês',
      santa_luzia: 'Santa Luzia',
      santa_luzia_do_parua: 'Santa Luzia do Paruá',
      santa_quiteria_do_maranhao: 'Santa Quitéria do Maranhão',
      santa_rita: 'Santa Rita',
      santana_do_maranhao: 'Santana do Maranhão',
      santo_amaro_do_maranhao: 'Santo Amaro do Maranhão',
      santo_antonio_dos_lopes: 'Santo Antônio dos Lopes',
      sao_benedito_do_rio_preto: 'São Benedito do Rio Preto',
      sao_bento: 'São Bento',
      sao_bernardo: 'São Bernardo',
      sao_domingos_do_azeitao: 'São Domingos do Azeitão',
      sao_domingos_do_maranhao: 'São Domingos do Maranhão',
      sao_felix_de_balsas: 'São Félix de Balsas',
      sao_francisco_do_brejao: 'São Francisco do Brejão',
      sao_francisco_do_maranhao: 'São Francisco do Maranhão',
      sao_joao_batista: 'São João Batista',
      sao_joao_do_caru: 'São João do Caru',
      sao_joao_do_paraiso: 'São João do Paraíso',
      sao_joao_do_soter: 'São João do Soter',
      sao_joao_dos_patos: 'São João dos Patos',
      sao_jose_de_ribamar: 'São José de Ribamar',
      sao_jose_dos_basilios: 'São José dos Basílios',
      sao_luis: 'São Luís',
      sao_luis_gonzaga_do_maranhao: 'São Luís Gonzaga do Maranhão',
      sao_mateus_do_maranhao: 'São Mateus do Maranhão',
      sao_pedro_da_agua_branca: 'São Pedro da Água Branca',
      sao_pedro_dos_crentes: 'São Pedro dos Crentes',
      sao_raimundo_das_mangabeiras: 'São Raimundo das Mangabeiras',
      sao_raimundo_do_doca_bezerra: 'São Raimundo do Doca Bezerra',
      sao_roberto: 'São Roberto',
      sao_vicente_ferrer: 'São Vicente Ferrer',
      satubinha: 'Satubinha',
      senador_alexandre_costa: 'Senador Alexandre Costa',
      senador_la_rocque: 'Senador La Rocque',
      serrano_do_maranhao: 'Serrano do Maranhão',
      sitio_novo: 'Sítio Novo',
      sucupira_do_norte: 'Sucupira do Norte',
      sucupira_do_riachao: 'Sucupira do Riachão',
      tasso_fragoso: 'Tasso Fragoso',
      timbiras: 'Timbiras',
      timon: 'Timon',
      trizidela_do_vale: 'Trizidela do Vale',
      tufilandia: 'Tufilândia',
      tuntum: 'Tuntum',
      turiacu: 'Turiaçu',
      turilandia: 'Turilândia',
      tutoia: 'Tutóia',
      urbano_santos: 'Urbano Santos',
      vargem_grande: 'Vargem Grande',
      viana: 'Viana',
      vila_nova_dos_martirios: 'Vila Nova dos Martírios',
      vitoria_do_mearim: 'Vitória do Mearim',
      vitorino_freire: 'Vitorino Freire',
      ze_doca: 'Zé Doca',
    },
    '#Estado': 'MA',
  };
  
  export default cidadesMA;