const cidadesGO = {
    '#empty_option': '- Selecione a Cidade -',
    '#options': {
      abadia_de_goias: 'Abadia de Goiás',
      abadiania: 'Abadiânia',
      acreuna: 'Acreúna',
      adelandia: 'Adelândia',
      agua_fria_de_goias: 'Água Fria de Goiás',
      agua_limpa: 'Água Limpa',
      aguas_lindas_de_goias: 'Águas Lindas de Goiás',
      alexania: 'Alexânia',
      aloandia: 'Aloândia',
      alto_horizonte: 'Alto Horizonte',
      alto_paraiso_de_goias: 'Alto Paraíso de Goiás',
      alvorada_do_norte: 'Alvorada do Norte',
      amaralina: 'Amaralina',
      americano_do_brasil: 'Americano do Brasil',
      amorinopolis: 'Amorinópolis',
      anapolis: 'Anápolis',
      anhanguera: 'Anhanguera',
      anicuns: 'Anicuns',
      aparecida_de_goiania: 'Aparecida de Goiânia',
      aparecida_do_rio_doce: 'Aparecida do Rio Doce',
      apore: 'Aporé',
      aracu: 'Araçu',
      aragarcas: 'Aragarças',
      aragoiania: 'Aragoiânia',
      araguapaz: 'Araguapaz',
      arenopolis: 'Arenópolis',
      aruana: 'Aruanã',
      aurilandia: 'Aurilândia',
      avelinopolis: 'Avelinópolis',
      baliza: 'Baliza',
      barro_alto: 'Barro Alto',
      bela_vista_de_goias: 'Bela Vista de Goiás',
      bom_jardim_de_goias: 'Bom Jardim de Goiás',
      bom_jesus_de_goias: 'Bom Jesus de Goiás',
      bonfinopolis: 'Bonfinópolis',
      bonopolis: 'Bonópolis',
      brazabrantes: 'Brazabrantes',
      britania: 'Britânia',
      buriti_alegre: 'Buriti Alegre',
      buriti_de_goias: 'Buriti de Goiás',
      buritinopolis: 'Buritinópolis',
      cabeceiras: 'Cabeceiras',
      cachoeira_alta: 'Cachoeira Alta',
      cachoeira_de_goias: 'Cachoeira de Goiás',
      cachoeira_dourada: 'Cachoeira Dourada',
      cacu: 'Caçu',
      caiaponia: 'Caiapônia',
      caldas_novas: 'Caldas Novas',
      caldazinha: 'Caldazinha',
      campestre_de_goias: 'Campestre de Goiás',
      campinacu: 'Campinaçu',
      campinorte: 'Campinorte',
      campo_alegre_de_goias: 'Campo Alegre de Goiás',
      campo_limpo_de_goias: 'Campo Limpo de Goiás',
      campos_belos: 'Campos Belos',
      campos_verdes: 'Campos Verdes',
      carmo_do_rio_verde: 'Carmo do Rio Verde',
      castelandia: 'Castelândia',
      catalao: 'Catalão',
      caturai: 'Caturaí',
      cavalcante: 'Cavalcante',
      ceres: 'Ceres',
      cezarina: 'Cezarina',
      chapadao_do_ceu: 'Chapadão do Céu',
      cidade_ocidental: 'Cidade Ocidental',
      cocalzinho_de_goias: 'Cocalzinho de Goiás',
      colinas_do_sul: 'Colinas do Sul',
      corrego_do_ouro: 'Córrego do Ouro',
      corumba_de_goias: 'Corumbá de Goiás',
      corumbaiba: 'Corumbaíba',
      cristalina: 'Cristalina',
      cristianopolis: 'Cristianópolis',
      crixas: 'Crixás',
      crominia: 'Cromínia',
      cumari: 'Cumari',
      damianopolis: 'Damianópolis',
      damolandia: 'Damolândia',
      davinopolis: 'Davinópolis',
      diorama: 'Diorama',
      divinopolis_de_goias: 'Divinópolis de Goiás',
      doverlandia: 'Doverlândia',
      edeadina: 'Edealina',
      edea: 'Edéia',
      estrela_do_norte: 'Estrela do Norte',
      faina: 'Faina',
      fazenda_nova: 'Fazenda Nova',
      firminopolis: 'Firminópolis',
      flores_de_goias: 'Flores de Goiás',
      formosa: 'Formosa',
      formoso: 'Formoso',
      gameleira_de_goias: 'Gameleira de Goiás',
      goianapolis: 'Goianápolis',
      goiandira: 'Goiandira',
      goianesia: 'Goianésia',
      goiania: 'Goiânia',
      goianira: 'Goianira',
      goias: 'Goiás',
      goiatuba: 'Goiatuba',
      gouvelandia: 'Gouvelândia',
      guapo: 'Guapó',
      guaraita: 'Guaraíta',
      guarani_de_goias: 'Guarani de Goiás',
      guarinos: 'Guarinos',
      heitorai: 'Heitoraí',
      hidrolandia: 'Hidrolândia',
      hidrolina: 'Hidrolina',
      iaciara: 'Iaciara',
      inaciolandia: 'Inaciolândia',
      indiara: 'Indiara',
      inhumas: 'Inhumas',
      ipameri: 'Ipameri',
      ipiranga_de_goias: 'Ipiranga de Goiás',
      ipora: 'Iporá',
      israelandia: 'Israelândia',
      itaberai: 'Itaberaí',
      itaguari: 'Itaguari',
      itaguaru: 'Itaguaru',
      itaja: 'Itajá',
      itapaci: 'Itapaci',
      itapirapua: 'Itapirapuã',
      itapuranga: 'Itapuranga',
      itaruma: 'Itarumã',
      itaucu: 'Itauçu',
      itumbiara: 'Itumbiara',
      ivolandia: 'Ivolândia',
      jandaia: 'Jandaia',
      jaragua: 'Jaraguá',
      jatai: 'Jataí',
      jaupaci: 'Jaupaci',
      jesupolis: 'Jesúpolis',
      joviania: 'Joviânia',
      jussara: 'Jussara',
      lagoa_santa: 'Lagoa Santa',
      leopoldo_de_bulhoes: 'Leopoldo de Bulhões',
      luziania: 'Luziânia',
      mairipotaba: 'Mairipotaba',
      mambai: 'Mambaí',
      mara_rosa: 'Mara Rosa',
      marzagao: 'Marzagão',
      matrincha: 'Matrinchã',
      maurilandia: 'Maurilândia',
      mimoso_de_goias: 'Mimoso de Goiás',
      minacu: 'Minaçu',
      mineiros: 'Mineiros',
      moipora: 'Moiporá',
      monte_alegre_de_goias: 'Monte Alegre de Goiás',
      montes_claros_de_goias: 'Montes Claros de Goiás',
      montividiu: 'Montividiu',
      montividiu_do_norte: 'Montividiu do Norte',
      morrinhos: 'Morrinhos',
      morro_agudo_de_goias: 'Morro Agudo de Goiás',
      mossamedes: 'Mossâmedes',
      mozarlandia: 'Mozarlândia',
      mundo_novo: 'Mundo Novo',
      mutunopolis: 'Mutunópolis',
      nazario: 'Nazário',
      neropolis: 'Nerópolis',
      niquelandia: 'Niquelândia',
      nova_america: 'Nova América',
      nova_aurora: 'Nova Aurora',
      nova_crixas: 'Nova Crixás',
      nova_gloria: 'Nova Glória',
      nova_iguacu_de_goias: 'Nova Iguaçu de Goiás',
      nova_roma: 'Nova Roma',
      nova_veneza: 'Nova Veneza',
      novo_brasil: 'Novo Brasil',
      novo_gama: 'Novo Gama',
      novo_planalto: 'Novo Planalto',
      orizona: 'Orizona',
      ouro_verde_de_goias: 'Ouro Verde de Goiás',
      ouvidor: 'Ouvidor',
      padre_bernardo: 'Padre Bernardo',
      palestina_de_goias: 'Palestina de Goiás',
      palmeiras_de_goias: 'Palmeiras de Goiás',
      palmelo: 'Palmelo',
      palminopolis: 'Palminópolis',
      panama: 'Panamá',
      paranaiguara: 'Paranaiguara',
      parauna: 'Paraúna',
      perolandia: 'Perolândia',
      petrolina_de_goias: 'Petrolina de Goiás',
      pilar_de_goias: 'Pilar de Goiás',
      piracanjuba: 'Piracanjuba',
      piranhas: 'Piranhas',
      pirenopolis: 'Pirenópolis',
      pires_do_rio: 'Pires do Rio',
      planaltina: 'Planaltina',
      pontalina: 'Pontalina',
      porangatu: 'Porangatu',
      porteirao: 'Porteirão',
      portelandia: 'Portelândia',
      posse: 'Posse',
      professor_jamil: 'Professor Jamil',
      quirinopolis: 'Quirinópolis',
      rialma: 'Rialma',
      rianapolis: 'Rianápolis',
      rio_quente: 'Rio Quente',
      rio_verde: 'Rio Verde',
      rubiataba: 'Rubiataba',
      sanclerlandia: 'Sanclerlândia',
      santa_barbara_de_goias: 'Santa Bárbara de Goiás',
      santa_cruz_de_goias: 'Santa Cruz de Goiás',
      santa_fe_de_goias: 'Santa Fé de Goiás',
      santa_helena_de_goias: 'Santa Helena de Goiás',
      santa_isabel: 'Santa Isabel',
      santa_rita_do_araguaia: 'Santa Rita do Araguaia',
      santa_rita_do_novo_destino: 'Santa Rita do Novo Destino',
      santa_rosa_de_goias: 'Santa Rosa de Goiás',
      santa_tereza_de_goias: 'Santa Tereza de Goiás',
      santa_terezinha_de_goias: 'Santa Terezinha de Goiás',
      santo_antonio_da_barra: 'Santo Antônio da Barra',
      santo_antonio_de_goias: 'Santo Antônio de Goiás',
      santo_antonio_do_descoberto: 'Santo Antônio do Descoberto',
      sao_domingos: 'São Domingos',
      sao_francisco_de_goias: 'São Francisco de Goiás',
      sao_joao_da_parauna: 'São João da Paraúna',
      sao_joao_dalianca: 'São João dAliança',
      sao_luis_de_montes_belos: 'São Luís de Montes Belos',
      sao_luiz_do_norte: 'São Luiz do Norte',
      sao_miguel_do_araguaia: 'São Miguel do Araguaia',
      sao_miguel_do_passa_quatro: 'São Miguel do Passa-Quatro',
      sao_patricio: 'São Patrício',
      sao_simao: 'São Simão',
      senador_canedo: 'Senador Canedo',
      serranopolis: 'Serranópolis',
      silvania: 'Silvânia',
      simolandia: 'Simolândia',
      sitio_dabadia: 'Sítio dAbadia',
      taquaral_de_goias: 'Taquaral de Goiás',
      teresina_de_goias: 'Teresina de Goiás',
      terezopolis_de_goias: 'Terezópolis de Goiás',
      tres_ranchos: 'Três Ranchos',
      trindade: 'Trindade',
      trombas: 'Trombas',
      turvania: 'Turvânia',
      turvelandia: 'Turvelândia',
      uirapuru: 'Uirapuru',
      uruacu: 'Uruaçu',
      uruana: 'Uruana',
      urutai: 'Urutaí',
      valparaiso_de_goias: 'Valparaíso de Goiás',
      varjao: 'Varjão',
      vianopolis: 'Vianópolis',
      vicentinopolis: 'Vicentinópolis',
      vila_boa: 'Vila Boa',
      vila_propicio: 'Vila Propício',
    },
    '#Estado': 'GO',
  };
  
  export default cidadesGO;
  