// cidadesTO.js
const cidadesTO = {
    '#empty_option': '- Selecione a Cidade -',
    '#options': {
      abreulandia: 'Abreulândia',
      aguiarnopolis: 'Aguiarnópolis',
      alianca_do_tocantins: 'Aliança do Tocantins',
      almas: 'Almas',
      alvorada: 'Alvorada',
      ananas: 'Ananás',
      angico: 'Angico',
      aparecida_do_rio_negro: 'Aparecida do Rio Negro',
      aragominas: 'Aragominas',
      araguacema: 'Araguacema',
      araguacu: 'Araguaçu',
      araguaina: 'Araguaína',
      araguana: 'Araguanã',
      araguatins: 'Araguatins',
      arapoema: 'Arapoema',
      arraias: 'Arraias',
      augustinopolis: 'Augustinópolis',
      aurora_do_tocantins: 'Aurora do Tocantins',
      axixa_do_tocantins: 'Axixá do Tocantins',
      babaculandia: 'Babaçulândia',
      bandeirantes_do_tocantins: 'Bandeirantes do Tocantins',
      barra_do_ouro: 'Barra do Ouro',
      barrolandia: 'Barrolândia',
      bernardo_sayao: 'Bernardo Sayão',
      bom_jesus_do_tocantins: 'Bom Jesus do Tocantins',
      brasilandia_do_tocantins: 'Brasilândia do Tocantins',
      brejinho_de_nazare: 'Brejinho de Nazaré',
      buriti_do_tocantins: 'Buriti do Tocantins',
      cachoeirinha: 'Cachoeirinha',
      campos_lindos: 'Campos Lindos',
      cariri_do_tocantins: 'Cariri do Tocantins',
      carmolandia: 'Carmolândia',
      carrasco_bonito: 'Carrasco Bonito',
      caseara: 'Caseara',
      centenario: 'Centenário',
      chapada_da_natividade: 'Chapada da Natividade',
      chapada_de_areia: 'Chapada de Areia',
      colinas_do_tocantins: 'Colinas do Tocantins',
      colmeia: 'Colméia',
      combinado: 'Combinado',
      conceicao_do_tocantins: 'Conceição do Tocantins',
      couto_magalhaes: 'Couto Magalhães',
      cristalandia: 'Cristalândia',
      crixas_do_tocantins: 'Crixás do Tocantins',
      darcinopolis: 'Darcinópolis',
      dianopolis: 'Dianópolis',
      divinopolis_do_tocantins: 'Divinópolis do Tocantins',
      dois_irmaos_do_tocantins: 'Dois Irmãos do Tocantins',
      duere: 'Dueré',
      esperantina: 'Esperantina',
      fatima: 'Fátima',
      figueiropolis: 'Figueirópolis',
      filadelfia: 'Filadélfia',
      formoso_do_araguaia: 'Formoso do Araguaia',
      fortaleza_do_tabocao: 'Fortaleza do Tabocão',
      goianorte: 'Goianorte',
      goiatins: 'Goiatins',
      guarai: 'Guaraí',
      gurupi: 'Gurupi',
      ipueiras: 'Ipueiras',
      itacaja: 'Itacajá',
      itaguatins: 'Itaguatins',
      itapiratins: 'Itapiratins',
      itapora_do_tocantins: 'Itaporã do Tocantins',
      jau_do_tocantins: 'Jaú do Tocantins',
      juarina: 'Juarina',
      lagoa_da_confusao: 'Lagoa da Confusão',
      lagoa_do_tocantins: 'Lagoa do Tocantins',
      lajeado: 'Lajeado',
      lavandeira: 'Lavandeira',
      lizard: 'Lizarda',
      luzinopolis: 'Luzinópolis',
      marianopolis_do_tocantins: 'Marianópolis do Tocantins',
      mateiros: 'Mateiros',
      maurilandia_do_tocantins: 'Maurilândia do Tocantins',
      miracema_do_tocantins: 'Miracema do Tocantins',
      miranorte: 'Miranorte',
      monte_do_carmo: 'Monte do Carmo',
      monte_santo_do_tocantins: 'Monte Santo do Tocantins',
      muricilandia: 'Muricilândia',
      natividade: 'Natividade',
      nazare: 'Nazaré',
      nova_olinda: 'Nova Olinda',
      nova_rosalandia: 'Nova Rosalândia',
      novo_acordo: 'Novo Acordo',
      novo_alegre: 'Novo Alegre',
      novo_jardim: 'Novo Jardim',
      oliveira_de_fatima: 'Oliveira de Fátima',
      palmas: 'Palmas',
      palmeirante: 'Palmeirante',
      palmeiras_do_tocantins: 'Palmeiras do Tocantins',
      palmeiropolis: 'Palmeirópolis',
      paraiso_do_tocantins: 'Paraíso do Tocantins',
      parana: 'Paranã',
      pau_darco: 'Pau dArco',
      pedro_afonso: 'Pedro Afonso',
      peixe: 'Peixe',
      pequizeiro: 'Pequizeiro',
      pindorama_do_tocantins: 'Pindorama do Tocantins',
      piraque: 'Piraquê',
      pium: 'Pium',
      ponte_alta_do_bom_jesus: 'Ponte Alta do Bom Jesus',
      ponte_alta_do_tocantins: 'Ponte Alta do Tocantins',
      porto_alegre_do_tocantins: 'Porto Alegre do Tocantins',
      porto_nacional: 'Porto Nacional',
      praia_norte: 'Praia Norte',
      presidente_kennedy: 'Presidente Kennedy',
      pugmil: 'Pugmil',
      recursolândia: 'Recursolândia',
      riachinho: 'Riachinho',
      rio_da_conceição: 'Rio da Conceição',
      rio_dos_bois: 'Rio dos Bois',
      rio_sono: 'Rio Sono',
      sampaio: 'Sampaio',
      sandolândia: 'Sandolândia',
      santa_fé_do_araguaia: 'Santa Fé do Araguaia',
      santa_maria_do_tocantins: 'Santa Maria do Tocantins',
      santa_rita_do_tocantins: 'Santa Rita do Tocantins',
      santa_rosa_do_tocantins: 'Santa Rosa do Tocantins',
      santa_tereza_do_tocantins: 'Santa Tereza do Tocantins',
      santa_terezinha_do_tocantins: 'Santa Terezinha do Tocantins',
      são_bento_do_tocantins: 'São Bento do Tocantins',
      são_félix_do_tocantins: 'São Félix do Tocantins',
      são_miguel_do_tocantins: 'São Miguel do Tocantins',
      são_salvador_do_tocantins: 'São Salvador do Tocantins',
      são_sebastião_do_tocantins: 'São Sebastião do Tocantins',
      são_valério_da_natividade: 'São Valério da Natividade',
      silvanópolis: 'Silvanópolis',
      sítio_novo_do_tocantins: 'Sítio Novo do Tocantins',
      sucupira: 'Sucupira',
      taguatinga: 'Taguatinga',
      taipas_do_tocantins: 'Taipas do Tocantins',
      talismã: 'Talismã',
      tocantínia: 'Tocantínia',
      tocantinópolis: 'Tocantinópolis',
      tupirama: 'Tupirama',
      tupiratins: 'Tupiratins',
      wanderlândia: 'Wanderlândia',
      xambioá: 'Xambioá',
    },
    '#Estado': 'TO',
  };
  
  export default cidadesTO;
