// cidadesSC.jsx
const cidadesSC = {
    '#empty_option': '- Selecione a Cidade -',
    '#options': {
      abdon_batista: 'Abdon Batista',
      abelardo_luz: 'Abelardo Luz',
      agrolandia: 'Agrolândia',
      agronomica: 'Agronômica',
      agua_doce: 'Água Doce',
      aguas_de_chapeco: 'Águas de Chapecó',
      aguas_frias: 'Águas Frias',
      aguas_mornas: 'Águas Mornas',
      alfredo_wagner: 'Alfredo Wagner',
      alto_bela_vista: 'Alto Bela Vista',
      anchieta: 'Anchieta',
      angelina: 'Angelina',
      anita_garibaldi: 'Anita Garibaldi',
      anitapolis: 'Anitápolis',
      antonio_carlos: 'Antônio Carlos',
      apiuna: 'Apiúna',
      arabuta: 'Arabutã',
      araquari: 'Araquari',
      ararangua: 'Araranguá',
      armazem: 'Armazém',
      arroio_trinta: 'Arroio Trinta',
      arvoredo: 'Arvoredo',
      ascurra: 'Ascurra',
      atalanta: 'Atalanta',
      aurora: 'Aurora',
      balneario_arroio_do_silva: 'Balneário Arroio do Silva',
      balneario_barra_do_sul: 'Balneário Barra do Sul',
      balneario_camboriu: 'Balneário Camboriú',
      balneario_gaivota: 'Balneário Gaivota',
      balneario_picarras: 'Balneário Piçarras',
      balneario_rincao: 'Balneário Rincão',
      bandeirante: 'Bandeirante',
      barra_bonita: 'Barra Bonita',
      barra_velha: 'Barra Velha',
      bela_vista_do_toldo: 'Bela Vista do Toldo',
      belmonte: 'Belmonte',
      benedito_novo: 'Benedito Novo',
      biguacu: 'Biguaçu',
      blumenau: 'Blumenau',
      bocaina_do_sul: 'Bocaina do Sul',
      bom_jardim_da_serra: 'Bom Jardim da Serra',
      bom_jesus: 'Bom Jesus',
      bom_jesus_do_oeste: 'Bom Jesus do Oeste',
      bom_retiro: 'Bom Retiro',
      bombinhas: 'Bombinhas',
      botuvera: 'Botuverá',
      braco_do_norte: 'Braço do Norte',
      braco_do_trombudo: 'Braço do Trombudo',
      brunopolis: 'Brunópolis',
      brusque: 'Brusque',
      cacador: 'Caçador',
      caibi: 'Caibi',
      calmon: 'Calmon',
      camboriu: 'Camboriú',
      campo_alegre: 'Campo Alegre',
      campo_belo_do_sul: 'Campo Belo do Sul',
      campo_ere: 'Campo Erê',
      campos_novos: 'Campos Novos',
      canelinha: 'Canelinha',
      canoinhas: 'Canoinhas',
      capao_alto: 'Capão Alto',
      capinzal: 'Capinzal',
      capivari_de_baixo: 'Capivari de Baixo',
      catanduvas: 'Catanduvas',
      caxambu_do_sul: 'Caxambu do Sul',
      celso_ramos: 'Celso Ramos',
      cerro_negro: 'Cerro Negro',
      chapadao_do_lageado: 'Chapadão do Lageado',
      chapeco: 'Chapecó',
      cocal_do_sul: 'Cocal do Sul',
      concordia: 'Concórdia',
      cordilheira_alta: 'Cordilheira Alta',
      coronel_freitas: 'Coronel Freitas',
      coronel_martins: 'Coronel Martins',
      correia_pinto: 'Correia Pinto',
      corupa: 'Corupá',
      criciuma: 'Criciúma',
      cunha_pora: 'Cunha Porã',
      cunhatai: 'Cunhataí',
      curitibanos: 'Curitibanos',
      descanso: 'Descanso',
      dionisio_cerqueira: 'Dionísio Cerqueira',
      dona_emma: 'Dona Emma',
      doutor_pedrinho: 'Doutor Pedrinho',
      entre_rios: 'Entre Rios',
      ermo: 'Ermo',
      erval_velho: 'Erval Velho',
      faxinal_dos_guedes: 'Faxinal dos Guedes',
      flor_do_sertao: 'Flor do Sertão',
      florianopolis: 'Florianópolis',
      formosa_do_sul: 'Formosa do Sul',
      forquilhinha: 'Forquilhinha',
      fraiburgo: 'Fraiburgo',
      frei_rogerio: 'Frei Rogério',
      galvao: 'Galvão',
      garopaba: 'Garopaba',
      garuva: 'Garuva',
      gaspar: 'Gaspar',
      governador_celso_ramos: 'Governador Celso Ramos',
      grao_para: 'Grão-Pará',
      gravatal: 'Gravatal',
      guabiruba: 'Guabiruba',
      guaraciaba: 'Guaraciaba',
      guaramirim: 'Guaramirim',
      guaruja_do_sul: 'Guarujá do Sul',
      guatambu: 'Guatambu',
      herval_doeste: 'Herval dOeste',
      ibiam: 'Ibiam',
      ibicare: 'Ibicaré',
      ibirama: 'Ibirama',
      icara: 'Içara',
      ilhota: 'Ilhota',
      imarui: 'Imaruí',
      imbituba: 'Imbituba',
      imbuia: 'Imbuia',
      indaial: 'Indaial',
      iomere: 'Iomerê',
      ipira: 'Ipira',
      ipora_do_oeste: 'Iporã do Oeste',
      ipuacu: 'Ipuaçu',
      ipumirim: 'Ipumirim',
      iraceminha: 'Iraceminha',
      irani: 'Irani',
      irati: 'Irati',
      irineopolis: 'Irineópolis',
      ita: 'Itá',
      itaiopolis: 'Itaiópolis',
      itajai: 'Itajaí',
      itapema: 'Itapema',
      itapiranga: 'Itapiranga',
      itapoa: 'Itapoá',
      ituporanga: 'Ituporanga',
      jabora: 'Jaborá',
      jacinto_machado: 'Jacinto Machado',
      jaguaruna: 'Jaguaruna',
      jaragua_do_sul: 'Jaraguá do Sul',
      jardinopolis: 'Jardinópolis',
      joacaba: 'Joaçaba',
      joinville: 'Joinville',
      jose_boiteux: 'José Boiteux',
      jupia: 'Jupiá',
      lacerdopolis: 'Lacerdópolis',
      lages: 'Lages',
      laguna: 'Laguna',
      lajeado_grande: 'Lajeado Grande',
      laurentino: 'Laurentino',
      lauro_muller: 'Lauro Müller',
      lebon_regis: 'Lebon Régis',
      leoberto_leal: 'Leoberto Leal',
      lindoia_do_sul: 'Lindóia do Sul',
      lontras: 'Lontras',
      luiz_alves: 'Luiz Alves',
      luzerna: 'Luzerna',
      macieira: 'Macieira',
      mafra: 'Mafra',
      major_gercino: 'Major Gercino',
      major_vieira: 'Major Vieira',
      maracaja: 'Maracajá',
      maravilha: 'Maravilha',
      marema: 'Marema',
      massaranduba: 'Massaranduba',
      matos_costa: 'Matos Costa',
      meleiro: 'Meleiro',
      mirim_doce: 'Mirim Doce',
      modelo: 'Modelo',
      mondai: 'Mondaí',
      monte_carlo: 'Monte Carlo',
      monte_castelo: 'Monte Castelo',
      morro_da_fumaca: 'Morro da Fumaça',
      morro_grande: 'Morro Grande',
      navegantes: 'Navegantes',
      nova_erechim: 'Nova Erechim',
      nova_itaberaba: 'Nova Itaberaba',
      nova_trento: 'Nova Trento',
      nova_veneza: 'Nova Veneza',
      novo_horizonte: 'Novo Horizonte',
      orleans: 'Orleans',
      otacilio_costa: 'Otacílio Costa',
      ouro: 'Ouro',
      ouro_verde: 'Ouro Verde',
      paial: 'Paial',
      painel: 'Painel',
      palhoca: 'Palhoça',
      palma_sola: 'Palma Sola',
      palmeira: 'Palmeira',
      palmitos: 'Palmitos',
      papanduva: 'Papanduva',
      paraiso: 'Paraíso',
      passo_de_torres: 'Passo de Torres',
      passos_maia: 'Passos Maia',
      paulo_lopes: 'Paulo Lopes',
      pedras_grandes: 'Pedras Grandes',
      penha: 'Penha',
      peritiba: 'Peritiba',
      pescaria_brava: 'Pescaria Brava',
      petrolandia: 'Petrolândia',
      pinhalzinho: 'Pinhalzinho',
      pinheiro_preto: 'Pinheiro Preto',
      piratuba: 'Piratuba',
      planalto_alegre: 'Planalto Alegre',
      pomerode: 'Pomerode',
      ponte_alta: 'Ponte Alta',
      ponte_alta_do_norte: 'Ponte Alta do Norte',
      ponte_serrada: 'Ponte Serrada',
      porto_belo: 'Porto Belo',
      porto_uniao: 'Porto União',
      pouso_redondo: 'Pouso Redondo',
      praia_grande: 'Praia Grande',
      presidente_castello_branco: 'Presidente Castello Branco',
      presidente_getulio: 'Presidente Getúlio',
      presidente_nereu: 'Presidente Nereu',
      princesa: 'Princesa',
      quilombo: 'Quilombo',
      rancho_queimado: 'Rancho Queimado',
      rio_das_antas: 'Rio das Antas',
      rio_do_campo: 'Rio do Campo',
      rio_do_oeste: 'Rio do Oeste',
      rio_do_sul: 'Rio do Sul',
      rio_dos_cedros: 'Rio dos Cedros',
      rio_fortuna: 'Rio Fortuna',
      rio_negrinho: 'Rio Negrinho',
      rio_rufino: 'Rio Rufino',
      riqueza: 'Riqueza',
      rodeio: 'Rodeio',
      romelandia: 'Romelândia',
      salete: 'Salete',
      saltinho: 'Saltinho',
      salto_veloso: 'Salto Veloso',
      sangao: 'Sangão',
      santa_cecilia: 'Santa Cecília',
      santa_helena: 'Santa Helena',
      santa_rosa_de_lima: 'Santa Rosa de Lima',
      santa_rosa_do_sul: 'Santa Rosa do Sul',
      santa_terezinha: 'Santa Terezinha',
      santa_terezinha_do_progresso: 'Santa Terezinha do Progresso',
      santiago_do_sul: 'Santiago do Sul',
      santo_amaro_da_imperatriz: 'Santo Amaro da Imperatriz',
      sao_bento_do_sul: 'São Bento do Sul',
      sao_bernardino: 'São Bernardino',
      sao_bonifacio: 'São Bonifácio',
      sao_carlos: 'São Carlos',
      sao_cristovao_do_sul: 'São Cristóvão do Sul',
      sao_domingos: 'São Domingos',
      sao_francisco_do_sul: 'São Francisco do Sul',
      sao_joao_batista: 'São João Batista',
      sao_joao_do_itaperiu: 'São João do Itaperiú',
      sao_joao_do_oeste: 'São João do Oeste',
      sao_joao_do_sul: 'São João do Sul',
      sao_joaquim: 'São Joaquim',
      sao_jose: 'São José',
      sao_jose_do_cedro: 'São José do Cedro',
      sao_jose_do_cerrito: 'São José do Cerrito',
      sao_lourenco_do_oeste: 'São Lourenço do Oeste',
      sao_ludgero: 'São Ludgero',
      sao_martinho: 'São Martinho',
      sao_miguel_da_boa_vista: 'São Miguel da Boa Vista',
      sao_miguel_do_oeste: 'São Miguel do Oeste',
      sao_pedro_de_alcantara: 'São Pedro de Alcântara',
      saudades: 'Saudades',
      schroeder: 'Schroeder',
      seara: 'Seara',
      serra_alta: 'Serra Alta',
      sideropolis: 'Siderópolis',
      sombrio: 'Sombrio',
      sul_brasil: 'Sul Brasil',
      taio: 'Taió',
      tangara: 'Tangará',
      tigrinhos: 'Tigrinhos',
      tijucas: 'Tijucas',
      timbe_do_sul: 'Timbé do Sul',
      timbo: 'Timbó',
      timbo_grande: 'Timbó Grande',
      tres_barras: 'Três Barras',
      treviso: 'Treviso',
      treze_de_maio: 'Treze de Maio',
      treze_tilias: 'Treze Tílias',
      trombudo_central: 'Trombudo Central',
      tubarao: 'Tubarão',
      tunapolis: 'Tunápolis',
      turvo: 'Turvo',
      uniao_do_oeste: 'União do Oeste',
      urubici: 'Urubici',
      urupema: 'Urupema',
      urussanga: 'Urussanga',
      vargeao: 'Vargeão',
      vargem: 'Vargem',
      vargem_bonita: 'Vargem Bonita',
      vidal_ramos: 'Vidal Ramos',
      videira: 'Videira',
      vitor_meireles: 'Vitor Meireles',
      witmarsum: 'Witmarsum',
      xanxere: 'Xanxerê',
      xavantina: 'Xavantina',
      xaxim: 'Xaxim',
      zortea: 'Zortéa',
    },
    '#Estado': 'SC',
  };
  
  export default cidadesSC;