// cidadesAM.js
const cidadesAM = {
    '#empty_option': '- Selecione a Cidade -',
    '#options': {
      alvaraes: 'Alvarães',
      amatura: 'Amaturá',
      anama: 'Anamã',
      anori: 'Anori',
      apui: 'Apuí',
      atalaia_do_norte: 'Atalaia do Norte',
      autazes: 'Autazes',
      barcelos: 'Barcelos',
      barreirinha: 'Barreirinha',
      benjamin_constant: 'Benjamin Constant',
      beruri: 'Beruri',
      boa_vista_do_ramos: 'Boa Vista do Ramos',
      boca_do_acre: 'Boca do Acre',
      borba: 'Borba',
      caapiranga: 'Caapiranga',
      canutama: 'Canutama',
      carauari: 'Carauari',
      careiro: 'Careiro',
      careiro_da_varzea: 'Careiro da Várzea',
      coari: 'Coari',
      codajas: 'Codajás',
      eirunepe: 'Eirunepé',
      envira: 'Envira',
      fonte_boa: 'Fonte Boa',
      guajara: 'Guajará',
      humaita: 'Humaitá',
      ipixuna: 'Ipixuna',
      iranduba: 'Iranduba',
      itacoatiara: 'Itacoatiara',
      itamarati: 'Itamarati',
      itapiranga: 'Itapiranga',
      japura: 'Japurá',
      jurua: 'Juruá',
      jutai: 'Jutaí',
      labrea: 'Lábrea',
      manacapuru: 'Manacapuru',
      manaquiri: 'Manaquiri',
      manaus: 'Manaus',
      manicore: 'Manicoré',
      maraa: 'Maraã',
      maues: 'Maués',
      nhamunda: 'Nhamundá',
      nova_olinda_do_norte: 'Nova Olinda do Norte',
      novo_airao: 'Novo Airão',
      novo_aripuana: 'Novo Aripuanã',
      parintins: 'Parintins',
      pauini: 'Pauini',
      presidente_figueiredo: 'Presidente Figueiredo',
      rio_preto_da_eva: 'Rio Preto da Eva',
      santa_isabel_do_rio_negro: 'Santa Isabel do Rio Negro',
      santo_antonio_do_ica: 'Santo Antônio do Içá',
      sao_gabriel_da_cachoeira: 'São Gabriel da Cachoeira',
      sao_paulo_de_olivenca: 'São Paulo de Olivença',
      sao_sebastiao_do_uatuma: 'São Sebastião do Uatumã',
      silves: 'Silves',
      tabatinga: 'Tabatinga',
      tapaua: 'Tapauá',
      tefe: 'Tefé',
      tonantins: 'Tonantins',
      uarini: 'Uarini',
      urucara: 'Urucará',
      urucurituba: 'Urucurituba',
    },
    '#Estado': 'AM',
  };
  
  export default cidadesAM;