const cidadesCE = {
    '#empty_option': '- Selecione a Cidade -',
    '#options': {
      abaiara: 'Abaiara',
      acarape: 'Acarape',
      acarau: 'Acaraú',
      acopiara: 'Acopiara',
      aiuaba: 'Aiuaba',
      alcantaras: 'Alcântaras',
      altaneira: 'Altaneira',
      alto_santo: 'Alto Santo',
      amontada: 'Amontada',
      antonina_do_norte: 'Antonina do Norte',
      apuiares: 'Apuiarés',
      aquiraz: 'Aquiraz',
      aracati: 'Aracati',
      aracoiaba: 'Aracoiaba',
      ararenda: 'Ararendá',
      araripe: 'Araripe',
      aratuba: 'Aratuba',
      arneiroz: 'Arneiroz',
      assare: 'Assaré',
      aurora: 'Aurora',
      baixio: 'Baixio',
      banabuiu: 'Banabuiú',
      barbalha: 'Barbalha',
      barreira: 'Barreira',
      barro: 'Barro',
      barroquinha: 'Barroquinha',
      baturite: 'Baturité',
      beberibe: 'Beberibe',
      bela_cruz: 'Bela Cruz',
      boa_viagem: 'Boa Viagem',
      brejo_santo: 'Brejo Santo',
      camocim: 'Camocim',
      campos_sales: 'Campos Sales',
      caninde: 'Canindé',
      capistrano: 'Capistrano',
      caridade: 'Caridade',
      carire: 'Cariré',
      caririacu: 'Caririaçu',
      carius: 'Cariús',
      carnaubal: 'Carnaubal',
      cascavel: 'Cascavel',
      catarina: 'Catarina',
      catunda: 'Catunda',
      caucaia: 'Caucaia',
      cedro: 'Cedro',
      chaval: 'Chaval',
      choro: 'Choró',
      chorozinho: 'Chorozinho',
      coreau: 'Coreaú',
      crateus: 'Crateús',
      crato: 'Crato',
      croata: 'Croatá',
      cruz: 'Cruz',
      deputado_irapuan_pinheiro: 'Deputado Irapuan Pinheiro',
      erere: 'Ereré',
      eusebio: 'Eusébio',
      farias_brito: 'Farias Brito',
      forquilha: 'Forquilha',
      fortaleza: 'Fortaleza',
      fortim: 'Fortim',
      frecheirinha: 'Frecheirinha',
      general_sampaio: 'General Sampaio',
      graca: 'Graça',
      granja: 'Granja',
      granjeiro: 'Granjeiro',
      groairas: 'Groaíras',
      guaiuba: 'Guaiúba',
      guaraciaba_do_norte: 'Guaraciaba do Norte',
      guaramiranga: 'Guaramiranga',
      hidrolandia: 'Hidrolândia',
      horizonte: 'Horizonte',
      ibaretama: 'Ibaretama',
      ibiapina: 'Ibiapina',
      ibicuitinga: 'Ibicuitinga',
      icapui: 'Icapuí',
      ico: 'Icó',
      iguatu: 'Iguatu',
      independencia: 'Independência',
      ipaporanga: 'Ipaporanga',
      ipaumirim: 'Ipaumirim',
      ipu: 'Ipu',
      ipueiras: 'Ipueiras',
      iracema: 'Iracema',
      iraucuba: 'Irauçuba',
      itaicaba: 'Itaiçaba',
      itaitinga: 'Itaitinga',
      itapaje: 'Itapajé',
      itapipoca: 'Itapipoca',
      itapiuna: 'Itapiúna',
      itarema: 'Itarema',
      itatira: 'Itatira',
      jaguaretama: 'Jaguaretama',
      jaguaribara: 'Jaguaribara',
      jaguaribe: 'Jaguaribe',
      jaguaruana: 'Jaguaruana',
      jardim: 'Jardim',
      jati: 'Jati',
      jijoca_de_jericoacoara: 'Jijoca de Jericoacoara',
      juazeiro_do_norte: 'Juazeiro do Norte',
      jucas: 'Jucás',
      lavras_da_mangabeira: 'Lavras da Mangabeira',
      limoeiro_do_norte: 'Limoeiro do Norte',
      madalena: 'Madalena',
      maracanau: 'Maracanaú',
      maranguape: 'Maranguape',
      marco: 'Marco',
      martinopole: 'Martinópole',
      massape: 'Massapê',
      mauriti: 'Mauriti',
      meruoca: 'Meruoca',
      milagres: 'Milagres',
      milha: 'Milhã',
      miraima: 'Miraíma',
      missao_velha: 'Missão Velha',
      mombaca: 'Mombaça',
      monsenhor_tabosa: 'Monsenhor Tabosa',
      morada_nova: 'Morada Nova',
      moraujo: 'Moraújo',
      morrinhos: 'Morrinhos',
      mucambo: 'Mucambo',
      mulungu: 'Mulungu',
      nova_olinda: 'Nova Olinda',
      nova_russas: 'Nova Russas',
      novo_oriente: 'Novo Oriente',
      ocara: 'Ocara',
      oros: 'Orós',
      pacajus: 'Pacajus',
      pacatuba: 'Pacatuba',
      pacoti: 'Pacoti',
      pacuja: 'Pacujá',
      palhano: 'Palhano',
      palmacia: 'Palmácia',
      paracuru: 'Paracuru',
      paraipaba: 'Paraipaba',
      parambu: 'Parambu',
      paramoti: 'Paramoti',
      pedra_branca: 'Pedra Branca',
      penaforte: 'Penaforte',
      pentecoste: 'Pentecoste',
      pereiro: 'Pereiro',
      pindoretama: 'Pindoretama',
      piquet_carneiro: 'Piquet Carneiro',
      pires_ferreira: 'Pires Ferreira',
      poranga: 'Poranga',
      porteiras: 'Porteiras',
      potengi: 'Potengi',
      potiretama: 'Potiretama',
      quiterianopolis: 'Quiterianópolis',
      quixada: 'Quixadá',
      quixelo: 'Quixelô',
      quixeramobim: 'Quixeramobim',
      quixere: 'Quixeré',
      redencao: 'Redenção',
      reriutaba: 'Reriutaba',
      russas: 'Russas',
      saboeiro: 'Saboeiro',
      salitre: 'Salitre',
      santa_quiteria: 'Santa Quitéria',
      santana_do_acarau: 'Santana do Acaraú',
      santana_do_cariri: 'Santana do Cariri',
      sao_benedito: 'São Benedito',
      sao_goncalo_do_amarante: 'São Gonçalo do Amarante',
      sao_joao_do_jaguaribe: 'São João do Jaguaribe',
      sao_luis_do_curu: 'São Luís do Curu',
      senador_pompeu: 'Senador Pompeu',
      senador_sa: 'Senador Sá',
      sobral: 'Sobral',
      solonopole: 'Solonópole',
      tabuleiro_do_norte: 'Tabuleiro do Norte',
      tamboril: 'Tamboril',
      tarrafas: 'Tarrafas',
      taua: 'Tauá',
      tejucuoca: 'Tejuçuoca',
      tiangua: 'Tianguá',
      trairi: 'Trairi',
      tururu: 'Tururu',
      ubajara: 'Ubajara',
      umari: 'Umari',
      umirim: 'Umirim',
      uruburetama: 'Uruburetama',
      uruoca: 'Uruoca',
      varjota: 'Varjota',
      varzea_alegre: 'Várzea Alegre',
      vicosa_do_ceara: 'Viçosa do Ceará',
    },
    '#Estado': 'CE',
  };
  
  export default cidadesCE;